### ISSUE TITLE
[HELP WANTED] Looking for Wiki Curator/Issue Manager

### ISSUE THREAD

**Issue by kvangent** [kvangent/PokeAlarm#102]
Title says it all. I'm looking for a volunteer willing to help me keep the Wiki up-to-date and issues tidy and marked correctly. I would prefer to be able to spend more of my limited free time working on the project itself, but I don't want to leave anyone having issues out in the cold. I just need someone to keep things organized so I spend more time on improving the project.

## Suggested Requirements
Proficient in English
Proficient (or willing to learn) Markdown format
Comfortable with basic linux
Comfortable with basic git commands
Perferably knows some basic python
Willing to check in every hour or two during the day

If anyone is interested please let me know.

**Comment by theresthatguy** [comment]
I will make no promises but I am willing to help. I'm native english speaker, been wanting to learn some markdown, linux mint is my daily OS, not to familiar with git commands other than clone, did something basic python programming years ago (to which i can provide links if desired).

**Comment by brettgus** [comment]
I could help sporadically if needed.  Have some programming background, but minimal python interaction (but have been able to learn enough to submit some PRs).  Have linux background, just learning git.  Familiar with markdown.

**Comment by kvangent** [comment]
@theresthatguy @brettgus Sorry it's taken me so long to get back to you guys. If you could both join this [discord channel] (https://discord.gg/QRgZa), I am going to try to coordinate things from there.

**Comment by reme-dy** [comment]
I'm willing to lend a hand with the wiki.  Markdown shouldn't be tough ([cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)) and I've seen the requests increase as the popularity of the project has grown in the past few weeks.

**Comment by kvangent** [comment]
@reme-dy Come talk to me in [discord ](https://discord.gg/hHJW5)sometime.
