### ISSUE TITLE
[BUG] Exception in thread Thread-1

### ISSUE THREAD

**Issue by Samras** [kvangent/PokeAlarm#106]
## Your Environment

Operating System:  Debian 8.4 Jessie
Python Version: Python 2.7.12
PokemonGo-Map startup command: `python runserver.py -ns -l '51.5189246068, 7.46500957478' -st 3 -a ptc -u XXXXX -p 'XXXXX' -k CENSORED -wh http://127.0.0.1:4000`  
PokeAlarm startup command: `python runwebhook.py`

Did the issue persist after restarting the script?: yes

## Console Output

```
	Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/poke/PokeAlarm/alarms/alarm_manager.py", line 72, in run
    self.trigger_pkmn(data['message'])
  File "/home/poke/PokeAlarm/alarms/alarm_manager.py", line 109, in trigger_pkmn
    if config['GEOFENCE'] is not None and not config['GEOFENCE'].contains(lat,lng):
KeyError: 'GEOFENCE'

```

## Your Alarms Config

```json
    [
                {
                        "active":"False",
                        "type":"pushbullet",
                        "api_key":"YOUR_API_KEY"
                },
                {
                        "active": "False",
                        "type":"slack",
                        "api_key":"YOUR_API_KEY",
                        "channel":"#general"
                },
                {
                        "active": "False",
                        "type":"twilio",
                        "account_sid":"YOUR_API_KEY",
                        "auth_token":"YOUR_AUTH_TOKEN",
                        "from_number":"YOUR_FROM_NUM",
                        "to_number":"YOUR_TO_NUM"
                },
                {
                        "active": "True",
                        "type":"telegram",
                        "bot_token":"XXXXXXXX",
                        "chat_id":"-XXXXXXX"
                },
                {
                        "active": "False",
                        "type": "pushover",
                        "app_token": "YOUR_APP_TOKEN",
                        "user_key": "YOUR_USER_KEY"
                }
        ],

```

## Troubleshooting Checklist
[X ] Most recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

-->

**Comment by kvangent** [comment]
@Samras Sorry about that. Try to do a new pull and the problem should be fixed.

**Comment by Samras** [comment]
@kvangent 
now getting another error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/poke/PokeAlarm/alarms/alarm_manager.py", line 72, in run
    self.trigger_pkmn(data['message'])
  File "/home/poke/PokeAlarm/alarms/alarm_manager.py", line 88, in trigger_pkmn
    log.info(name + " ignore: time_left has passed.")
UnboundLocalError: local variable 'name' referenced before assignment

**Comment by kvangent** [comment]
@Samras That's weird, I wasn't getting that error but I can see why it would.. Try to pull again and see what happens.
