### ISSUE TITLE
[ENHANCEMENT] Quiet hours to prevent messages overnight

### ISSUE THREAD

**Issue by DyonR** [kvangent/PokeAlarm#108]
Add an option for 'quiet hours'.

Most people only use PokeAlarm when they are awake, so sending messages overnight causes a lot of non relevant messages to appear on whatever-platform-you-use when you wake up.
I think it is nice if we could have an option like 'Only send messages between 7:00 and 23:00'.

**Comment by theresthatguy** [comment]
You didn't mention what system you're pushing the notifications to. Concerning Slack, it has "Do Not Disturb" functionality that each user can customize as well as custom notifications settings per channel.

**Comment by DyonR** [comment]
I am using Telegram myself, I know that it is possible to mute a chat, but
it would be nice if PokeAlarms could do it.

Op 13 aug. 2016 02:20 schreef "theresthatguy" <notifications@github.com>:

**Comment by kvangent** [comment]
You could just shut the server off at night as well.

**Comment by DyonR** [comment]
True, but automation is nicer than doing it manually.
It was just a quick thought that I had :)

Op 13 aug. 2016 02:42 schreef "Kurtis Van Gent" <notifications@github.com>:

**Comment by brettgus** [comment]
@DyonR there are probably other tools you could use to do this rather than making it part of PokeAlarm (and add to feature bloat).  Kill the process at a scheduled time, start it up at another time.. just a thought.

**Comment by DyonR** [comment]
Sure, I will write a script in bash to do it.

Op 14 aug. 2016 00:23 schreef "brettgus" <notifications@github.com>:

**Comment by roflinger** [comment]
not tested, should work.. only the loop may have a problem

`@echo off
color 0b
cls
echo ###########################
echo.
echo     When to shutdown
echo.
echo ###########################
set /p shutdown=
cls

echo ###########################
echo.
echo            When to start
echo        Format: hh:mm
echo ###########################
set /p start=
cls

echo Shutdown on %shutdown%
echo Startup on %start%

:loop
for /f %%h in ('time /T') do set hour=%%h


if %hour%==%shutdown (C:\windows\system32\taskkill.exe /IM python* /f)
if %hour%==%start% ( your start command ) ELSE (goto:loop)

`

**Comment by brettgus** [comment]
Also, just a thought, I have do not disturb turned on on my iPhone from 1:30am to 6am so nothing (except callers I make exceptions for) will cause any notifications.  Another possible solution.

**Comment by kvangent** [comment]
To be honest, this is something that is going to be way far down on my list. Simply because if you prefer to not get messages, you can just shut the server off and start it back up when you are ready to receive again. 

I'm not saying its something I'm not going to ever do, it's just a very low priority at the moment.

**Comment by kvangent** [comment]
I'm going to close this issue because I have no plans to implement it any time soon. If someone wishes to do it and submit a PR that is good with me.
