### ISSUE TITLE
[ENHANCEMENT] Add Telegram Bot Commands

### ISSUE THREAD

**Issue by Kyriten** [kvangent/PokeAlarm#111]
## Enhancement Description

Telegram bots allow commands given through the chat interface. It would be incredible to be able to configure PokeAlarm on the go through commands. Possible commands could include:

* /start - Start receiving notifications
* /stop - Stop notifications
* /add [pokemon]... - Adds Pokémon to the watchlist (space or comma separated list)
* /remove [pokemon]... - Removes Pokémon from the watchlist (space or comma separated list)
* /list - Lists Pokémon currently on your watchlist
* /location - change location
* /reset - Resets your watchlist to the default 
* /help - Displays this helpful list of commands

## Use cases

This would allow users to go choose what they want to be notified to while out and about. This would also mean less direct changes to the config.json, meaning less chances for human error (an invalid command would be ignored).

**Comment by brettgus** [comment]
Are you talking about more than one user being able to have a different watchlist?

**Comment by kvangent** [comment]
Something I'm interested in doing, but there are a few issues related to how it would work. Would it control all the other alarms as well? Would just JUST effect telegram notifications? 

Again, not something I'm going to be against but might be a while before I find a solution that I am happy with.

**Comment by Kyriten** [comment]
@brettgus it could be used for more than one user if implemented that way, but I was just thinking it would be useful for a single user.

@kvangent I don't think it would be able to control other alarms, as the functionality is part of the Telegram Bot API specifically...unless you had the Telegram Bot save to a variable accessible to the other alarms (but that might cause more problems then it's worth).

**Comment by anonacct** [comment]
@kvangent if you have any form of beta with this at any point I'd love to test it out.  The ability to change location while in the field would drastically improve the value of location sensitive distance alerts.

**Comment by kvangent** [comment]
Consolidating to #148.
