### ISSUE TITLE
[Enhancement] Ability not to send Pokemon below a duration of x minutes.

### ISSUE THREAD

**Issue by kevdotcom** [kvangent/PokeAlarm#116]
This would be great in a scenario where you scan a big area for multiple people, because the chat wouldn't get spammed with Pokemon nobody can get. (below 5 minutes)

**Comment by cheezy64** [comment]
I think the `--skip-lured` argument would solve the majority of this for you, since I'm pretty sure all of them are < 3min

**Comment by kvangent** [comment]
--Skip-lured no longer works because of changes to the api from niantic

**Comment by theresthatguy** [comment]
I think seconds would be better than minutes. I wouldn't mind seeing a 3 minute timer but not, say 90 seconds or less.

**Comment by kevdotcom** [comment]
It's not about the lured Pokemon, but my scan seems to have some hiccups every now and then and goes slow, resulting in sometimes finding Pokemon with only 5 minutes or less left.

**Comment by kvangent** [comment]
As of commit 62f5e885cfedd0ef28a6cc36e329c8aaaac173f0, you can now specify the number of seconds you wish to have remaining with `-tl X`, where X is the number of seconds.
