### ISSUE TITLE
[ENHANCEMENT] better translation

### ISSUE THREAD

**Issue by Viper2k4** [kvangent/PokeAlarm#119]
## Enhancement Description
Actual the only possible translation are the Pokemon-Names. What u think about adding Messages to the Localization file?

Somthing like this:

```
{
    "msg": {
        "wildPoke": "Ein wildes <pkmn> ist aufgetaucht!",
        "timeUntil": "Verfügbar bis <24h_time> (<time_left>).",
    }
    "pokemon": {
        "1": "Bisasam",
        "2": "Bisaknosp",
        "3": "Bisaflor",
        "4": "Glumanda",
        "5": "Glutexo",
        "6": "Glurak",
        "7": "Schiggy",
        "8": "Schillok",
        "9": "Turtok",
        "10": "Raupy",
        "11": "Safcon",
        "12": "Smettbo",
        "13": "Hornliu",
        "14": "Kokuna".
        ....
    }
}
```

## Use cases

Better feeling :)

**Comment by kvangent** [comment]
You can already do custom messages in whatever language you want.

**Comment by Viper2k4** [comment]
And on what point?

**Comment by Viper2k4** [comment]
ok found it (in the code^^). But a small info in the file,wiki or doku would be cool ^^

**Comment by kvangent** [comment]
There is info in the wiki, it's under Alarms Configuration and every service has the listed fields.
