### ISSUE TITLE
[ENHANCEMENT] Auto delete Tweet after the pokemon disappeared

### ISSUE THREAD

**Issue by Teelve** [kvangent/PokeAlarm#123]
## Enhancement Description

Auto delete tweet after the pokemon expire
## Use cases

To prevent spam on the twitter wall, and improve readability

**Comment by brettgus** [comment]
A workaround is to use something like this [YoSmudge/twdlt](https://github.com/YoSmudge/twdlt), it's a script to delete tweets.  You could set age to .25, so any tweets older than 15 minutes would be deleted.  Just a thought.

Of course, if this isn't a dedicated twitter account for pokemon location tweets, that'd be a little dangerous.

**Comment by jnovack** [comment]
... why wouldn't you make a dedicated account?  Who is following @hotsexxy123 for her pokemon location tweets??

**Comment by kvangent** [comment]
After some discussion, we've decided not to include this feature at this time because we feel the population that would use it compared to the time to implement is not great. If someone else wants to develop it and submit a PR, we will evaluate it then.
