### ISSUE TITLE
[ENHANCEMENT] Telegram: Multiple Chats 

### ISSUE THREAD

**Issue by Albert62** [kvangent/PokeAlarm#124]
## Enhacement Description
Being able to use multiple chat id's..

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
You can use multiple chat ids. Just make multiple alarms, each with a different chat id.

**Comment by bilalkamoon** [comment]
@kvangent I don't get how can this be implemented? What do you mean with multiple alarms? multiple alarms.json?

**Comment by Albert62** [comment]
@bilalkamoon actually you can, it was an error on my end. I was missing one bracket which broke everything.
1. Go to 'alarms.json'
2. Now recreate a new alarm using telegram and a different chat id.
Don't forget to add the new bracket, that was my mistake it should look like this
`
		{
			"active": "True",
			"type":"telegram",
			"bot_token":"TELEGRAM_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
`
You can reuse your bot's token

**Comment by kvangent** [comment]
@bilalkamoon You can configure as many alarms as you want, using any combination of services, just like @Albert62 said.

**Comment by aczone** [comment]
just wonder if multiple alarms are sent async?

**Comment by kvangent** [comment]
@aczone No, they aren't currently.
