### ISSUE TITLE
[ENHANCEMENT] Add ability to notify on certain rarity levels

### ISSUE THREAD

**Issue by Jericon** [kvangent/PokeAlarm#125]
## Enhancement Description
The PokemonGo-Map displays a rarity of each pokemon.  It also has the ability to notify based on rarity.  It would be nice if we could set a rarity: Notify for Ultra Rare only, for example

## Use cases
Notifying a specific rarity without having to configure each pokemon as on or off.

**Comment by kvangent** [comment]
The problem with this is rarity is very situational and varies person to person. The current structure, while perhaps a tad bit more work, is much more clear.

**Comment by justj0sh** [comment]
Could import some of this guy's code? https://github.com/eugenio412/PogomBOT
