### ISSUE TITLE
[Enhancement] Add lure notifications for nearby pokestops

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#126]
## Enhancement Description

New [commit ](https://github.com/PokemonGoMap/PokemonGo-Map/commit/51fd3c0cfb48975e6e4cf40f9ed5c8dda4832d43)from PokemonGo-Maps enables pokestop information:

``` python
                     webhook_data = {
 +                        'pokestop_id': f['id'],
 +                        'enabled': f['enabled'],
                          'latitude': f['latitude'],
                          'longitude': f['longitude'],
                          'last_modified_time': f['last_modified_timestamp_ms'],
 +                        'lure_expiration': lure_expiration,
                          'active_fort_modifier': active_fort_modifier
                      }
```
Would be great if we could be notified of nearby lures within a certain range and when they'll expire
## Use cases

Notification of nearby lures ("hey, someone placed a module down the block!  It has 20 minutes left!")
## Other Links

https://github.com/PokemonGoMap/PokemonGo-Map/commit/51fd3c0cfb48975e6e4cf40f9ed5c8dda4832d43

**Comment by ObviousLeeGitHub** [comment]
that would be awesome :+1:

**Comment by kvangent** [comment]
@ObviousLeeGitHub @reme-dy 

If anyone wants to alpha-test this, checkout this [branch](https://github.com/kvangent/PokeAlarm/tree/alert_updates); 

The config system has changed slightly, and we'll be updating the wiki shortly. In the meantime, here is an example of what an extended version slack looks like:
```json
{
    "type":"slack",
    "active":"True",
    "api_key":"YOUR_API_KEY_HERE",
		"pokemon":{
			"channel":"general",
			"username":"<pkmn>",
			"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
			"title":"A wild <pkmn> has appeared!",
			"url":"<gmaps>",
			"body": "Available until <24h_time> (<time_left>)."
		},
		"pokestop":{
			"channel":"general",
			"username":"Pokestop",
			"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/pokestop.png",
			"title":"Someone has placed a lure on a Pokestop!",
			"url":"<gmaps>",
			"body":"Lure will expire at <24h_time> (<time_left>)."
		}
}
```

Let me know if anyone has any issues.

**Comment by ObviousLeeGitHub** [comment]
I'm running it right now and it seems to work just fine so far :) thanks

**Comment by kvangent** [comment]
@ObviousLeeGitHub Thanks for the headsup, this should be fixed.

**Comment by ObviousLeeGitHub** [comment]
@kvangent It was fixed after updating to https://github.com/kvangent/PokeAlarm/commit/084b57c4e585fdae129301b42738650a4565adcf

Thanks again

**Comment by kvangent** [comment]
This is now completed as of commit 9b5368a166bad41c7b0d3a81c5e14f98579d5bb4. If anyone has problems, please open additional issues.
