### ISSUE TITLE
[ENHANCEMENT] Frontend Idea

### ISSUE THREAD

**Issue by rrbailey89** [kvangent/PokeAlarm#128]
## Enhancement Description

A nice frontend, preferably one accesible via the browser at either localhost:port or your public ip:port with this frontend you should be able to see statistics, configure alarms on the fly and maybe other things that may come to your mind.
## Use cases

Allow the configuration of alarms on the fly, and see stats .. "x number of notifications sent today"

**Comment by kvangent** [comment]
Consolidating to #148.
