### ISSUE TITLE
[ENHANCEMENT] Send Pokemon Location and map in the same message (Telegram).

### ISSUE THREAD

**Issue by Toetje585** [kvangent/PokeAlarm#129]
## Problem Description

It's unlogocal to send te map first and the location after. I would like to see the map in the same message below the location info.

                        try_sending(log, self.connect, "Telegram (loc)", self.client.sendLocation, locargs)

                try_sending(log, self.connect, "Telegram", self.client.sendMessage, args)

## Your Environment

Operating System:  Ubuntu 16.04
Python Version: (use `python -V`) 2.7.12 
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

## Enhancement Description

Send the Found Pokemon and Map in the same message.

## Use cases

Makes the chat easy to read for large groups.

**Comment by Toetje585** [comment]
I'm not a programmer but would love if someone is able to get this up.

**Comment by kvangent** [comment]
The reason it is sent in two messages is because it's using Telegrams [sendLocation ](https://core.telegram.org/bots/api#sendlocation)from the API, which doesn't allow for additional text.

**Comment by reme-dy** [comment]
Closing, beyond Telegram's capability.

**Comment by kvangent** [comment]
I think we can actually do this, but it going to take a while.

**Comment by sLoPPydrive** [comment]
How? The Telegram API doesn't seem to allow this. Of course one could create an image of an excerpt of the map and post the image together with the text+GMaps Link (like with Slack) but that would make the map rather uncool. The actual location post allows for quickly opening the map on your mobile being able to zoom and pan around and (at least on iOS) start navigation with the app of your choice (Apple Maps, Google Maps, Waze, etc.). I would love to have everything in 1 message but I don't see that happening. What I would change is the order of messages. First the text then the map.

**Comment by kvangent** [comment]
@sLoPPydrive I was just going to introduce a static map like is included in Slack at the moment. Using the web app for telegram, this is virtually the same. Are you tellling me the mobile app makes more use of this then just adding the link to the image?

**Comment by kvangent** [comment]
If anyone who uses the Telegram app could tell me if the mobile app does more then add a static image, please let me know.

**Comment by sLoPPydrive** [comment]
Sorry, that I answer so late. Yes, the mobile app for iOS does more. The location post is first a small minimap which you can tap:
![thumb_img_1061_1024](https://cloud.githubusercontent.com/assets/3931865/17948398/06f6e0ec-6a51-11e6-8d7c-3cdf2f537bd8.jpg)

If you tap it a full Apple Maps view opens up where you can actually get directions to the location (choosing between several installed navigation maps):
![thumb_img_1062_1024](https://cloud.githubusercontent.com/assets/3931865/17948405/0ef50a26-6a51-11e6-8b9f-6b4f3eb8bf83.jpg)

**Comment by kvangent** [comment]
In that case, I'll leave it alone the way it is.
