### ISSUE TITLE
Telegram issues

### ISSUE THREAD

**Issue by Blamroc** [kvangent/PokeAlarm#13]
As mentioned in the reddit thread, this needs to be added to alarms.json to get Telegram to work:

```
    {
        "active": "True",
        "type":"telegram",
        "chat_id":"your bot chat ID",
        "bot_token":"your bot API"
    },
```
For fellow newbies reading this: I used this tutorial to start my Telegram bot and get the token and chat_id: http://www.domoticz.com/wiki/Telegram_Bot

**Comment by kvangent** [comment]
Thank you for this, I've got it updated now.
