### ISSUE TITLE
Enhancement: More Clarity For Dynamic Substitutions Please

### ISSUE THREAD

**Issue by rrbailey89** [kvangent/PokeAlarm#130]
## Enhancement Description

Browsing [this page](https://github.com/kvangent/PokeAlarm/wiki/Alarm-Configuration) it is unclear where or how the substitutions should be used.
## Use cases

I believe that clarifying and showing a code example with the substitutions in action would be beneficial to the userbase and new users to come.

**Comment by kvangent** [comment]
@rrbailey89 We're in the process of trying to make the wiki easier to understand.

**Comment by brettgus** [comment]
@rrbailey89 Made some changes to explain dynamic subsitutions... does that clarify it a bit?

**Comment by rrbailey89** [comment]
@brettgus yes it does. Thank you :+1:
