### ISSUE TITLE
Enhancement: The Ability To Choose High Resolution Icons For Slack Or Other Alarms.

### ISSUE THREAD

**Issue by rrbailey89** [kvangent/PokeAlarm#131]
## Enhancement Description

I and Im sure others would like to be able to display the high resolution icons in slack or other alarms. Currently low res icons are displayed.
## Use cases

Prettier, Cleaner Look.

## Other Links

![icons-large-sprite](https://cloud.githubusercontent.com/assets/6540217/17783123/73d6fc72-652b-11e6-8024-70af69ba7574.png)
![icons-shuffle-sprite](https://cloud.githubusercontent.com/assets/6540217/17783128/7e2982e4-652b-11e6-8f8a-a8790074cd4d.png)

**Comment by kvangent** [comment]
@rrbailey89 Part of the problem is that these are sprite-maps, where as we need individual icons for slack. If you can find a nice set of higher res icons (I think they have to be .png too, but I can't remember right now) I'll be glad to switch them out.

**Comment by rrbailey89** [comment]
@kvangent Maybe this will help :) let me know. 

[Large Icons](https://drive.google.com/open?id=0B9v70D_-W9usYWZHVmVURWJvdjg) 

[Shuffle Icons](https://drive.google.com/open?id=0B9v70D_-W9usVGZuU3ZBbUhOVGc)

**Comment by theresthatguy** [comment]
Attached zip are pokemon PNG files with size of 128x128 px. I got them as emojis for slack group.

[pokepng.zip](https://github.com/kvangent/PokeAlarm/files/426432/pokepng.zip)

**Comment by kvangent** [comment]
Updated as of commit  bee10541fe69cf77e094d60c6539c5806c6f32ed.
