### ISSUE TITLE
Map screenshot not ALWAYS appearing [slack]

### ISSUE THREAD

**Issue by thatsweater** [kvangent/PokeAlarm#132]
## Problem Description
When using slack, and using the map:"enabled", the small map does not always appear/upload. Console shows no extra output, map runs fine, all pokemon of this type are enabled, but the map does not ALWAYS go, infact i would say it is about 1 in 10. This is true for both pokemon/alarms that frequently alarm pokemon, and for alarms that do not alarm pokemon very often (<1 minute in between alarm)

## Your Environment
Operating System:  Ubuntu 16.04
Python Version: python -V  
PokemonGo-Map startup command: General startup command with -wh http://127.0.0.1:4000  (other alarms are working)
PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?: yes

## Console Output
Unfortunately there isn't one.

## Your Alarms Config
{
    		"active": "True",
    		"type":"slack",
    		"api_key":"APIKEY",
			"channel":"#test",
    			"map": 
					{ 
        			"enabled":"true",
        			"width": "250",
        			"height": "125",
        			"maptype": "roadmap",
        			"zoom": "14"
    				},
			}

## Troubleshooting Checklist
[ x] Most recent version of PokemonGo-Map
[ x] Most recent version of PokeAlarm
[ x] Checked the Wiki page for service in question

**Comment by reme-dy** [comment]
@kvangent is working on this.  We'll have to add a Google Maps Static Map API to the code so that we can call down the map image.

More about Google Static Maps [here](https://developers.google.com/maps/documentation/static-maps/intro).

If you want to get a head start, head over to the developer console on your google account and enable the API for Static Maps.

**Comment by thatsweater** [comment]
Thank you so much for the swift reply. Excited to have this feature enabled. Thank you so much!

**Comment by kvangent** [comment]
I'm going to leave this open until I get this problem solved.

**Comment by mgoodsell91** [comment]
I just downloaded the latest version and there is no reference to the map in my config file. Is this something I have to add manually?

**Comment by thatsweater** [comment]
Check the wiki under Slack setup.

**Comment by rrbailey89** [comment]
I dont know about others but im getting a map with each notification now.

**Comment by thatsweater** [comment]
> I dont know about others but im getting a map with each notification now.
I re-downloaded and tested, not all working but more seem to.

**Comment by paulharman** [comment]
yeah seems to be working for me too

**Comment by paulharman** [comment]
scrap that, broken again

**Comment by kvangent** [comment]
Yeah, it's based on rate limiting from google. Once I incorporate the google maps key, it will be limited by a personal goal instead of one key for a large chunk of slack.

**Comment by rrbailey89** [comment]
@kvangent your not going to allow us to use our own api key?

**Comment by brettgus** [comment]
@rrbailey89 That's what he was saying.  Once he adds the ability to add your own google maps key

**Comment by pozimonte** [comment]
For anyone wanting a quick fix before kvangent gets an official one out, you can edit your setup_map function in slack_alarm.py to look as below. Make sure to enable Static Maps API in your Google API Manager console and replace YOUR_API_KEY with your actual key.

(added gkey and query_key to hold your Google API key, then added the key to the url in self.map)

```
	#Set stack map attributes
	def setup_map(self, settings):
		if parse_boolean(settings.get('enabled', "True")) is False:
			self.map = None
			return
		width = settings.get('width', '250')
		height = settings.get('height', '125')
		maptype = settings.get('maptype', 'roadmap')
		zoom = settings.get('zoom', '15')
		gkey = settings.get('key', 'YOUR_API_KEY')
	
		center = '<CENTER>'
		query_center = 'center={}'.format(center)
		query_markers =  'markers=color:red%7C{}'.format(center)
		query_size = 'size={}x{}'.format(width, height)
		query_zoom = 'zoom={}'.format(zoom)
		query_maptype = 'maptype={}'.format(maptype)
		query_key = 'key={}'.format(gkey)
		
		self.map = ('https://maps.googleapis.com/maps/api/staticmap?' +
					query_center + '&' + query_markers + '&' +
					query_maptype + '&' + query_size + '&' + query_zoom +
					'&' + query_key)
```

**Comment by HusbandoMax** [comment]
@pozimonte putting that code in replace of the original i just giving me console errors

**Comment by rrbailey89** [comment]
@pozimonte so you wouldnt add `gkey` to alarms.json you would just insert it there?

**Comment by pozimonte** [comment]
Nope, nothing added in alarms.json. Those three lines were the only ones added or changed in the entirety of PokeAlarm. What program did you use to edit the file, Notepad++? It may be an indention error from copy/paste. You could try simply adding the API key to the URL and delete the gkey and query_key lines, that'll have the same effect.

```
self.map = ('https://maps.googleapis.com/maps/api/staticmap?' +
                    query_center + '&' + query_markers + '&' +
                    query_maptype + '&' + query_size + '&' + query_zoom +
                    '&key=YOUR_API_KEY')
```

**Comment by rrbailey89** [comment]
I figured it out. @pozimonte it was an indentation error haha. I got it fixed thanks :+1:

**Comment by kvangent** [comment]
As of the last commit, you can now specify your own google API key.
