### ISSUE TITLE
Push-Notification like Prowl and NotifyMyAndroid?

### ISSUE THREAD

**Issue by elvquant** [kvangent/PokeAlarm#133]
Have made a directly integration: https://github.com/PokemonGoMap/PokemonGo-Map/issues/836

**Comment by elvquant** [comment]
Prowl-Api https://www.prowlapp.com/api.php
NmA-Api http://www.notifymyandroid.com/api.jsp

**Comment by elvquant** [comment]
No interest for PokeAlert?

**Comment by kvangent** [comment]
You didn't follow the issue template.

**Comment by elvquant** [comment]
Ok!
