### ISSUE TITLE
[ENHANCEMENT] Choose Pokemon to notify by rarity

### ISSUE THREAD

**Issue by DreamingEmma** [kvangent/PokeAlarm#137]
## Enhancement Description

PokemonGo-Map's notification feature includes rarity lists (Common, Uncommon, Rare, Super Rare, Ultra Rare) and the ability to notify based on them. PokeAlarm should allow for notifications by rarity, possibly using a command line argument that modifies the pokemon list in alarms.json accordingly. (This method would still a user to modify her notification preferences on a more granular level, to match her local spawn patterns.)
## Use cases

While the rarity lists may not be accurate for every location since Pokemon distribution is variable, they are a good baseline and would allow quicker setup than manually enabling every Pokemon to notify. It would also allow users familiar with PokemonGo-Map to set up PokeAlarm with familiar settings.

**Comment by reme-dy** [comment]
Hi @DreamingEmma,

We're recently received a similar request.  Please see [#125](https://github.com/kvangent/PokeAlarm/issues/125).

> The problem with this is rarity is very situational and varies person to person. The current structure, while perhaps a tad bit more work, is much more clear.

The current `alarm.json` allows for very fine tuning of notifications.  Kabutos and omanytes are very rare in NYC but a dime a dozen on cali beaches. :)  Perhaps we can add quickstart `alarm.json` files to the wiki based on perceived rarity (things like dragonites, snorlax, and lapras are always uber/ultra rare) then users can just pull down the example and use it straight out of the box after adding their respective service's API keys.

Going to close this ticket but thanks for the idea!  Feel free to contribute additional ideas to the project.
