### ISSUE TITLE
[BUG] All notifications have less than 3 minutes left when using telegram or twitter services

### ISSUE THREAD

**Issue by KongGal** [kvangent/PokeAlarm#141]
## Problem Description
When posting to telegram or twitter it does it so late there is only 2-3 min left on pokemons some times even down to 1 min.

## Your Environment
Operating System:  Debian 8
Python Version: Python 27  
PokemonGo-Map startup command: `-l "xx.152592, xx.199914" -H 0.0.0.0 -P 4582 -ss mrmime.json -wh http://xx.xx.xx.xx:6001`  
PokeAlarm startup command: `--location "xx.152592, xx.199914" -H 0.0.0.0 -P 6001`

## Your Alarms Config

```
{
        "alarms":[
                {
                        "active": "True",
                        "type": "twitter",
                        "access_token": ",
                        "access_secret": "",
                        "consumer_key": "",
                        "consumer_secret": ""
        }
        ],
```
## Troubleshooting Checklist
[ x] Most recent version of PokemonGo-Map
[ x] Most recent version of PokeAlarm
[x ] Checked the Wiki page for service in question

**Comment by reme-dy** [comment]
Do you have the same issues when using Pushbullet or Slack?

What -st and -sd are you using for PokemonGo-Map? Do you see the Pokemon appearing much faster on the PokemonGo-Map live map  (13> minutes)?

**Comment by KongGal** [comment]
Dooh forgot about the title
I'm using  spawnpoint scan with 6 accounts that covers around 300 spawn points so the bottleneck shouldn't be there
I have tried with -sd 6 and -sd 15 same result on both
on the map they show up with 10-13 min left on
I don't have the options to test with pushbullet or slack

the twitter feed in question where it can be seen is @ https://twitter.com/PokeAarhus

**Comment by reme-dy** [comment]
Have you tried changing your -wh to 127.0.0.1?

**Comment by KongGal** [comment]
I have the alarm offsite compared to the map running it but yes i have -wh to the IP running the alarm from the machine running the map with correct port too.

**Comment by kvangent** [comment]
Are you using multiple instances of PokemonGo-Alarm? Do they all have the webhook specified? 

Do you receive in tweets of other pokemon in between the map finding the pokemon and the alert going off?

**Comment by KongGal** [comment]
I am only running 1 Alarm with the WH specified
and i don't get other tweets in betweeen. just take the lastest been on the map for 11 min and the alarm just tweetet it with 1 min left on it :/

**Comment by kvangent** [comment]
Sorry, I meant to say are you running multiple maps? 

So the issue you are experiencing is that the tweets are taking a while to show. For example, a tweet gets posted and says it had 10 minutes left, but really it's only 1-2 minutes?

Are you getting any messages in the console?

**Comment by KongGal** [comment]
i am running 2 maps 1 with 2 workers and the one with the WH with 7 workers
both running on my local machine and using the remote host as database + alarm
the remote host is hosting 2 web server only for the 2 maps and alarm

the issue is the alarm doesn't get info on enabled pokemons until like 5-10 min after scanned :/

**Comment by kvangent** [comment]
Is the time remaining on the tweets accurate? or is it not?

**Comment by KongGal** [comment]
Available until 21:26:56 is correct
(20m 14s). Isn't

**Comment by brettgus** [comment]
Have you tried running the PokeAlarm on the same host that the PokemonGo-Map is running on?

**Comment by kvangent** [comment]
If you could run the Alarm in debug mode, it will show you when it is handling each request. This may help us determin if it is either a processing issue or a connection issue. 

So when you see a pokemon's tweet be late, Look in the console and see if you can find where the alarm processed it.

**Comment by KongGal** [comment]
Best way to use debug mode? console is spammed with pokestop notifications not yet implimented and no logging to file :/

**Comment by kvangent** [comment]
You can always redirct to a file by piping it into a file. `runwebhook.py >> log.txt`

**Comment by KongGal** [comment]
I tried
> log.txt
>> log.txt
| tee log.txt

But none of it get saved :/

**Comment by kvangent** [comment]
Try using two `>>`

**Comment by KongGal** [comment]
Already tried with 2 >>

**Comment by kvangent** [comment]
try  `> log.txt 2>&1`

**Comment by KongGal** [comment]
didn't work either but i just disabled pokestops and gyms from the map and that did it :)

**Comment by KongGal** [comment]
it stopped the pokestop spam with debug, not sure with time. it seems like it post anywhere from 1-3 min to 10 min when SS scanning with 7 accounts which seems a bit weird

**Comment by kvangent** [comment]
You can also try `--webhook-updates-only` to PokemonGo-Map.

**Comment by KongGal** [comment]
--webhook-updates-only seems to do the trick!

**Comment by KongGal** [comment]
Fast question anyway to disable the pokealert start tweet?
