### ISSUE TITLE
[ENHANCEMENT] Gym Alerts

### ISSUE THREAD

**Issue by jane0815** [kvangent/PokeAlarm#143]
## Enhancement Description

Add Option for gym Alerts

## Use cases

Receive an alert when a gym changes team. For example to keep your home or couch gym in your color.

**Comment by kvangent** [comment]
The reason we don't have this feature yet is because PokemonGoMap doesn't send webhooks on gyms at this moment. If they don't add it soon, I'll work on submitting a PR request to them.

**Comment by jnovack** [comment]
PR#666 does.  Plan for it to be merged.

**Comment by kvangent** [comment]
@jnovack The same is true for both Pokemon and Pokestops.

**Comment by brettgus** [comment]
Looks like the relevant PR has been merged to the develop branch in PokemonGo-map https://github.com/PokemonGoMap/PokemonGo-Map/pull/666#event-768306639

**Comment by kvangent** [comment]
This is now completed as of commit 9b5368a166bad41c7b0d3a81c5e14f98579d5bb4. If anyone has problems, please open additional issues.
