### ISSUE TITLE
[BUG] 5..png Needs to be named 53.png for Persian 

### ISSUE THREAD

**Issue by Malouff** [kvangent/PokeAlarm#146]
## Problem Description
Using Slack alarm Number 53 Persian does not have a  bot icon as you have it named 5..png you need to rename that image. 

## Console Output
Sorry,  I didn't looked if there was an error here. 

## Your Alarms Config
I  don't think it's needed in this case. 

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
@Malouff Thanks for catching this. Should be fixed now.
