### ISSUE TITLE
[Enhancement] Front End API Megathread

### ISSUE THREAD

**Issue by kvangent** [kvangent/PokeAlarm#148]
I plan on adding the ability to update the config while running through a restful API and eventually adding a front end API to make these changes easier. There are a few issues open with questions about this, so I wanted to consolidate them here.

This is fairly low on my priority list, and with the exception of changing location may take a while to happen. I'd prefer to focus on functionality and including a wide variety of services for now.

**Phase 1:** 
Introduce RESTful API to Update configuration while the alarm is already running

**Phase 2:** 
Introduce a front end API to make changes to the configuration easier. (If anyone has any front end experience, please feel free to contact me. PR's are always welcome.) 

**Phase 3:** 
Allow services to configure alarm with chat commands. Specifically Telegram and Slack.

**Comment by kvangent** [comment]
As of commit 564599d8aa8311e738125c11a8f0ea8f75b22634, you can now get and update location.

A get request to `/location/` will return the currently set location and status 200.

A post request `/location/location=<name or lat,lng>` will return the updated location and status 200.

**Comment by neutron666** [comment]
Enhancements to the way the config is edited would be very nice. I find it very time consuming to edit the alarms.json file, specifically the pokemon section, which also isn't translated and i have to look into the german translation for every single Pokemon.

**Comment by kvangent** [comment]
@neutron666 there are translated alarms.json.defaults in the defaults folder. 

I would live to get some kind of front end implemented, but I am just one person and there are still performance issues that need to be sorted.

**Comment by neutron666** [comment]
Oh well, i see :) I would help, if i could. Some kind of offline or online editor to write the alarms.json config would be enough, but i understand your problem. The translated alarms.json can just be used as the normal default english one ?

**Comment by kvangent** [comment]
@neutron666 Yes. In fact, PokeAlarm shouldn't care which language you enter in the pokemon's names in, as it converts them to ID numbers. You can fill out the english alarms.json and still get german pokemon names with the locales set correctly.
