### ISSUE TITLE
[Enhancement] Pushing to channels.

### ISSUE THREAD

**Issue by Plop** [kvangent/PokeAlarm#15]
Hi,

Could it be possible to push to a channel, instead of my devices ?

I tried to add this to alarms/pushbullet_alarm.py : 

```
def __init__
[...]
my_channel = self.client.channels[0]
push = my_channel.push_note("Hello World !", "Hello World")
[...]

def pokemon_alert
[...]
push = my_channel.push_link(notification_text, gmaps_link, body=time_text)
[...]
```

But it seems that, even if I receive the first push (Hello World) in the channel, nothing else is working anymore. Nothing is displayed in my console when running PokemonGo-Map, like 
`				log.info(name + " notification was not triggered because time_left had passed.")
`

I can't find what I broke. Is anyone able to help ? :)

Thanks.

**Comment by hhu94** [comment]
You need to make `my_channel` part of the object my changing `my_channel = self.client.channels[0]` to `self.channel = self.client.channels[0]`.

Then instead of `push = my_channel.push_link(notification_text, gmaps_link, body=time_text)`, do `push = self.channel.push_link(notification_text, gmaps_link, body=time_text)`

**Comment by kvangent** [comment]
@Plop It's definitely doable to add channels in, and I had plans to make it a permanent feature. However since Pushbullet is changing their api to paid only (and I'm too cheap to buy premium), I won't be able to continue to test and support it.

**Comment by Plop** [comment]
@kvangent I don't know if you know this, but apparently, there is a [500 requests/month](http://www.androidpolice.com/2016/07/27/pushbullet-will-limit-api-based-pushes-500-per-month-free-accounts-starting-august-1/) for the free plan. Maybe it will be enough for your tests ?

**Comment by kvangent** [comment]
@Plop I may keep updating it occasionally, but it will be a 2nd priority. The problem is that if a problem arises and I'm out of requests, it'll become very difficult for me to troubleshoot a solution.

**Comment by Plop** [comment]
No problem, I understand :) You were saying that the API was paid only, so I thought you maybe didn't know it. :)
