### ISSUE TITLE
Trouble Running Multiple Webhooks

### ISSUE THREAD

**Issue by TackyBrad** [kvangent/PokeAlarm#152]
## Problem Description

I am attempting to run multiple alarms. I admit to having no expertise. Basically, I am trying to have two twitter outputs, one to TWITTER1 that is for my personal notifications, things that I am missing. The other TWITTER2, I want to send out many more notifications for the whole community. For example, for my personal alarm, I would not want to be notified of a Ninetales, but the community would. Thus, I want it to be false for TWITTER1 but true for TWITTER2. I tried to do this by running two webhooks from my PokemonGo-Map config.ini, one for 127.0.0.1 and one for 127.0.0.2. I did this and ran two different cmd prompts from different folders containing the different alarms.json (copied folder, made one "personal" one "general," ran one from each folder). The one set to listen to port 4000 and wh 127.0.0.1 worked flawlessly, the second one, set to listen to port 4001 and wh 127.0.0.2 initialized correctly, even tweeting the initialization post, but never received information from the map. I also tried taking the webhooks out of config and running them in the cmd line (-wh http://127.0.0.1 -wh http://127.0.0.2). I have not yet been able to figure out to get it working.

## Your Environment

Operating System:  Windows 10
Python Version:   2.7.12
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>` python runwebhook.py ||| python runwebhook.py -H 127.0.0.2 -P 4001

Did the issue persist after restarting the script?: yes

## Console Output

This is what happened when I ran both alarms on the same address and port. **Please note, I did not expect this to work,** but it is the only potentially relevant command line material I had. Please do not get caught up on thinking my issue is running this on the same address/port. I tried it just in case. Thanks!

```
	<2016-08-24 01:46:16,480 [     alarm_manager] [   INFO] Alarm not activated: pushbullet because value not set to "True"
2016-08-24 01:46:16,483 [     alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-08-24 01:46:16,486 [     alarm_manager] [   INFO] Alarm not activated: pushover because value not set to "True"
2016-08-24 01:46:16,546 [     twitter_alarm] [   INFO] Twitter Alarm intialized.
2016-08-24 01:46:17,196 [     alarm_manager] [   INFO] PokeAlarm has started! Your alarms should trigger now.
2016-08-24 01:46:17,197 [        runwebhook] [   INFO] Webhook server running on http://127.0.0.1:4000
Traceback (most recent call last):
  File "runwebhook.py", line 60, in <module>
    server.serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 347, in serve_forever
    self.start()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 291, in start
    self.init_socket()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 1222, in init_socket
    StreamServer.init_socket(self)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 80, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 91, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 177, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('127.0.0.1', 4000)
Exception gevent.hub.LoopExit: LoopExit('This operation would block forever', <Hub at 0x3ce9080 select default pending=0 ref=0 resolver=<gevent.resolver_thread.Resolver at 0x4c489f0 pool=<ThreadPool at 0x4c48d30 0/1/10>> threadpool=<ThreadPool at 0x4c48d30 0/1/10>>) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

C:\Users\Mark\Documents\PogoMapStuff\PokemonGo-Map1\PokeAlarm - Personal>
>
```

## Your Alarms Config

```json
    <{
	"alarms":[
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#general"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
            "active": "True",
            "type": "twitter",
            "access_token": "",
            "access_secret": "",
            "consumer_key": "",
            "consumer_secret": ""
        }
		
	],
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"True",
		"Charmander":"False",
		"Charmeleon":"True",
		"Charizard":"True",
		"Squirtle":"False",
		"Wartortle":"True",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"True",
		"Sandshrew":"False",
		"Sandslash":"True",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"True",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"True",
		"Clefairy":"False",
		"Clefable":"True",
		"Vulpix":"False",
		"Ninetales":"True",
		"Jigglypuff":"False",
		"Wigglytuff":"True",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"True",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"True",
		"Meowth":"False",
		"Persian":"True",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"True",
		"Growlithe":"False",
		"Arcanine":"True",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"True",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"True",
		"Machop":"False",
		"Machoke":"True",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"True",
		"Tentacool":"False",
		"Tentacruel":"True",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"True",
		"Ponyta":"False",
		"Rapidash":"True",
		"Slowpoke":"False",
		"Slowbro":"True",
		"Magnemite":"False",
		"Magneton":"True",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"True",
		"Seel":"False",
		"Dewgong":"True",
		"Grimer":"False",
		"Muk":"True",
		"Shellder":"False",
		"Cloyster":"True",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"True",
		"Onix":"True",
		"Drowzee":"False",
		"Hypno":"True",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"True",
		"Exeggcute":"False",
		"Exeggutor":"True",
		"Cubone":"False",
		"Marowak":"True",
		"Hitmonlee":"True",
		"Hitmonchan":"True",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"True",
		"Rhyhorn":"False",
		"Rhydon":"True",
		"Chansey":"True",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"True",
		"Goldeen":"False",
		"Seaking":"True",
		"Staryu":"False",
		"Starmie":"True",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"True",
		"Electabuzz":"True",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"True",
		"Eevee":"False",
		"Vaporeon":"True",
		"Jolteon":"True",
		"Flareon":"True",
		"Porygon":"True",
		"Omanyte":"False",
		"Omastar":"True",
		"Kabuto":"False",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"True",
		"Zapdos":"True",
		"Moltres":"True",
		"Dratini":"False",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"True"
	}
}
>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

Map is ~2 day old version, same for alarm. I hope I didn't miss it in the Wiki. No problems running two accounts, just an issue trying to run two accounts from two different alarm lists.

**Comment by brettgus** [comment]
So, the problem with what you're trying to do is that PokemonGo-Map only (as far as I know) supports sending one webhook per process.  You are trying to have it send two webhooks.

You could handle this by starting different PokemonGo-Map processes with different webhooks, but it doesn't sound like that's what you're trying to do.

What I've done for my personal setup is have a separate php script that accepts the webhook, and then that in turns calls out to multiple different webhooks.  A "webhook splitter" is probably the best name for it.  It isn't the most elegant solution, but it's worked for me as temporary one.

Ideally, PokeAlarm would be able to handle multiple alarms configurations natively... but if that feature is added it wouldn't probably won't be for quite a while because it would require quite the revamp of the code.

**Comment by TackyBrad** [comment]
Thanks for adding the labels and giving it the proper title. You are correct in your assessment. I cannot code and can only use limited intelligence in doing assorted things without breaking stuff. Is what you have implemented something I could implement?

My aim is to help the community, but I do not want as many notifications personally as they want. So, yes, I would need a way split the webhook so it goes to both. Who knows, maybe someone has an easily implementable solution.

Cheers,

Brad

**Comment by kvangent** [comment]
PokemonGo-Map allows multiple webhooks. It used to be the format `-wh <WEBHOOK1> -wh <WEBHOOK2>`, but someone on reddit was having trouble with this, so they may have changed it to `-wh <WEBHOOK1> <WEBHOOK2>`. If you prefer to modify it in config.ini, it might be `[<WEBHOOK1>,<WEBHOOK2>].

**Comment by brettgus** [comment]
@kvangent So it does!  Glad to know this

**Comment by brettgus** [comment]
And yeah, @TackyBrad it looks like [the current format](https://github.com/PokemonGoMap/PokemonGo-Map/wiki/Command-Line-Arguments)  for the command line is `-wh <webhook1> <webhhook2>` as @kvangent was saying.

**Comment by TackyBrad** [comment]
Thank you for the replies. One last question, will I need to run the Webhooks as 

-wh 127.0.0.1:4000 127.0.0.2:4001 

For it to work? I need to add the port as well, correct? Thank you again.

**Comment by kvangent** [comment]
`-wh http://127.0.0.1:4000 http://127.0.0.1:4001` - The IP will stay the same, but the port should be different.

**Comment by TackyBrad** [comment]
Thanks a lot. Two webhooks are now running. I wanted to do a third for another subset of the community, so my cmd line reads:

python runserver.py -l -k -u -p.. etc -wh http:127.0.0.1:4000 http://127.0.0.1:4001 http://127.0.0.1:4002

I get no error messages on the map workers nor the alarm cmd. (alarm command is python runwebhook.py -P 4002), it simply just doesn't populate the alarm. Thoughts? Quit while I'm ahead?

**Comment by brettgus** [comment]
I take it that's not the exact command line you're using?  You're missing some slashes in the first webhook.

**Comment by kvangent** [comment]
@TackyBrad If you could, post all 3 commands and at least the first few lines for the alarms.

**Comment by TackyBrad** [comment]
User error. There was an errant space I noticed once I turned on paragraph markings in word. Thanks again, sorry to bother with a n00b mistake!

**Comment by kvangent** [comment]
Glad you got it figured out!
