### ISSUE TITLE
[Bug]Slack address notification return None None.

### ISSUE THREAD

**Issue by jtmantis** [kvangent/PokeAlarm#158]
## Problem Description
The address notifications on Slack sometimes are shown as None None. Sometimes it stays like this for a few hours and then brings back to normal. 

Do you think it can be the issue with the slack itself? 

## Your Alarms Config

```
    		{
			"active": "True",
			"type":"slack",
			"api_key":"****",
			"channel":"#kaunas",
			"body":" Bus iki <24h_time>, liko (<time_left>). ",
			"title":" KaipZaisti.lt rado <pkmn>! adresu: <addr>. ",
			"url":"<gmaps>"
		},
```
## A screenshot from Slack

https://i.gyazo.com/4dedf7fcb0f30500ae45502f30eeea57.png

Operating System:  Linux ubuntu
Python Version: 2.7.6
PokemonGo-Map startup command: python runserver.py
PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?:  Yes

## Console Output
Everything seems pretty normal, except this one error. But even with that error the address was shown all the time.

```
	016-08-25 23:21:20,716 [     alarm_manager] [   INFO] Bellsprout ignored: notify not enabled.
2016-08-25 23:21:20,721 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:22,589 [     alarm_manager] [   INFO] Drowzee ignored: notify not enabled.
2016-08-25 23:21:22,613 [     alarm_manager] [   INFO] Caterpie ignored: notify not enabled.
2016-08-25 23:21:23,483 [     alarm_manager] [   INFO] Rattata ignored: notify not enabled.
2016-08-25 23:21:23,495 [     alarm_manager] [   INFO] Koffing ignored: notify not enabled.
2016-08-25 23:21:24,658 [     alarm_manager] [   INFO] Drowzee ignored: notify not enabled.
2016-08-25 23:21:24,664 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:24,736 [     alarm_manager] [   INFO] Pidgey ignored: notify not enabled.
2016-08-25 23:21:26,729 [     alarm_manager] [   INFO] Machop notication was triggered!
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
2016-08-25 23:21:27,610 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:27,610 [     alarm_manager] [   INFO] Haunter ignored: notify not enabled.
2016-08-25 23:21:27,611 [     alarm_manager] [   INFO] Zubat ignored: notify not enabled.
2016-08-25 23:21:27,611 [     alarm_manager] [   INFO] Venonat ignored: notify not enabled.
2016-08-25 23:21:28,997 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:30,753 [     alarm_manager] [   INFO] Nidoran♀ ignored: notify not enabled.
2016-08-25 23:21:31,811 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:32,837 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-25 23:21:32,857 [     alarm_manager] [   INFO] Clefairy ignored: notify not enabled.

```

**Comment by kvangent** [comment]
It's possible that these locations don't have a suitable address - and so google is coming up empty.

**Comment by jtmantis** [comment]
If I click the link on Slack it shows me the locations in the map, and that location do have address. Plus those are the same locations that were shown just a few hours ago, and sudenly every single address turned to None None. The same thing happened this morning but then it came back to normal without doing anything. 

By the way I'm scanning from -ss .json so those are definatelly the same spawnpoints that had the address just a few hours ago.

**Comment by kvangent** [comment]
So it's all addresses are coming up with None for a few hours at a time? Have you checked Google Dev Console to see if it you are hitting your limit? 

If not please fill out the rest of the issue template so I can get a better idea of whats happening.

**Comment by brettgus** [comment]
@jtmantis Yeah, I agree with @kvangent, it looks like you have your alarms have a very high frequency (1-5 per min).  Every time an alarm goes off, there may be multiple requests to google's maps API.  Google limits you to 2500 requests a day, you might be hitting that.

**Comment by jtmantis** [comment]
I get maximum 500 requests a day. I've just updated the issue template, not sure if it helps.

**Comment by jtmantis** [comment]
One more thing: I have Alarms set for two cities. They use different API, but the address turn to None None on both almost the same time.

**Comment by kvangent** [comment]
Can you double check your console API limit and see what it says you are at and what you are at yesterday?

**Comment by jtmantis** [comment]
Well I don't know if I'm looking at the right place, but here are the screenshots from my dashboard.

https://i.gyazo.com/8545aeb69646299a351847f494723c9c.png

https://i.gyazo.com/a05805c587d18bc4f8df6ba4e10fab15.png

If this is the right place that means I just hit 600 request out of 25000 today. Although I'm not sure about 100 requests per 100 seconds limit. Maybe I could hit the limit on that one?

**Comment by kvangent** [comment]
@jtmantis Are you sure that is the key you are giving to the Alarm? You should see something along the lines of Google Maps Geocoding API, which I dont see on there. For example, mine looks like this: 
![image](https://cloud.githubusercontent.com/assets/10712294/17985186/4c3aaa56-6ada-11e6-872f-d4ee82a99f5e.png)

**Comment by jtmantis** [comment]
@kvangent yes I've dubled checked, it's the same API that is used in config.ini So maybe because I don't have Geocoding API enabled is the reason I stopped seeing the address?

**Comment by kvangent** [comment]
It could be. It is weird that it works sometimes but not all. I would check the output from your Alarms console to make sure you aren't getting an error at the start. But if you enable it, let me know if it solves your problem.

**Comment by jtmantis** [comment]
Unfortunatelly that didn't help. But even before I anabled it, there was a couple notifications that showed the address: https://i.gyazo.com/c4743dab69e35b1a2f4a2bdfa2e35549.png

I'm also checking my API requests for the whole day: https://i.gyazo.com/fb04270410ea634c81fe8972e1316fbd.png 

So it seems like it went up in the last few hours but it's still under the limit. 

But disabling notifications in alarms.json on some pokemons wouldn't reduse the API requsts right?

**Comment by kvangent** [comment]
Yes, less pokemon would make less requests per pokemon. My guess is that something funky is going on with your API key, but I'm not positive. It seems weird that it was letting your get requests without being enabled.

**Comment by brettgus** [comment]
@jtmantis Can you paste the google maps link for one of the ones that shows up "None None".

**Comment by jtmantis** [comment]
@brettgus sure, here is a link: https://www.google.com/maps?q=54.72185698782487,25.286420060321564

@kvangent but according to Wiki Javascrip API and API Web Service are the only ones that needs to be enabled: https://pgm.readthedocs.io/en/develop/basic-install/google-maps.html It doesn't say anything about Geocoding API, so I would assume that is what most people are using and are fine?

**Comment by jtmantis** [comment]
Interesting... it came back to normal exactly the same time when it came back yasterday. 

One more thing: I have two saparate Pogo-Map and PokeAlarm clones, 1 for each city tracking and notifications. And I also use two different Google Maps keys with in config.ini But those addresses brake on both servers exactly the same time and comes back to normal at the same time, even though their API keys and even alarms.json settings are different. One has more Pokemon alerts than another. 

Maybe I should try to check with PushBullet once (if) it brakes today?

**Comment by brettgus** [comment]
Just looking over this issue again and I realized that you're not specifying the google maps key at the command line, is that right?

**Comment by jtmantis** [comment]
@brettgus thanks for taking your time to have a look at this issue again. Do you mean the command line in PokeAlarm directory? Suck as:

```
    	python runwebhook.py -k asdjasdkasda666 
```
Or the one in pogomap folder?

**Comment by brettgus** [comment]
@jtmantis Yes, the command for PokeAlarm.  In the issue description template, you said this is your startup command.  `PokeAlarm startup command: python runwebhook.py`  Is that correct?

**Comment by kvangent** [comment]
@jtmantis He is refering to the command line in for PokeAlarm. I'm assuming you are and just didn't put it, because otherwise your geocoding wouldn't work at all. 

You said you are using multiple keys. Are you sure that you have enabled Geo-coding for both keys? And that you are using the most up to date copy of PokeAlarm?

The fact that they comes back at the same time really makes me think you are hitting the limit.

**Comment by jtmantis** [comment]
Yes that's correct, I haven't used API Key in the command line, forgive me for my stupidity. I don't know how come I haven't thought of that. ```python runwebhook.py``` is the only thing I inserted in the command line. I only have my API Keys set in Pogomap config.ini file, so I'm not sure where PokeAlarm is taking that API Key from.

**Comment by kvangent** [comment]
@jtmantis Are you sure you are using the most recent version?

**Comment by kvangent** [comment]
@jtmantis Right. The more recent update allows you to specify your own key.

**Comment by brettgus** [comment]
@jtmantis Yeah if we're troubleshooting an issue for you you should really be on the latest commit as we may have already resolved an issue that you're trying to have addressed.

But yeah, it looks like the issue you're having is as we first suspected, API key related.  If an API key isn't specified, google falls back on limiting your IP address.  From seeing your alerts, I'm 99% sure you're going over your limit.  Pretty sure that's why @kvangent closed out this issue.

To fix this issue going forward:
- Update all of your instances of PokeAlarms running on your computer to the latest version
- Make sure your Google Maps API key is setup correctly
- Use your API key with all of your running PokeAlarms on your computer
- Monitor your API usage.  You will see that you're hitting your 2500/day limit
- Reduce the number of alarms so that you are below the 2500/day limit

**Comment by jtmantis** [comment]
Thank you guys for all the response and support. I've updated the to the last git, but looks like <addr> is not supported anymore. Have you removed it? Here is how my line in alarms.json looks like:
```
"body":" Bus iki <24h_time>, liko (<time_left>). ",
"title":" KaipZaisti.lt rado <pkmn>! adresu: <addr>. "
```
And the result: 
https://i.gyazo.com/2cc18b747ff775bdfaf1387d981fa187.png

vs before: https://i.gyazo.com/bcd7ba2fea0f5a70e4a69011d53bd52d.png

**Comment by kvangent** [comment]
Use `<address>`.

**Comment by jtmantis** [comment]
Now I get an error:
```
Traceback (most recent call last):
  File "runwebhook.py", line 78, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/root/Vilnius/PokeAlarm/alarms/alarm_manager.py", line 24, in __init__
    settings = json.load(file)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 16 column 13 (char 387)
```
I've used exactly the same lines as in your wiki just replaced <addr> with <address>
```
		{
			"active": "True",
			"type":"slack",
			"api_key":"xxx",
			"channel":"#test"
            "title":"<pkmn> (#<id>) at <address> <postal>",
            "url":"<gmaps>",
            "body":"(<dist> <dir>) until <24h_time> (<time_left> remaining)!"
		},
```

**Comment by nhumber** [comment]
just got this up and going, nice work, same <address> error here for me when specifying -k .

debug shows nothing out of the ordinary on console.

**Comment by simisbeat** [comment]
have anyone fixed <address> ??
