### ISSUE TITLE
[ENHANCEMENT] Add ability to configure alarms from Telegram

### ISSUE THREAD

**Issue by phillipah** [kvangent/PokeAlarm#159]
## Your Environment

Operating System:  
Python Version: (use `python -V`)  
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

## Other Links

It would be great to be able to configure or "subscribe" to pokemon from telegram or any other service that has bot features.

**Comment by kvangent** [comment]
See #148.
