### ISSUE TITLE
Outside range Exception!

### ISSUE THREAD

**Issue by Youpit44** [kvangent/PokeAlarm#160]
## Problem Description

After [last commit](https://github.com/kvangent/PokeAlarm/commit/ec495c4322aceb9c84be855aa98a716e50bbbd8e), i get an error when a pokemon appears far from my area. 
## Your Environment

Operating System:  Linux 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python Version: 2.7.12  
PokemonGo-Map startup command: `python runserver.py -ss -l 'xx.xxxxxxxx, -xx.xxxxxxxx' -st 6 -a ptc -u XXXXX -p 'YYYYY' -wh http://127.0.0.1:4000 -j --webhook-updates-only`   
PokeAlarm startup command: `python runwebhook.py -L fr -l 'xx.xxxxxxxx, -xx.xxxxxxxx' -k XYXYXYXYXYXYXYXYxyxyxyxxyxyxyxy`

Did the issue persist after restarting the script?: yes

## Console Output

```
2016-08-26 09:28:26,435 [     alarm_manager] [   INFO] Évoli ignored: outside range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pokemongo/PokeAlarm/alarms/alarm_manager.py", line 73, in run
    self.trigger_pkmn(data['message'])
  File "/opt/pokemongo/PokeAlarm/alarms/alarm_manager.py", line 106, in trigger_pkmn
    log.debug("Pokemon must be less than %f, but was %f." % (self.notify_list[pkmn_id]), dist)
TypeError: not enough arguments for format string
```

## Your Alarms Config

```json
                {
                        "active": "True",
                        "type":"telegram",
                        "bot_token":"XXXXXXXXXYYYYYYYYYYY",
                        "chat_id":"123456789"
                },

                        "Évoli":"150",
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

## Use cases

replace : 
   `log.debug("Pokemon must be less than %f, but was %f." % (self.notify_list[pkmn_id]), dist)`
by
   `log.debug("Pokemon must be less than {0}, but was {1}.".format((self.notify_list[pkmn_id]), dist))`

**Comment by sLoPPydrive** [comment]
Just created PR #161 for the fix. :)

**Comment by kvangent** [comment]
I actually noticed this, but somehow forgot to commit. My apologies.
