### ISSUE TITLE
[ENHANCEMENT] Reduce Telegram to 1 vibrate/notification per pokemon

### ISSUE THREAD

**Issue by drewreece** [kvangent/PokeAlarm#164]
## Problem Description
Telegram alarms sends the map & text as individual messages - this is due to how Telegram handles messages & maps (they are individual items). It causes 2 notifications & 2 vibrations. 

## Your Environment
Operating System:  Raspbian Linux, Raspberry Pi
Python Version: Python 2.7.9
Tested with Telegram on iOS

## Your Alarms Config
Telegram is setup, maps are enabled.

## Enhancement Description
Disable the notification for the map message via the 'locargs'. 
Add this to line 46 on alarms/Telegram/Telegram.py… 
`
locargs = {
                                'chat_id': self.chat_id,
                                'latitude': pkinfo['lat'],
                                'longitude':  pkinfo['lng'],
                                'disable_notification': 'True'
                        }
`

On iOS the text message does still vibrate if that notification is enabled in telegram - this only stops the map notification which is a 'duplicate alert'. The app badges does show 2 missed messages (the map counts as one message despite no audible or visual notification for it).
See the API for more detail, Android handles this differently it gets a notification for both 'parts' of the message but the map should be silent with the above change, iOS gets only the text notification & buzz from the text part. 

This change seems harmless unless the text body can be disabled - Why would you do that? Is that a feature?

## Use cases
It reduces the amount of 'buzz buzz', 'beep beep' or worse 'buzz beep' 'buzz beep' for one Pokémon alarm.

## Other Links
Telegram API https://core.telegram.org/bots/api#sendmessage

**Comment by brettgus** [comment]
Please see this previous issue: https://github.com/kvangent/PokeAlarm/issues/129

**Comment by drewreece** [comment]
I have seen that issue and don't understand what point you are trying to make @brettgus?

This stops the double vibrate or double sounds in Telegramwhich cannot be altered via the issue you mention - Telegram needs to use 2 messages & kvangent seems to think that is the best answer.  I have to agree, the map is interactive in telegram & should not be downgraded to a static image.

**Comment by kvangent** [comment]
@drewreece I get what you are going for. It totally make sense to reduce it to one.

**Comment by kvangent** [comment]
@drewreece Check out commit 64d4f14619c535a8275f6b48b6f12e400d050f79 and see if that is what you are looking for.

**Comment by drewreece** [comment]
Yes that looks correct I'll pull & retest it soon, thanks kvagent.

**Comment by drewreece** [comment]
Actually that needs to be set to 'True' to avoid the double notification. 'False' still buzzes/ sounds twice.

Sorry, I failed to see that you had reversed the setting, it needs changing unless you intended this behaviour.

**Comment by kvangent** [comment]
@drewreece Make sense. My brain didn't realize it was 'disable' for whatever reason. Should be good now.
