### ISSUE TITLE
[Slack] Map is missing complete

### ISSUE THREAD

**Issue by Viper2k4** [kvangent/PokeAlarm#168]
## Problem Description
Slack alarms dont show an map anymore.

## Your Environment
Operating System:  
Python Version: v2.7.9
PokemonGo-Map startup command: `python ./runserver.py .....  -wh http://127.0.0.1:4000 --webhook-updates-only`
PokeAlarm startup command: `python ./runwebhook.py --locale "de" --key "TheKey"`

Did the issue persist after restarting the script?: yes

## Console Output
Nothing to show here. On -d there is only the request to Slack :/

## Your Alarms Config

```json
{
  "alarms": [
    {
      "active": "True",
      "type": "slack",
      "api_key": "xoxp-63787400951-63780781648-69010514004-8183cc8acd",
      "channel": "#pokelarm",
      "title": "Ein wildes <pkmn> ist aufgetaucht!",
      "body": "Verfügbar bis <24h_time> (<time_left>).",
      "startup_message" : "False",
      "map":{
                "enabled":"True",
                "width":"250",
                "height":"125",
                "maptype":"roadmap",
                "zoom":"15"
            } 
    }
  ],
  "pokemon": {
    "Bulbasaur": "True",
    "Ivysaur": "True",
    "Venusaur": "True",
    "Charmander": "True",
    "Charmeleon": "True",
    "Charizard": "True",
    "Squirtle": "False",
```

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by neskk** [comment]
Same here, no error messages appear with -d option enabled, but minimaps fail to be attached/displayed in Slack bot message.

**Comment by kvangent** [comment]
@Viper2k4 @neskk Have you guys enabled the static map API from google dev console?

**Comment by neskk** [comment]
You were right, thanks.

**Comment by Viper2k4** [comment]
Nope. But now it works :)
(would a a sweet wiki point^^)

**Comment by kvangent** [comment]
Yeah, the wiki needs some overhauling. We're working on it.
