### ISSUE TITLE
A misspelled code in Wiki

### ISSUE THREAD

**Issue by jtmantis** [kvangent/PokeAlarm#169]
Hi,

I've noticed a small typo in Wiki: Mini Map code for slack:

```
{
    "active": "True",
    "type":"slack",
    "api_key":"YOUR_API_KEY"
    "map": { 
        "enabled":"true",
        "width":"250",
        "height":"125",
        "maptype":"roadmap",
        "zoom": "15"
    }
},
```
There is comma missing after api key line
```
  "api_key":"YOUR_API_KEY",
```
It's not a big a deal but for someone like me it could hive a headache when you can't understand what is wrong and why it's not working.

**Comment by kvangent** [comment]
We're working on making some major changes to the wiki, including fixing minor mistakes like this.

In the future please use the issue template.
