### ISSUE TITLE
[ENHANCEMENT] Slack - ability to send direct message to user

### ISSUE THREAD

**Issue by JasonSchoon** [kvangent/PokeAlarm#173]
## Enhancement Description
Support posting to username channels on Slack

## Use cases
I would like to just send myself notifications (by sending to my username channel) on Slack. This should already be supported by the Slack API if the channel name given is by ID, and is the ID of the username channel.

The issue is likely due to the fact that these channels do not show up in the channels.List results.

Specifically, it would be cool if a channel name started with "@", to skip the current channels.List validation, and automatically do the lookup described below between users.list and im.list to get the appropriate channel ID automatically.

## Other Links
Slack postMessage documentation showing the support: https://api.slack.com/methods/chat.postMessage

Note it's currently a little cumbersome to get the ID for a user channel. I used the users.List API tester (https://api.slack.com/methods/users.list/test) to get my user ID, and then used im.List tester (https://api.slack.com/methods/im.list/test) to get my user channel ID.

**Comment by kvangent** [comment]
@JasonSchoon I think you said this was solved in discord. If not let me know and I'll reopen.
