### ISSUE TITLE
[USER SPECIFIC] <address> not working correctly for telegram output

### ISSUE THREAD

**Issue by eugenesoo** [kvangent/PokeAlarm#174]
## Problem Description

Utilising `<address>` in the `"title"` or `"body"` under alarms.json prevents telegram bot from sending out a message, with the following error code:

## Your Environment

Operating System:  Debian 7.11 (Wheezy)
Python Version: Python 2.7.12
PokemonGo-Map startup command: `./start.sh` (custom beehive start script)
PokeAlarm startup command: `python runwebhook.py`

Did the issue persist after restarting the script?: Yes

## Console Output

```
2016-08-28 18:25:15,788 [     alarm_manager] [   INFO] Rattata notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 72, in run
    self.trigger_pkmn(data['message'])
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 131, in trigger_pkmn
    pkmn_info.update(**reverse_location(pkmn_info))
  File "/root/PokeAlarm/alarms/utils.py", line 293, in reverse_location
    result = config['GMAPS_CLIENT'].reverse_geocode((lat,lng))[0]
  File "/opt/python/lib/python2.7/site-packages/googlemaps/geocoding.py", line 109, in reverse_geocode
    return client._get("/maps/api/geocode/json", params)["results"]
  File "/opt/python/lib/python2.7/site-packages/googlemaps/client.py", line 222, in _get
    raise googlemaps.exceptions.TransportError(e)
TransportError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

## Your Alarms Config

```json
              {
                        "active": "True",
                        "type":"telegram",
                        "bot_token":"_________",
                        "chat_id":"-_________",
                        "title":"A wild <pkmn> has appeared at <address>!",
                        "body":"It will be here for another <time_left>. Hurry before it is too late!"
                },

```

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
@eugenesoo Can you try the following:

`pip uninstall -y certifi && pip install certifi==2015.04.28` 
from http://stackoverflow.com/questions/35087360/how-to-make-googlemaps-python-library-detect-ssl-certificates.

**Comment by eugenesoo** [comment]
it worked - thank you very much!
