### ISSUE TITLE
[USER ISSUE] Issue with adding options to alarms.json

### ISSUE THREAD

**Issue by mgoodsell91** [kvangent/PokeAlarm#175]
## Problem Description
I run into an error any time I try to add an option to the alarms.json. Specifically disabling the startup message on slack. 

## Your Environment

Operating System:  OSX 10.11
Python Version: 2.7
PokemonGo-Map startup command: python /Users/USER/PokemonGo-Map/runserver.py -os -l 50 50 -H 0.0.0.0 -wh http://127.0.0.1:4000
PokeAlarm startup command: Python runwebhook.py

Did the issue persist after restarting the script?: no

## Console Output
Traceback (most recent call last):
  File "runwebhook.py", line 80, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/Users/USER/Documents/PokemonGoTools/PokeAlarm/alarms/alarm_manager.py", line 23, in __init__
    settings = json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 13 column 4 (char 239)

## Your Alarms Config
{
	"alarms":[
		{
			"active": "True",
			"type":"slack",
			"api_key":"KEY",
			"channel":"#localsearch"
			"startup_message":"true"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "",
			"access_secret": "",
			"consumer_key": "",
			"consumer_secret": ""
        }
Took the pokemon triggers to keep this brief. 
}
Config unchanged

## Troubleshooting Checklist
[ X] Most recent version of PokemonGo-Map
[ X] Most recent version of PokeAlarm
[ X] Checked the Wiki page for service in question

It works fine when I remove the offending line. Also same issue happened when I tried to add maps options.

**Comment by kvangent** [comment]
You are missing a comma on line 12.

 Use http://www.jsoneditoronline.org/ to look for JSON formatting issues.

**Comment by mgoodsell91** [comment]
Thanks for the quick fix, it works. Sorry for the basic questions!
