### ISSUE TITLE
[BUG] Telegram wiki shows "header" but it is "title"

### ISSUE THREAD

**Issue by jtp10181** [kvangent/PokeAlarm#176]
## Problem Description

The Wiki shows the wrong parameter to use for changing the message title
https://github.com/kvangent/PokeAlarm/wiki/Telegram

## Your Alarms Config

This works:
```json
   			"title":"<pkmn> has appeared!",
```

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by jtp10181** [comment]
Sorry did you not want this reported?
I found an issue with the notify sound on telegram on Android also and fixed it. Was going to try and post that also but it takes time to fill in all info for the issue request. Or we can chat on Discord if you want.

**Comment by kvangent** [comment]
@jtp10181 What issue did you find with the notify sound on telegram?

**Comment by jtp10181** [comment]
It is odd, after one of the recent updates I noticed the text on telegram started showing up first then the maps, before maps were on top. I could not find what code change caused this. Then with the most recent fix to only send one notify per alert (by shutting off the notify for the map), it effectively stopped working at all on Android. Was confirmed with two different users with different android phones.

My theory was that since the map was coming second (immediately after the text) and the notify was disabled it was making it not notify at all. I swapped the map and text code in the telegram alarm so it sends the map first (which I like better anyway) and the sounds started working again.

I am on Discord now also 'jtp10181' if you want to ping me on there.

**Comment by kvangent** [comment]
@jtp10181 Can you open an issue ticket for that error? I'll look into it after the pokestops/gyms update is complete

**Comment by kvangent** [comment]
@jtp10181 As of d563056 you can add 'disable_map_notification' to your telegram config. Set it to "False" to get your notifications back.

**Comment by jtp10181** [comment]
Then I will get two notifications for each alert like before, i will just
keep my fix.

**Comment by kvangent** [comment]
@jtp10181 When I tested it this afternoon, I was only getting one buzz on Android. Is this not the case for you?

**Comment by jtp10181** [comment]
I will try it, but I think you get two dings on iPhone like that, possibly
only one on android.
The way I fixed it, it works as desired for both platforms.

**Comment by kvangent** [comment]
@jtp10181 When I played around with it the other day via the desktop client, disabling the notification on the first one would cause it only to show "PokeAlarm has sent a location." rather then the actual text sent. With this solution, android users can specify it to "False" to ensure they get the alarm (because it will show the notification text regardless) and everyone else can let it default to true with no issues.
