### ISSUE TITLE
[ENHANCEMENT] Pushbullet SMS API

### ISSUE THREAD

**Issue by mew905** [kvangent/PokeAlarm#177]
## Enhancement Description
Change or add ability to use Pushbullet's SMS API instead of asking users to install their application.

## Use cases
Streamlining user interface to make it as minimal as possible. I rather not ask users to install anything they're unsure of, less end-user troubleshooting means more development time for me.

## Other Links
https://docs.pushbullet.com/#send-sms

Example API:
{
  "push": {
    "conversation_iden": "+1 303 555 1212",
    "message": "Hello!",
    "package_name": "com.pushbullet.android",
    "source_user_iden": "ujpah72o0",
    "target_device_iden": "ujpah72o0sjAoRtnM0jc",
    "type": "messaging_extension_reply"
  },
  "type": "push"
}

**Comment by brettgus** [comment]
Looks like the pushbullet library PokeAlarm uses supports sending pushbullet SMS

```
Sending SMS messages

device = pb.devices[0]
push = pb.push_sms(device, "+3612345678", "Wowza!")
```

**Comment by kvangent** [comment]
@mew905 It can be the same API, what I meant was it would make more sense to have it as an additional python module rather than incorporate it into the Pushbullet alarm that is already created.

**Comment by mew905** [comment]
oh, , sorry I thought you meant I'd have to write one from scratch so I've been looking through tons of examples to try and figure it out. This looks like I should be able to replace a couple lines in my own copy, but the catch is (from my understanding) it looks like in order to do SMS via Pushbullet, it has to both be installed on my phone, and my phone has to be powered and active.

**Comment by kvangent** [comment]
@mew905 Correct.

**Comment by mew905** [comment]
going into the pushbullet api in C:/python27 and replacing the device_id variable with an actual device ID, removing device from the def, then in the pushbullet_alarm file in the pokealarm, changing push_note to push_sms and having the args be phone number and message (you can snag those lines from the Twilio alarm), works perfectly. Thank you for pointing that out, brettgus :)

**Comment by kvangent** [comment]
Consolidated under #147
