### ISSUE TITLE
[ENHANCEMENT] Gym Details

### ISSUE THREAD

**Issue by jnovack** [kvangent/PokeAlarm#183]
## Enhancement Description

Use the new `gym_details` webhook provided by PR#666 which was merged for additional data.  New alerts can be generated:

* The **White House Lawn** gym has been claimed by **Instinct**!
* **Instinct** is now defending the **White House Lawn** gym with: *Vaporeon* (1435), *Gengar* (1498), *Snorlax* (1999).
* [**Instinct**] **White House Lawn** gym is *under attack*!
* **TrainerName** has fortified the **White House Lawn** gym with: *Magikarp* (*10*) #**Instinct**

If this is related, I'd like to see the messages being templates (is that a different issue?)  So that someone can format the data as one sees fit.

## Use cases

The new `gym_details` webhook sends the Gym Name, Team, Lng/Lat, as well as the current pokemon defending it.  

The `gym_details` webhook fires whenever the data has changed. Including owning team or adding/removing pokemon. The application should maintain state to verify if pokemon have been added `has been fortified with: *Pokemon* (*CP*)` or removed `is under attack!` (Although: "under attack" should check Prestige level, available in the previous webhook, not this one.)

## Other Links

Example JSON: https://gist.github.com/jnovack/655eecb84f9ed24a6ad7e768950ddf25

**Comment by jnovack** [comment]
With no external storage, I suppose you can store the data by key/value in memory. The `id` is the Gym_ID.

When you receive a message, check it against `gyms[id]`.  Find the difference type, announce, store as `gyms[id]`, wait for next message.

The different types of alerts based on this information can be:

* Pokemon Added (not prestige/level changes)
* Pokemon Removed (not prestige/level changes)
* Current occupants/owner (remember, it only sends the webhook if it differs from last scan)

The important piece is the `name`.  This adds a flavor to an otherwise generic "A Gym...".

**Comment by kvangent** [comment]
@jnovack Just so you are aware, PokeAlarm currently accepts webhooks with `gym_details` - It simply doesn't make use of the additional parameters at the moment. This is mostly because these changes are difficult to come up with a simple control/config scheme for.

**Comment by jnovack** [comment]
I'm on the Discord, let's talk.

**Comment by Talhoo** [comment]
I don't care about most of stuff, mostly cause if you let it trigger on every tiny change (new pokemon in the gym, under attack) It would be a lot of messages (spam). But the name of the gym is something I'd really really like.

**Comment by nhumber** [comment]
i would also like the gym names to be a dynamic text sub, would be a nice addition for gyms and also pokestops,
