### ISSUE TITLE
Webhook window closes intermittently

### ISSUE THREAD

**Issue by moggd** [kvangent/PokeAlarm#19]
Hello,

I'm having an issue in which my webhook python window will randomly close after some time.  Sometimes it will close after 5 minutes of running, other times it will close after 8 hours of running.  I'm using the latest time fix posted by kvangent.  Because of this issue, I have to constantly check to see if my webhook server is running and restart it- I'm missing out on some notifications.

Any help would be appreciated.

**Comment by kvangent** [comment]
Are you getting any errors or anything? If you are using Windows add a `pause` to the end of the .bat file. If you are using bash on linux you can add `read -n1 -r -p "Press any key to continue..." key`.  This will prevent the window from closing and allow you to see the error.

**Comment by moggd** [comment]
No, the window just closes.  I've added pause to my bat file and will see if any errors pop up the next time it closes

**Comment by kvangent** [comment]
@moggd Please let me know what you find. I pushed a new version which should take care of the socket errors.

**Comment by kvangent** [comment]
@moggd I've (hopefully) fixed the issue concerning socket errors. If you are still having issues with it after a new pull please open a new issue.
