### ISSUE TITLE
[BUG] AttributeError: 'Nonetype' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Kandrion** [kvangent/PokeAlarm#193]
## Problem Description

I've set up the PokeAlarm and PokemonGo-Map servers what I believe to be correctly, and PokemonGo-Map starts up and runs fine. However, whenever I try to run the PokeAlarm webhook, I receive an error "AttributeError: 'Nonetype' object has no attribute 'encode'." I've tried this on both my Mac and Windows machines, and no amount of research seems to let me fix this easily. Any suggestions?

## Your Environment

Operating System:  Windows 10
Python Version: 2.7.12
PokemonGo-Map startup command: python ./runserver.py
PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?: yes

## Console Output

```
Traceback (most recent call last):
  File "runwebhook.py", line 81, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/Users/mccarthynolan/PokemonGo/PokeAlarm/alarms/alarm_manager.py", line 28, in __init__
    out = out + "{}, ".format(get_pkmn_name(id))
  File "/Users/mccarthynolan/PokemonGo/PokeAlarm/alarms/utils.py", line 183, in get_pkmn_name
    return get_pkmn_name.names.get(str(pokemon_id)).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

## Your Alarms Config

```json
#host: 						# Address to listen on (default 127.0.0.1)
#port: 						# Port to listen on (default: 4000)
key: (personal, but I do have a working one)	 						# Google Maps API Key to use
#config: 					# Alarms configuration file. default: alarms.json
location: (personal again, but I know it's accurate from PokemonGo-Map)					# Location, can be an address or coordinates
#locale: 					# Locale for Pokemon names
#geofence: 					# Specify a file of coordinates, limiting alerts to within this area
units:imperial 					# Specify either metric or imperial
timelimit:90 					# Minimum number of seconds remaining on a pokemon to notify
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
@Kandrion Can you post your Alarms.json instead of your config.ini?

**Comment by Kandrion** [comment]
Sure thing, I copied it below. The code insert made it nigh-unreadable, so I just used plaintext.

{
	"alarms":[
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "True",
			"type":"twilio",
			"account_sid":"(personal)",
			"auth_token":"(personal)",
			"from_number":"(personal)",
			"to_number":"(personal)"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"True",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"True"
	},
	"pokemon":{
		"Bulbasaur":"True",
		"Ivysaur":"True",
		"Venusaur":"True",
		"Charmander":"True",
		"Charmeleon":"True",
		"Charizard":"True",
		"Squirtle":"True",
		"Wartortle":"True",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"True",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"True",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"True",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"True",
		"Pikachu":"True",
		"Raichu":"True",
		"Sandshrew":"False",
		"Sandslash":"False",
		"Nidoran♀":"True",
		"Nidorina":"True",
		"Nidoqueen":"True",
		"Nidoran♂":"True",
		"Nidorino":"True",
		"Nidoking":"True",
		"Clefairy":"True",
		"Clefable":"True",
		"Vulpix":"True",
		"Ninetales":"True",
		"Jigglypuff":"True",
		"Wigglytuff":"True",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"False",
		"Persian":"True",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"True",
		"Growlithe":"False",
		"Arcanine":"True",
		"Poliwag":"True",
		"Poliwhirl":"True",
		"Poliwrath":"True",
		"Abra":"True",
		"Kadabra":"True",
		"Alakazam":"True",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"True",
		"Geodude":"False",
		"Graveler":"True",
		"Golem":"True",
		"Ponyta":"True",
		"Rapidash":"True",
		"Slowpoke":"True",
		"Slowbro":"True",
		"Magnemite":"True",
		"Magneton":"True",
		"Farfetch’d":"True",
		"Doduo":"True",
		"Dodrio":"True",
		"Seel":"True",
		"Dewgong":"True",
		"Grimer":"True",
		"Muk":"True",
		"Shellder":"True",
		"Cloyster":"True",
		"Gastly":"True",
		"Haunter":"True",
		"Gengar":"True",
		"Onix":"True",
		"Drowzee":"False",
		"Hypno":"True",
		"Krabby":"False",
		"Kingler":"True",
		"Voltorb":"False",
		"Electrode":"True",
		"Exeggcute":"False",
		"Exeggutor":"True",
		"Cubone":"True",
		"Marowak":"True",
		"Hitmonlee":"True",
		"Hitmonchan":"True",
		"Lickitung":"True",
		"Koffing":"False",
		"Weezing":"True",
		"Rhyhorn":"True",
		"Rhydon":"True",
		"Chansey":"True",
		"Tangela":"True",
		"Kangaskhan":"True",
		"Horsea":"True",
		"Seadra":"True",
		"Goldeen":"True",
		"Seaking":"True",
		"Staryu":"True",
		"Starmie":"True",
		"Mr. Mime":"True",
		"Scyther":"True",
		"Jynx":"True",
		"Electabuzz":"True",
		"Magmar":"True",
		"Pinsir":"True",
		"Tauros":"True",
		"Magikarp":"True",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"True",
		"Eevee":"True",
		"Vaporeon":"True",
		"Jolteon":"True",
		"Flareon":"True",
		"Porygon":"True",
		"Omanyte":"True",
		"Omastar":"True",
		"Kabuto":"False",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"True",
		"Zapdos":"True",
		"Moltres":"True",
		"Dratini":"True",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"True"
	}
}
`

**Comment by kvangent** [comment]
@Kandrion Can you run in debug mode `--debug` and post that console output? In a pastebin please?

**Comment by Kandrion** [comment]
Sure thing, posted [here](http://pastebin.com/8fxyEmrH)

**Comment by brettgus** [comment]
@Kandrion I think we're going to need more of your debug file... not just those two lines

**Comment by Kandrion** [comment]
I thought it was a bit strange too, but that's all that was in the console? Unless there's a different place I should be looking. Sorry about all this trouble!

**Comment by kvangent** [comment]
@Kandrion So I've narrowed down your problem to being with your alarms.json but I'm not sure why yet.

**Comment by kvangent** [comment]
@Kandrion It looks like your `Farfetch'd` is using a backtick instead of an apostrophe. If you copy and paste it from there, it should work.

**Comment by Kandrion** [comment]
Thanks so much! I just tested, that solved it perfectly. It's weird, I don't think I ever changed that name. Thanks again though!
