### ISSUE TITLE
[ENHANCEMENT] Alarm-specific pokemon

### ISSUE THREAD

**Issue by thatsweater** [kvangent/PokeAlarm#194]
## Enhancement Description
Allowing specific alarms to have specific sets of pokemon. In my case, i have my slack set up in different "tiers", for people with different interests. At the moment, i run 3 different pokealarms, each with their own webhook. If it were possible, i would love to run just one alarm, with pokemon being specified per each alarm, easing up the webhooks on my pokemongomap.

## Use cases
For people with a user base that want separate poke alarms for different purposes.

**Comment by reme-dy** [comment]
See #125 and #137.  Grouping right now is a bit of a nightmare with the current configuration.  I'll leave this open for a bit to let others chime in and close if necessary.

**Comment by kvangent** [comment]
There will never be Alarm-Specific Limits on requests because it's a logistical nightmare for the alarms.configuration. However I have plans for allowed multiple Alarms groupings to run with a single webhook... but it's going to be a while.

**Comment by Malouff** [comment]
Use Dynamic Substitutions to create the dynamic Pokémon channels
Example: `"pkmn_channel":"#<id>-<pkmn>",`
`<id>` is 1-151 not 001-151 So `#1-bulbasaur to #151-mew`

You will have to create all of of the 151 channels first though, then people can subscribe to the individual Pokémon alerts. 

You could also dump everything into another channel too.  I do this with Slack &  have alerts for Pokémon people are missing but have the everything channel favorited to see what else is around.

**Comment by kvangent** [comment]
Closing this - there will never be alarm specific pokemon alerts, but if PogoMap ever comes back I will finish up the changes for multiprocessing to allow multiple alarms run off one webhook.
