### ISSUE TITLE
[ENHANCEMENT] Pokémon Counter

### ISSUE THREAD

**Issue by AlbertEspinosa** [kvangent/PokeAlarm#198]
## Enhancement Description
The Pokémon counter will let you know how many times a certain Pokémon has appear today.
Example:
> Snorlax has appeared 5 times today!
> Dragonite has appeared 3 times today!
> Gyarados has appeared 8 times today!

You should be able to set the Pokémon you want on "counter.json"

## Use cases
Command:
/counter - (Telegram)

**Comment by darkelement1987** [comment]
How about /counter <name of pokemon> :-)
