### ISSUE TITLE
[BUG] Twitter startup_message and startup_list do not display desired timezone-formatted time when user specifies timezone with -tz

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#201]
## Problem Description
Twitter startup message and startup list post server UTC time and ignores user-provided `-tz` argument when optional parameters `startup_message` an `startup_list` are set to `true`

## Your Environment

Operating System:  Windows 10
Python Version: (use `python -V`)  2.7.12
PokemonGo-Map startup command: `python .\runserver.py`
PokeAlarm startup command: `python .\runwebhook.py -tz America/Los_Angeles`

Did the issue persist after restarting the script?: yes

## Console Output
Timezone is set, according to log:

```
2016-09-05 11:49:10,102 [             utils] [   INFO] Timezone set to: America/Los_Angeles
```

## Your Alarms Config
`startup_message` and `startup_list` are both set to `True`.  Below is an excerpt from `alarms.json`:

```json
		{
			"active": "True",
			"type": "twitter",
			"access_token": ".",
			"access_secret": ".",
			"consumer_key": ".",
			"consumer_secret": ".",
			"startup_message":"True",
			"startup_list":"True",
			"pokemon":{
				"status": "<pkmn> in <neighborhood> at <address> <city> <postal> until <24h_time> (<time_left> remaining). <gmaps>"
			},
			"pokestop":{
				"status": "Someone has placed a lure on a Pokestop! Lure will expire at <24h_time> (<time_left>).  <gmaps>"
			},
			"gym":{
				"status":"A Team <old_team> gym has fallen! It is now controlled by <new_team>. <gmaps>"
			}
		},
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Done with commit b2eaa649585f0d27b9abb91f4f8c008a5518fd89.
