### ISSUE TITLE
[USER SPECIFIC] Twitter Bot showing startup but no pokemon

### ISSUE THREAD

**Issue by RovingSpirit** [kvangent/PokeAlarm#202]
## Problem Description
Twitter bot sending startup message and terminal running fine but no alarms/pokemon found

## Your Environment

Operating System:  OSX
Python Version: (use `python -V`)  : 2.7.12
PokemonGo-Map startup command: `<python ./runserver.py>`  
PokeAlarm startup command: `<python ./runwebhook.py>`

Did the issue persist after restarting the script?: yes

## Console Output

```
2016-09-06 02:35:49,471 [     twitter_alarm] [   INFO] Twitter Alarm intialized.
2016-09-06 02:35:49,471 [     alarm_manager] [   INFO] PokeAlarm has started! Your alarms should trigger now.
2016-09-06 02:35:49,471 [        runwebhook] [   INFO] Webhook server running on http://127.0.0.1:5000
```

## Your Alarms Config

```json
#host: 					         	# Address to listen on (default 127.0.0.1)
port:5000 						# Port to listen on (default: 4000)
key: 	XXXXYYYY		                	# Google Maps API Key to use
#config: 					               # Alarms configuration file. default: alarms.json
location: 	X University, City				# Location, can be an address or coordinates
#locale: 					# Locale for Pokemon names
#geofence: 					# Specify a file of coordinates, limiting alerts to within this area
#units: 					# Specify either metric or imperial
#timelimit: 					# Minimum number of seconds remaining on a pokemon to notify```

ALARMS CONFIG
	"alarms":[

		{
			"startup_list":"False",
			"active": "True",
	    "type": "twitter",
	    "access_token": "ABC123",
	    "access_secret": "ABC123",
	    "consumer_key": "ABC123",
	    "consumer_secret": "ABC123",
			"startup_message":"False",
             "startup_list":"False",
             "pokemon":{
                 "status": "<pkmn> in <neighborhood> at <address> <city> <postal> until <24h_time> (<time_left> remaining). <gmaps>"
             },
             "pokestop":{
                 "status": "Someone has placed a lure on a Pokestop! Lure will expire at <24h_time> (<time_left>).  <gmaps>"
             },
             "gym":{
                 "status":"A Team <old_team> gym has fallen! It is now controlled by <new_team>. <gmaps>"
             }
         }
	],
(yes i have some pokemon set to True)
```
## Troubleshooting Checklist
[ X] Most recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
It doesn't look like you are receiving requests. 

I see that you are also set to Port 5000. Is your PokemonGo-Map also running on port 5000? Is PokemonGo-Map running on the same port? Did you make sure that you added the webhook address (`http://127.0.0.1:5000`) to PokemonGo-Map?

You commands from above to run PokeAlarm are obviously wrong, but I'm assuming this is because you were too lazy to write them out and just copy/pasted from PokemonGo-Map.

**Comment by RovingSpirit** [comment]
My webhook on pokemongo-map was set to an old slack webhook. Thanks for the quick answer!
