### ISSUE TITLE
Typo In Wiki

### ISSUE THREAD

**Issue by ChilliHam** [kvangent/PokeAlarm#205]
Sorry if this is the wrong spot to put this, but I was looking at the wiki and notice this.

"channel":"Gyms",
"title":"Someone  has placed a lure on a Pokestop!",
"body":"Better hurry! The lure only has <time_left> remaining!."

It is located in the "Alarm Configuration" section

**Comment by reme-dy** [comment]
lol sure. Thanks for bringing it up. :)

**Comment by kvangent** [comment]
In the future, please make sure you stick to the Issue template.

Also, wiki issues should be directed [here ](https://github.com/kvangent/PokeAlarmWiki)
