### ISSUE TITLE
[Enhancement] Error/Debug channel

### ISSUE THREAD

**Issue by joberembt** [kvangent/PokeAlarm#206]
## Enhancement Description

If my feature request for the map is implemented (https://github.com/PokemonGoMap/PokemonGo-Map/issues/1206), we will need some sort of channel/mode for receiving and displaying it.

## Use cases

If you get IP Banned, or accounts are banned, rather than just hammering away at things, you can get a notice and be able to log in to make changes.

**Comment by kvangent** [comment]
If this gets merged, feel free to reopen. I'd like to keep issues clear as a todo list.
