### ISSUE TITLE
No bug, just idea

### ISSUE THREAD

**Issue by roflinger** [kvangent/PokeAlarm#209]
Now it sends everything in one message, that´s pretty nice. 
But i only see in my preview bar on android "MrBot send a location" and not the triggered pokemon anymore..

any chance to get back the info of the pokemon in the preview (slidebar) again?

**Comment by kvangent** [comment]
@roflinger In the future, please stick to the issue template.

I will probably add in the option to choose between the double message and the single message. There is no way with the single message to change it to anything besides the location.

**Comment by roflinger** [comment]
ok sorry :)
i will go back to an older version, thx anyway

**Comment by roflinger** [comment]
thx
