### ISSUE TITLE
[ENHANCEMENT] Remove "None" responses in reverse location lookup

### ISSUE THREAD

**Issue by krummrey** [kvangent/PokeAlarm#211]
## Problem Description
I live in a rural environment where google returns quite a lot of "None" responses for streetsnames and house numbers. The alarms send out the "None" which makes no sense.

Wouldn't it make sense to just remove those responses and return empty strings so that they don't get sent out?

## Your Environment
Operating System:  
Ubuntu

Did the issue persist after restarting the script?: yes

## Console Output
Sichlor in L91 None, 22955 Hoisdorf
Zu erwischen bis 11:57:34  (14m 59s).
http://maps.google.com/maps?q=53.657859635

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x ] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by reme-dy** [comment]
Yes it would make sense if we had a standardized output message for everyone. With Dynamic Text Substitution available for the users, returning an empty string may not make sense grammatically for many of the notifications.  A possible message might be, `"<pkmn> in <neighborhood> at <address>, <sublocality>, <city>"`.  Returning an empty string instead of **None** might result in a message:

>Dragonite in at ,

which is just as, if not moreso, confusing.  (I've had a bunch of Nones similar to this happen to me a few times already.)

You're welcome to modify the alarm service code if you are proficient at providing the relevant conditionals for your use case (though this is obviously not officially supported by the dev team).

**Comment by kvangent** [comment]
I agree with @reme-dy that it would make things more confusing for people. If you wish, you could go into the reverse location function and set the defaults to '' which would fix the problem for you locally. 

I'll leave this open to get input from others. Perhaps if there is enough interest we can add an optional argument.

**Comment by Talhoo** [comment]
One thing that maybe should be put on an empty string is the address number. No use to have "none none" can be reduced to just "none". I myself will probably change it, I use the city name and that will never return a "none" so it will always return "pokemon found in <city>

**Comment by toshioson** [comment]
@kvangent Could you please kindly guide me how to change the default to '' or something else? I looked into the reverse_location(info) session in utils.py but have no idea about it.

Being able to change it for me is quite important as it quite often returns None for me. I even tried to put some codes to do that if it returns None but could not get it done.

Thanks and sorry for my ignorance.

**Comment by kvangent** [comment]
@toshioson You can specify the defaults for .get(key) by changing it to .get(key, default value)
![image](https://cloud.githubusercontent.com/assets/10712294/18408272/d9912b10-76f0-11e6-87e9-77ff77769f87.png)

**Comment by brettgus** [comment]
I've seen quite a few people mention this in the discord.  What about adding additional argument for the geocoded variables such as <address-hidenone> or something along those lines?

**Comment by krummrey** [comment]
I'd prefer an extra argument. That way you could set either an empty string "" or a localized one i.e. "unbekannt" in german. Would solve two current problems.

**Comment by PoliSwagAllDay** [comment]
@kvangent can you tell me where that code you posted is located? Trying to include neighborhood in my notifs. Don't see that section in the alarm config wiki. Already added geocoding api and editi notif text with <neighborhood> and no luck.

**Comment by kvangent** [comment]
@PoliSwagAllDay It is located in alarms/utils.py (I think under reverse_location or something).

**Comment by PoliSwagAllDay** [comment]
So I would delete the pound sign in front of "Returns true" delete the
pound sign in front of "reverse location" and enter 'neighborhood' in my
alarm text?
