### ISSUE TITLE
[ENHANCEMENT] Remove the trailing text when using timezone parameter.

### ISSUE THREAD

**Issue by neskk** [kvangent/PokeAlarm#212]
## Enhancement Description
When you change the Timezone (-tz) to adjust for the server not being in the same timezone as you, it appends some letters after the actual <24htime>. E.g.: 17:45 WEST - probably means it's Western Europe Time. This is kinda redundant and annoying, tends to make the time harder to read and pollutes the overall message. I would love to see this crappy thing removed, maybe use regex to trim the string.

**Comment by kvangent** [comment]
I agree it was redundant. Remove in 0228be9220a1a8c1f08f3f2d011e9749f4972033.

If people are upset, they can open another ticket and maybe I'll add an option to enable it, otherwise use dynamic text to just add it in yourself.
