### ISSUE TITLE
Slack mini map not working

### ISSUE THREAD

**Issue by SeeingBlue** [kvangent/PokeAlarm#217]
I copied the advanced config out of the slack setup page. Everything works. I'm getting notifications but the minimap is not appearing. Any ideas why?

python 2.7.12
windows 10 x64

**Comment by SeeingBlue** [comment]
Whats the solution @reme-dy

**Comment by brettgus** [comment]
Did you not see this when you opened the issue?

```<!--- ALL ISSUES CREATED NOT USING ONE OF THE BELOW ISSUE TEMPLATES WILL BE CLOSED WITHOUT RESPONSE --->```

**Comment by SeeingBlue** [comment]
I have solved this issue now. It was a 1 single permission issue with my api key that I had been using w/ no issues until PokeAlarms. So I didn't think to check it.

I ask users to follow a template on my free support forums too, but just because they don't doesn't mean I ignore them because I understand that not all questions are needed to solve an issue.

**Comment by brettgus** [comment]
@SeeingBlue Unfortunately, most of the time that information is needed to diagnose the problem.
