### ISSUE TITLE
No module named gevent error, but Gevent IS installed.

### ISSUE THREAD

**Issue by rievna** [kvangent/PokeAlarm#22]
I saw the "no module named gevent" issue that was closed. I'm having the same issue, BUT gevent is installed and I'm running off the latest pull. See below:
> Last login: Mon Aug  1 21:11:53 on ttys010
MacBook-Pro:~ user$ cd /Users/user/Documents/PokeAlarm-master 
MacBook-Pro:PokeAlarm-master user$ sudo -H pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pushbullet.py==0.10.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): slacker==0.9.24 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): twilio==5.4.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): telepot==8.3 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gevent==1.1.2 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from Flask==0.11.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in /Library/Python/2.7/site-packages (from Flask==0.11.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from Flask==0.11.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Library/Python/2.7/site-packages (from Flask==0.11.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in /Library/Python/2.7/site-packages (from pushbullet.py==0.10.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): python-magic in /Library/Python/2.7/site-packages (from pushbullet.py==0.10.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in /Library/Python/2.7/site-packages (from pushbullet.py==0.10.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.7 in /Library/Python/2.7/site-packages (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): urllib3==1.9.1 in /Library/Python/2.7/site-packages (from telepot==8.3->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from gevent==1.1.2->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Library/Python/2.7/site-packages (from Jinja2>=2.4->Flask==0.11.1->-r requirements.txt (line 1))
MacBook-Pro:PokeAlarm-master user$ python runwebhook.py
Traceback (most recent call last):
  File "runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: No module named gevent
MacBook-Pro:PokeAlarm-master user$ sudo -H pip install gevent
Requirement already satisfied (use --upgrade to upgrade): gevent in /private/var/root/Library/Python/2.7/lib/python/site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from gevent)
MacBook-Pro:PokeAlarm-master user$ sudo -H pip install greenlet
Requirement already satisfied (use --upgrade to upgrade): greenlet in /private/var/root/Library/Python/2.7/lib/python/site-packages
MacBook-Pro:PokeAlarm-master user$ python runwebhook.py
Traceback (most recent call last):
  File "runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: No module named gevent
MacBook-Pro:PokeAlarm-master user$

**Comment by rievna** [comment]
After Googling around, I was able to get it to work using `python -m pip install gevent` but it is weird because as you can see above, no error message was ever generated. Ah well!

**Comment by kvangent** [comment]
Awesome, thanks for posting your fix!

**Comment by rievna** [comment]
No problem! For your future reference if anything like this ever comes up again, from what I was reading while searching for a solution, it may have had to do with OSX's system integrity protection. This was where I found my info: [https://github.com/HelloZeroNet/ZeroNet/issues/286](url)

**Comment by LittlePoke** [comment]
So im still getting this issue with Gevent. no module found. any other thoughts ?

**Comment by kvangent** [comment]
@LittlePoke It's hard to tell what is going on without more information. 

Make sure you have the most recent version of python 2.7 (2.7.12), make sure you use `pip install --upgrade gevent`, and try the above `python -m pip install gevent`.

**Comment by LittlePoke** [comment]
Traceback (most recent call last):
  File "C:\GIT\Git-Pokealarm\runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: No module named gevent

I have run all the updates and Gevent is there. a little lost with what to do next, if you have any ideas or want specifics just tell me and I will get it. im definitely just getting into this stuff.

**Comment by LittlePoke** [comment]
$ python -m pip install gevent
Requirement already satisfied: gevent in c:\python27\lib\site-packages
Requirement already satisfied: greenlet>=0.4.9 in c:\python27\lib\site-packages (from gevent)

same message from both pip's

**Comment by kvangent** [comment]
@LittlePoke 

First try 'python -V`. I'm willing to bet that it is a lower version of python 2.7.

Then try `pip list` and let us know what gevent version you are running.

**Comment by LittlePoke** [comment]
$ python -V
Python 2.7.12
gevent (1.1.2)
@kvangent

**Comment by kvangent** [comment]
@LittlePoke 
Try the following and post back:
1. What version of Windows are you runnning, including 32/64x?
2. Run `python-32 -c 'import struct;print( 8 * struct.calcsize("P"))'` (Should output python version)

Another thing you could try to do is to uninstall gevent and reinstall, making sure that you are running in an administrative console.

**Comment by manbharae** [comment]
https://stackoverflow.com/questions/49198346/no-module-named-gevent-even-though-it-is-installed any help here guys?
