### ISSUE TITLE
[ENHANCEMENT] Send notifications only near your position, even running multiple workers.

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#221]
## Enhancement Description

I will try to describe my setup as best as possible, and it may be a bit personalized, but right now I haven't found a way to fix this.

I have 4 workers on different points of the city (mainly parks) that are constantly scanning with -ss method. I also have one main worker that follows my location wherever I go, and that one sends updates to webhooks so PokeAlarm notifies me if a rare Pokémon appears nearby my location. Notice that I am often nearby the areas where the other scanners are running so they often overlap position (both the -ss scan and the hexagon one that follows me).

Traditionally, I still got notified because found Pokémon for both workers were upserted on the database, and even if -ss found the Pokémon first (it does, because it goes to the spawn point right at the pop time), whenever the hexagon passed nearby and found the Pokémon, it would send the notification to webhooks and I still would be notified of the rare Pokémon I wanted.

What changed now is that with the new IV PR (https://github.com/PokemonGoMap/PokemonGo-Map/pull/1272) that most likely will get incorporated to the main branch, it now disables the upsert of duplicated Pokémon to the DB, as per the notes:

> A somewhat major change I made is now before each pokemon is parsed, I query the database to see if any active spawns with that encounter_id are already in there, and if so I skip them entirely. This is to avoid having to re encounter any pokemon that get scanned multiple times, otherwise the new stats would be wiped once the pokemon was reinserted. I then bump a new 'skipped' variable, and add that count when we log how many pokemon we found to avoid people seeing false '0' results.

So, since the -ss workers find the Pokémon first (but I don't have them configured on PokeAlarm, because I may not be around that location and it would be alerting me of Pokémon I can't get), whenever my mobile hexagon gets to the Pokémon location, it won't send a notification because the Pokémon is already on the DB.

I have been thinking about various ways to solve this, but can't get to find a solution. I know that PokeAlarm has the capabilities to only notify of Pokémon that are at certain distance from you, but in the case of the other workers, it would only notify based on the start location of the worker, and not on your actual moving location.

Is there any configuration I am missing, or any way we could solve/improve this?

Thank you!

**Comment by reme-dy** [comment]
Check out PR #117 and commit https://github.com/kvangent/PokeAlarm/commit/564599d8aa8311e738125c11a8f0ea8f75b22634 for updating you location on the fly.  @brettgus can chime in with the details. =)

**Comment by Imoq** [comment]
Wow, thank you very much! :)

**Comment by bluelatios** [comment]
@Imoq ,  can you teach me how to set up 4 workers, and exactly how to set up workers that follow my current location like you said?
Any help appreciated thanks :D

**Comment by Imoq** [comment]
@bluelatios : sorry, it is outside the scope of PokeAlarm / Git issues section. Can discuss on Discord if you want: https://discordapp.com/channels/204338767920758785/204339169458126849
