### ISSUE TITLE
[BUG] Error while processing request: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by lota7** [kvangent/PokeAlarm#223]
## Problem Description

Getting Error while processing request: 'NoneType' object has no attribute 'encode' in log.
Why is this coming?

## Your Environment.

Operating System:  Win 10
Python Version: (use `python -V`)  Python 2.7
PokemonGo-Map startup command: `start D:\PoGoMaps\PoGoMapDev10SS\runserver.py -a ptc -u xxx -p xxx-l "xxx"`  
PokeAlarm startup command: ` start D:\PoGoMaps\PokeAlarm-master2\runwebhook.py -l "xx`

Did the issue persist after restarting the script?: yes

## Console Output

```
	2016-09-14 15:55:28,881 [     alarm_manager] [   INFO] Pidgeotto ignored: notify not enabled.
2016-09-14 15:55:30,828 [     alarm_manager] [  ERROR] Error while processing request: 'NoneType' object has no attribute 'encode'
2016-09-14 15:55:38,437 [     alarm_manager] [   INFO] Venonat ignored: notify not enabled.
2016-09-14 15:55:43,509 [     alarm_manager] [   INFO] Rattata ignored: notify not enabled.
```

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x ] Most recent version of PokeAlarm
[x ] Checked the Wiki page for service in question (Used search on the error)

**Comment by brettgus** [comment]
Can you post your console output with --debug?

**Comment by lota7** [comment]
Found the issue, it was due to IV and moves not being sent from pokemongomap.
Which means I have to enable IV scanning on pokemongomap and then enable notifications in pokealarm.

Might be unnecessary in the case when I want notifications on certain pokemon I dont have just for collection, but others I want to know IV also.
