### ISSUE TITLE
Multiple errors on Pokemon

### ISSUE THREAD

**Issue by Plop** [kvangent/PokeAlarm#23]
Hi,

Running `python runwebhook.py -L fr` gives me those errors :

![image](https://cloud.githubusercontent.com/assets/876470/17320866/fe9352c2-5895-11e6-8300-e8c4de736e2e.png)
![image](https://cloud.githubusercontent.com/assets/876470/17320875/04aef0e4-5896-11e6-85f7-b7291731a4de.png)
![image](https://cloud.githubusercontent.com/assets/876470/17320891/192041b8-5896-11e6-9da0-9f88a152a3bf.png)

I can't find what's causing this. 
Seems that using "-L fr" is the issue.

Thanks for helping

**Comment by kvangent** [comment]
If you use -L fr, you need to adjust the name of the pokemon in the Alarms.json as well.

**Comment by Plop** [comment]
Oh, that's it. Well, gonna do this. Thanks :)
