### ISSUE TITLE
[ENHANCEMENT] Starting up text disabler

### ISSUE THREAD

**Issue by NickFlamel** [kvangent/PokeAlarm#238]
## Description:
A true/false option in the config for disabling the startup text that spams Twitter.

## Use Cases:
Spamming people isn't nice, and I don't want anyone to get pissed off when my computer restarts or the power goes out.

## Other Links
The file that would have to be edited is twitter_alarm.py for twitter alarms. Not sure about the others.

**Comment by jnovack** [comment]
Undocumented variable.

```
{
    "alarms": [
        {
            "type": "twitter",
            "startup_message": "False"
        }
    ]
}
```

**Comment by kvangent** [comment]
Not even undocumented:
![image](https://cloud.githubusercontent.com/assets/10712294/18809093/9e4333b0-8239-11e6-98db-6fc8be391b70.png)
