### ISSUE TITLE
[ENHANCEMENT] Possible to add encounter id and show as hashtag in Telegram alert?

### ISSUE THREAD

**Issue by toshioson** [kvangent/PokeAlarm#242]
## Enhancement Description
Want to show the encounter id of the Pokemon in the body of Telegram alert and also show as hashtag so that you can tap/click on the encounter id in Telegram to immediately start a search with that encounter id.

## Use cases
This would be useful to identify the pokemon. One use is to confirm if it is duplicates as there are more and more "double pokemon" showing up at similar timing and location.

**Comment by kvangent** [comment]
Yes, I'll get this done shortly.

**Comment by kvangent** [comment]
Completed as of 0368bf6a016396837b6265a7e3557ff18e5f1b8f.
