### ISSUE TITLE
ENHANCEMENT: Scheduled Public Service Announcements

### ISSUE THREAD

**Issue by jbum** [kvangent/PokeAlarm#245]
## Enhancement Description
It would be useful for my Twitter feeds to post hourly public service announcements (about safety, mostly) between the hours of 10pm and 6am.  

## Use cases
In parts of Los Angeles, some trainers have been mugged while going after rare pokemon at night.  An hourly announcement feature would help raise awareness of safety.

**Comment by kvangent** [comment]
@jbum While I like the idea, I feel it may be a little outside PokeAlarm's intended use-case and I don't want to see a bunch of feature bloat. It may be better to use another tool like http://www.autotweeter.in/ or some other automated twitter tool to make these tweets.
