### ISSUE TITLE
[ENHANCEMENT] Add Attack Points to Moves

### ISSUE THREAD

**Issue by neutron666** [kvangent/PokeAlarm#247]
## Enhancement Description

Add Attack Points to moves. Example:

Move1: Bite (6), Move2: Hyper Beam (120)
## Use cases

You can see the attack points and decide more easily. Saw this on another Notifier.

**Comment by kvangent** [comment]
This would require updating the moves.json to a format similar to PokemonGoMap that has more information.

**Comment by neutron666** [comment]
Maybe I can provide this. Will check later.

**Comment by Cel1ca** [comment]
I'm trying to translate locale moves.json to Italian language. Please keep me informed if you need this to update the Attack Point inside.

**Comment by neutron666** [comment]
Ok, i could provide a extra file which has the same ID Numbers from 1-241 (like you use in your moves.json) inlcuding the move damages. So those Damage Points would be in an extra file which you just would need to parse. How about that ?

**Comment by Cel1ca** [comment]
If you can parse it, It will be great. So, if I understand well moves.json files is not going to change...
In that situation It will be easier to keep older locate version.

**Comment by neutron666** [comment]
This would be the case if @kvangent want's this that way. Let's wait on him.

**Comment by kvangent** [comment]
@neutron666 We can avoid worrying about translations for now if we just get a move_id to damage json.

Should be in the format "name":"5". But I don't know if you want to make one for attack or dps or what you guys would prefer.

**Comment by neutron666** [comment]
How can I send you the file I have? Just have a look at it

**Comment by kvangent** [comment]
@neutron666  Just post it in a paste-bin is fine.

**Comment by neutron666** [comment]
http://pastebin.com/81a95Uic

There you go. I can try to submit it as PR, however, it's a completely new file.

**Comment by kbtbc** [comment]
I see the moves-info.json PR to add this info.  What changes do I need to add to the code to get those actaully into the alarms?

**Comment by kvangent** [comment]
I'm going to close this for housekeeping as we move to v3. If anyone thinks this feature will still be useful feel free to re-open and I'll re-examine the issue.

**Comment by neutron666** [comment]
I still think this is usefull. I would like to see the moves and dp's in the notification. How can i reopen it ?
