### ISSUE TITLE
[Enhancement] Dynamic text substitution for <cp>

### ISSUE THREAD

**Issue by theresthatguy** [kvangent/PokeAlarm#249]
## Enhancement Description
Add <cp> to possible pokemon dynamic substitutions.

## Use cases
Perhaps a Pokemon's IV is low but has high CP (like over 2000): I wouldn't want to go after a 50 IV/ under 1000 CP but I would go after a 50 IV / over 2000 CP.

**Comment by kvangent** [comment]
CP is different for every user, so it is impossible for the map to gather this information.
