### ISSUE TITLE
[ENHANCEMENT] More personal push notifications for service Pushover

### ISSUE THREAD

**Issue by hd1080** [kvangent/PokeAlarm#250]
## Enhancement Description
It would be great if I can set different sounds and priorities for each pokemon.

## Use cases
I would set an emergency priority for very rare pokemons like Dragonite, Snorlax, ... so I won't miss them. For example today I missed a Snorlax while I was outside. With the emergency priority I would have get several notifications and I wouldn't have missed it :) 
A different notification sound for pokemons would help me to decide if I have to look on my phone or not in a situation where I would only leaf for rare pokemons. If it is too much work to have different notification sounds for each pokemon it would be great to just change the sound for all PokeAlert notifications.

## Other Links
https://pushover.net/api#priority
https://pushover.net/api#sounds

**Comment by kvangent** [comment]
Because Pushover has terrible business policies and my trial has expired, I can't test this to ensure that it works.

But if you want to try [this branch](https://github.com/kvangent/PokeAlarm/tree/pushover_sounds) and let me know if it works, I'll pull it into master.

**Comment by hd1080** [comment]
It works great! 👍 
Do you think you could add the priority stuff as well? If not I will try to add it myself.

**Comment by kvangent** [comment]
It's pretty hard to do it per pokemon because of the way everything is structured. I would only be able to do it so that it's priority of all alerts PokeAlarm sends. Is that what you want?

**Comment by hd1080** [comment]
No that wouldn't help me much.
