### ISSUE TITLE
webhook start and closes instantly

### ISSUE THREAD

**Issue by blestpsycho** [kvangent/PokeAlarm#255]
guys i launch "runwebhook.py" and closes instantly i took a photo before the .py is closed

i need help 

![screenshot_1](https://cloud.githubusercontent.com/assets/22419543/19024624/79646eec-88dd-11e6-8713-9c2f7ecdaf2e.png)

**Comment by kvangent** [comment]
@blestpsycho Please make sure you use the issue template.

Your issue it JSON related.
