### ISSUE TITLE
Slack icons

### ISSUE THREAD

**Issue by mythicaldog** [kvangent/PokeAlarm#26]
Slack icons are really blurred is there a way we can clean them up?

**Comment by kvangent** [comment]
If you have some higher resolution icons that we have permission to use, please let us know.

**Comment by mythicaldog** [comment]
I'll have a search, are you using the ones from PokemonGo-Map?

**Comment by kvangent** [comment]
Yes.

**Comment by mythicaldog** [comment]
I see they have their Hi-res in a sprite map, I've switched my local copy to use the pixel icons
