### ISSUE TITLE
[ENHANCEMENT] shutdown warning

### ISSUE THREAD

**Issue by Brtrnd** [kvangent/PokeAlarm#260]
## Enhancement Description

Create the possibility to end the process and give a warning of the end of the process. I'm using a telegram public channel; I'd like it to say something like "I'm stopping to alarm for pokemons".

This may be implemented if there is no connection to the pogomap (if it's possible to check in that direction?); if no pokemons have been caught for x time or when I specifically stop the service from running.

## Use cases

I don't scan continuously. If somebody else but me uses my channel, they don't know when I stop checking and may think the system is broken.

**Comment by kvangent** [comment]
There is pretty much no good way to do this without significant changes in how PokeAlarm is run and I don't think it would be useful enough to justify the work, so I am going to close this for now.
