### ISSUE TITLE
[BUG] Slack channel defaulting to wrong channel

### ISSUE THREAD

**Issue by neskk** [kvangent/PokeAlarm#263]
## Problem Description

From time to time (time intervals seem random) Slack channels stop working and all notifications are dumped in "#general" chat. PokeAlarm doesn't seem to notice anything so I suspect it isn't its fault and instead maybe it's Slack's API that is malfunctioning... I suggest a parameter could be added to the config.ini file: *default-channel*, so we can change the default channel where messages are dumped in case of any errors.

## Your Environment

Operating System:  Ubuntu 16.04
Python Version: 2.7.12
PokeAlarm startup command: `python ./PokeAlarm/runwebhook.py -P 4001 -c alarms-all.json`

Did the issue persist after restarting the script?: *no*

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active": "True",
			"type":"slack",
			"api_key":"",
			"channel":"random",
			"startup_message":"False",
      "startup_list":"False",
      "pokemon":{
          "channel":"pkmn-<pkmn>",
          "username":"<pkmn>",
          "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
          "title":"<pkmn> (<iv>% <atk>/<def>/<sta>)",
          "url":"<gmaps>",
          "body": "Expira às <24h_time> (faltam <time_left>)\n IV: <iv>% (<atk>/<def>/<sta>)\n Ataque 1: <move1>\n Ataque 2: <move2>",
          "map": { 
              "enabled":"true",
              "width":"350",
              "height":"200",
              "maptype":"roadmap",
              "zoom": "15"
          }
      }
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
               }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"False"
	},
	"pokemon":{
		"max_dist":"inf",
		"min_iv":"0",
		"Bulbasaur":{ "min_iv":"80" },
		"Ivysaur":{ "min_iv":"80" },
		"Venusaur":{ "min_iv":"80" },
		"Charmander":"True",	
		"Mew":"True"
	}
}
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Hi @neskk,

Thanks for using the issue template.

Unfortunately, it's hard to say why PokeAlarm is changing channels since you didn't post your console output. Whenever Slack posts to a no standard channel, it should output a message into the console to say why.

Is it certain pokemon that aren't updating correctly? If so, it may be that you don't have a channel for that pokemon created properly. 

Slack already has a default channel selection: Slack tried the channel specified at the alert level. If there is no channel at the alert level, it defaults to the the channel specified at the alarm level. If this doesn't work, it then finally reverts to the general channel. Thus if your channel exists at the alarm level, it should revert to that channel.

**Comment by neskk** [comment]
Thanks for the quick reply, next time it happens I will post console output. I have created channels for each pokémon so it isn't that kind of problem.
I run 12 instances of PokeAlarm each with a different config in order to provide custom channels for several regions/neighborhoods of my city. All of them fail and start dumping notifications in "#general", but the map seems to work fine and so does the webhook (as far as I'm aware no notifications get lost or anything).

**Comment by kvangent** [comment]
@neskk Another possible option is that you are running out of geocoding qouta on your API_key, and this is causing all of your city-channels to not be calculated correctly. 

And if you missed it, you should be able to default the channel for each alarm by setting the "channel" field at the alarm level.

**Comment by neskk** [comment]
@kvangent I didn't miss it :) In the config file I posted here you can see I tried to do that with `channel:random` at the Slack alarm level.
I'm not using geocoding anymore, It works fine but after a while it starts to output "error!" instead of the *walk_dist*. That said even if it was the case I'm pretty sure this issue isn't related to the google API limits, your software seems to handle pretty much everything gracefully ;)

**Comment by kvangent** [comment]
My guess is that `error!` is related to reaching your API Quota as well.

**Comment by neskk** [comment]
@kvangent you've misunderstood me. (maybe I wasn't that clear...)
`error!` is definitely because I reached my Google's API quota so I stopped using it. I meant that this error (API quota) seems to have no influence on the problem discussed above.

**Comment by kvangent** [comment]
If you were hitting your API quota before, it seems likely you might possible be hitting it again with <city>.
