### ISSUE TITLE
[ENHANCEMENT] Mentioning the "locale" source somewhere :)

### ISSUE THREAD

**Issue by asukakenji** [kvangent/PokeAlarm#266]
## Enhancement Description
Would you please mention where you got the translations in the `/locale` directory?

## Use cases
One possible source would be https://github.com/asukakenji/pokemon-go/tree/master/pokemon/internal/.

Mentioning so would encourage the original author to make better software / tables. Cooperating to make sure that the data is correct is also a good idea.

**Comment by kvangent** [comment]
The locales were taken from PokemonGo-Map when it first started. If I ever get around to working on this again, I will be updating the locales to allow for more customization.
