### ISSUE TITLE
[BUG] Missing Pokemon with multi-script running at same time

### ISSUE THREAD

**Issue by m4rtint** [kvangent/PokeAlarm#267]
## Problem Description

Situation:
At times I've noticed that it will skip out on the notifications, I look at the logs and it doesn't seem to appear (not ignored, not notified, just not there), whereas the Pokemon show up on the map.

## Your Environment

Operating System:  
Python Version: 2.7.12
PokemonGo-Map startup command: 
I run three instances - honey spot
st 6, sd 60
st 5, sd 60
st 6, sd 60
All the webhooks point to the same PokeAlarm

PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?: yes

## Your Alarms Config
No changes, all comments out

## Troubleshooting Checklist
[X ] Most recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
@m4rtint It's hard to say what is going wrong without more information. It's possible that some issues have crept in with the new API change. I would suggest running in `--debug` mode and see if you generate any more errors.

**Comment by m4rtint** [comment]
The only theory I had personally, was because i'm running 3 instances at the same time, which i can't think of any reason as to why it might affect it. Is this at all possible?

Thanks for replying though. I'll take a look at debug mode

**Comment by kvangent** [comment]
It seems pretty unlikely it is because of multiple python instances.
