### ISSUE TITLE
German alarms.json

### ISSUE THREAD

**Issue by gine78** [kvangent/PokeAlarm#27]
Hey,
has anyone create a german alarms.json and want to share it?

**Comment by kvangent** [comment]
If you wish to create a locales file, I can generate the alarms.json. You can see more locales in the locales folder.

**Comment by gine78** [comment]
I only need the _de alarm.json. I have no time yet to create one. But if i found some minutes, i can create one

**Comment by kvangent** [comment]
I forgot to let you know, but I updated default alarms.json to include all supported languages.
