### ISSUE TITLE
[BUG] Twillo <gmaps> key is presenting a malformed link

### ISSUE THREAD

**Issue by Calvinthesneak** [kvangent/PokeAlarm#270]
## Problem Description
 I've set up a Twillo account to text message about rare pokemon.  Setup was easy, service works great, however the <gmaps> dynamic text is sending an incomplete link, it breaks after the lat, and the long portion is not included with the link.  There is no space after the comma, but it just breaks there  IE.  Google:http://maps.google.com/maps?q=50.7810938503, -125.8532352645154362356 

![screenshot_20161113-143741](https://cloud.githubusercontent.com/assets/23301696/20249536/116456ba-a9b0-11e6-90b5-5cc9854eb5c5.png)

 ## Your Environment

Operating System:  Windows 10 Pro 64bit
Python Version: 2.7.12
PokeAlarm startup command: `python runwebhook.py`

Did the issue persist after restarting the script?: yes

## Console Output

```
	
```

## Your Alarms Config

```json
    "active": "True",
			"type":"twilio",
			"account_sid":"myAccountSID",
			"auth_token":"MyAuthToken",
			"from_number":"MyTwilloNumber",
			"to_number":"MyMobileNumber",
			"pokemon":{
				"from_number":"MyTwilloNumber",
				"to_number":"MyMobileNumber",
				"message": "Panic! OMG!!!! <pkmn> has appeared! IV is <iv>. The closest address is:<address>.  Google:<gmaps>  Lat:<lat> Long:<lng> "
				}
},


```

## Troubleshooting Checklist
[ x ] Most recent version of PokemonGo-Map
[ x ] Most recent version of PokeAlarm
[ x ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Try a space between 'Google:' and <gmaps> and see if that fixes your problem. Seems like the  link works fine for me (once you remove the space).

**Comment by Calvinthesneak** [comment]
No dice... text is still the same.  It truncates the URL after the lat in the text message on the phone.  If I deliver to a computer it seems to be ok....

PS.  There is no space in the actual text message, I just placed in the thread above to try and show the issue.

![screenshot_20161113-160856](https://cloud.githubusercontent.com/assets/23301696/20250066/023e8bbc-a9bd-11e6-9ea7-33b7df4112be.PNG)

**Comment by kvangent** [comment]
It could be that whatever your SMS messenger is, it just doesn't parse URL's with commas in them correctly.  I would guess that to be the case since the link is working fine

**Comment by Calvinthesneak** [comment]
Yeah it definitely is the commas, but it doesn't work on two different android phones.  I'm digging through Twilio documentation to see if they have a string builder or something to get past the limitation...  I can easily enough manually check google maps, just was curious if there was a relatively painless solution or it could support something like a shortlink or html builder.

**Comment by kvangent** [comment]
I can confirm that it works fine on the Galaxy S5, S6, and S7. I would suggest a different SMS messenger as they vary between phones and carriers.
