### ISSUE TITLE
[ENHANCEMENT] Discord bot

### ISSUE THREAD

**Issue by evilmumi** [kvangent/PokeAlarm#271]
## Enhancement Description
The Bot could send information to an discord server / channel

## Use cases
so not everybody will posts his spawns just one bot

## Other Links
https://support.discordapp.com/hc/en-us/articles/212889058-Discord-s-Official-API
https://discordapp.com/developers/docs/reference
https://github.com/Rapptz/discord.py

**Comment by LogaRhythmus** [comment]
+1 I was thinking of that as well the past few days. Glad to see this.

**Comment by kvangent** [comment]
There is already a mega thread to request services.

The Discord endorsed python API is for Python 3, not Python 2 (which is what PokeAlarm is).
