### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by thepokemaster1** [kvangent/PokeAlarm#272]
## Problem Description
The problem is i am not able to nstall dependencies as part of step 2 of the installation. I cannot find the "pip install -r requirements.txt" 

## Your Environment

Operating System:  windows 10
Python Version: (use `python -V`)  2.7.12
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Pip is a command you run, the requirements.txt is a file located in the root of PokeAlarm.
