### ISSUE TITLE
[ENHANCEMENT] Send URL notifications to your map instead of to Google maps

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#273]
## Enhancement Description

Currently whenever a notification is triggered, it sends the URL for Google Maps which works great, but it would be even better if the URL for your own map was sent instead to provide context and have the nearby Pokémon, gyms, etc. relevant for that notification. I am not sure it will work on maps running with -fl -nsc though...

## Use cases

If you are running a map for several people, it looks nicer to get the Twitter/Telegram notifications to be sent to your own map instead of to generic Google Maps.

## Other Links

I discussed about it on Discord, received a suggestion like this:

```
                   #curl "http://192.168.1.33:5008/next_loc" -d lat=$lat -d lon=$lon
                   #requests.post("http://192.168.1.33:5008/next_loc",data={'lat':pkmn['latitude'],'lon':pkmn['longitude']})
```

However, due to my map running with -fl I don't seem to be able to pass URLs of the kind next_loc. I wonder if there is any other way to locate a specific point in your map without it needing to go "search" there.

**Comment by kvangent** [comment]
This is really a functionality for PokemonGo-Map, not PokeAlert. You would want PokemonGo-Map to take in some kind of lat lng from a url and center you there.

**Comment by Imoq** [comment]
It seems like it does take some kind of lat and lng but *only* if you are not running it with -fl

with fl:
```
[gonzalez@pyhome ~]$ curl "https://www.pogomars.com/next_loc" -d lat=43.283658 -d lon=5.375430
Location changes are turned off
[gonzalez@pyhome ~]$ 
```

without -fl
```
[gonzalez@pyhome ~]$ curl "https://www.pogomars.com/next_loc" -d lat=43.283658 -d lon=5.375430
{
  "lat": 43.283658, 
  "lng": 5.37543
}
[gonzalez@pyhome ~]$
```

So, I wonder if this is possible to change/add on PokeAlarm :)

(thanks for your work, btw! I've seen this very quiet lately! but Telegram + Twitter alerts still rock the world!)

**Comment by kvangent** [comment]
So using curl with `-d <data>` essentially sends a POST request with form data. This means it is not possible to replicate with just a URL.  You would need to change PokemonGO-Map to correctly interpret URL parameters.

**Comment by Imoq** [comment]
Umm... I thought that such functionality was already implemented on PokemonGO-Map but then I guess I was mistaken. I'll go poke on that side to see if I can get somebody's attention, but this would be indeed a great addition for the alerts. Thanks!

**Comment by midadami** [comment]
In case I already have it implemented on pokemongomap. What do I need to do to implement it on PokeAlarm?
I tried :

'loc': "[Haga click aqui para acceder al mapa pokemon](http://xxxxxxxxx.txyz/?lat=<lat>&lon=<lng>)"

alert['loc'] = settings.get('loc', default['loc'])

and when the data is sent I created another message with it since I need another parse mode:

args ={
                'chat_id': alert['chat_id'],
                'text': replace(alert['loc'], info),
                'parse_mode': 'Markdown',
                'disable_web_page_preview': 'True',
                'disable_notification': 'False'
            }
            try_sending(log, self.connect, "Telegram", self.client.sendMessage, args)

It compiles alright but when running:

Traceback (most recent call last):
  File "runwebhook.py", line 93, in <module>
    alarm_thread = Alarm_Manager()
  File "E:\Radar_Pokemon\PokeAlarm\alarms\alarm_manager.py", line 55, in __init__
    self.alarms.append(Telegram_Alarm(alarm))
  File "E:\Radar_Pokemon\PokeAlarm\alarms\Telegram\telegram_alarm.py", line 50, in __init__
    self.pokestop = self.set_alert(settings.get('pokestop', {}), self._defaults['pokestop'])
  File "E:\Radar_Pokemon\PokeAlarm\alarms\Telegram\telegram_alarm.py", line 71, in set_alert
    alert['loc'] = settings.get('loc', default['loc'])
KeyError: 'loc'

**Comment by Imoq** [comment]
@kvangent as you can see here: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1592 it's just a matter to add few lines to the map for it to work. Tested with -fl -nsc and works like a charm.

I believe midadami already made some efforts to make it work on Telegram, I'll try to add them tomorrow to my own notifications but I imagine it shouldn't be terribly hard for you to provide the option to either be sent to Google or to own custom map on any notifications (Twitter, Slack, Telegram, etc.)

Thanks!

**Comment by kvangent** [comment]
@Imoq Since lat and long are part of dynamic text, is there any reason you can't implement this with the way PokeAlarm is right now? Just put `http://yoururl.com/?lat=<lat>&lon=<lng>` in the appropriate field?

**Comment by midadami** [comment]
@kvangent yes its very easy, but you just have to create a new message (cant use title or body) since you need another parse mode so it will appears as an link.

**Comment by Imoq** [comment]
In the case of Twitter it was easy enough just as you said, for sure. On Telegram, I believe @midadami didn't want both the Google minimap and the own map's link to appear. For me it wasn't an issue, so I just added the map's URL (with lat/lng) and I just have both for Telegram.

Thank you both!

**Comment by midadami** [comment]
No, the reason I had to create another message with another parse mode its becuase I want it to be a hyperlink not just a link. What I mean is that I want the text: "click here to access map" and if you click you, you access the url.

**Comment by kvangent** [comment]
@midadami It works with google maps links, why wouldn't it work with another url?

**Comment by midadami** [comment]
I actually havent looked how the google map link is done haha but yes I guess its the same. I just created another message as it seemed easier.

**Comment by Imoq** [comment]
Thank you very much @kvangent for submitting a PR, it was merged to the map repo now. I guess we can close this one unless you want to track any further work in here. You rock!

**Comment by danwie** [comment]
I guess I'm late to the party. I'm using a fresh version of  PokemonGo-Map and PokeAlarm. I still get Google Maps links. What argument do I need to add to get links to my own domain?

**Comment by Imoq** [comment]
Just put http://yoururl.com/?lat=<lat>&lon=<lng> in the appropriate field :)
