### ISSUE TITLE
[ENHANCEMENT] Send notifacation about captchas

### ISSUE THREAD

**Issue by spammer23** [kvangent/PokeAlarm#275]
## Enhancement Description

Support a PR from PokemonGo-Map: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1567
When the Map discovers that one account needs a captcha, send out a message about it, or better: send out the [link](http://pgorelease.nianticlabs.com/) where to solve the captcha.

## Use cases

It make it easier to solve some captchas when you are on a walk to catch some Pokemon

**Comment by jaggles** [comment]
This would be a **_fantastic_** enhancement.

**Comment by kvangent** [comment]
In order for PokeAlarm to do this, it would first need PokemonGo-Map to send the webhook.

**Comment by sLoPPydrive** [comment]
PR #1567 does already send the webhook but it does it in a way currently unsupported by PokeAlarm (and IMHO with too few information). I enhanced the PR to send more information about captchas and I adapted PokeAlarm to read them (only Telegram currently). The result is something like this:

![image](https://cloud.githubusercontent.com/assets/3931865/20700636/ccf8416a-b60e-11e6-800f-73e0b0060e22.png)

Check out my forks of PokemonGo-Map (branch PR_MIX_7) and PokeAlarm (branch DEBUG) to get the code.

**Comment by spammer23** [comment]
That's what i mean :)

**Comment by JoniValles** [comment]
@sLoPPydrive I'm trying to use your Pokealarm webhook for captchas to send the url to my friends but i don't know how to use it. Can you help? Thanks in advance!

**Comment by kvangent** [comment]
If we can get some pressure on PokemonGo-Map to add some form of manual captcha (preferably with the webhook), I would love to get this feature added.

**Comment by kvangent** [comment]
Closing this, please use the following instead: #297
