### ISSUE TITLE
[ENHANCEMENT] Ditto Notification

### ISSUE THREAD

**Issue by satrox28** [kvangent/PokeAlarm#277]
Is it possible to get ditto notification

## Problem Description

[USER SPECIFIC]
Since ditto is introduced recently, is it possible to get notified via telegram.

## Your Environment

Operating System:  
Python Version: (use `python -V`)  
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

## Enhancement Description

Since ditto is introduced recently, is it possible to get notified via telegram.

**Comment by kvangent** [comment]
From what I understand, Ditto shows the same on scanners and so there is no way to tell them apart.
