### ISSUE TITLE
[ENHANCEMENT] Update location via "send location" from Telegram (other services)

### ISSUE THREAD

**Issue by spammer23** [kvangent/PokeAlarm#278]
## Enhancement Description

Update the scan location via "send location" in Telegramm.
maybe using this: 
_A post request /location/?location=<name or lat,lng> will return the updated location and status 200._

## Use cases

Update the location when you are on a walk

**Comment by kvangent** [comment]
There is already an API hook in place for this. See https://github.com/kvangent/PokeAlarm/wiki/PokeAlarm-API#update-location

**Comment by spammer23** [comment]
I know this, i wrote it in my text?
The question is, is it possible to send the bot in the chat a location and the bot interprets it and set the new location. (https://www.youtube.com/watch?v=6lQVkQGm4aU)

**Comment by kvangent** [comment]
You cannot. PokeAlarm does not change PokemonGo-Map, only receives info from it.

**Comment by spammer23** [comment]
@kvangent i have the url to change the location:

curl "http://localhost:5000/next_loc?lat=${lat}&lon=${lon}" -X POST
where lat and lon is the variables containing the the latitude & longitude, respectively..

if you like you can implement it.
