### ISSUE TITLE
[USER SPECIFIC] Float Latitude Longitude Co-Ordinates

### ISSUE THREAD

**Issue by satrox28** [kvangent/PokeAlarm#279]
## Problem Description

Currentlly I am receiving co-ordinates notification with long numbers like  1.xxxxxxxxxxxxxxxxx, 103.xxxxxxxxxxxxxx
Is it possible to restrict 4 or 6 decimals.
## Your Environment

Operating System:  
Python Version: (use `python -V`)  
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
There is no conventional way to do this, but you can edit the code. Find the alarm_manager.py file and change lines 215-216 to look like this:
```
			'lat' : "{:.4f}".format(repr(lat)),
			'lng' : "{:.4f}".format(repr(lng)),
```

**Comment by satrox28** [comment]
2016-12-01 06:43:02,052 [     alarm_manager] [  ERROR] Error while processing request: Unknown format code 'f' for object of type 'str'


iam getting error

**Comment by kvangent** [comment]
Try the following:
```
			'lat' : "{:.4f}".format(float(lat)),
			'lng' : "{:.4f}".format(float(lng)),
```

**Comment by satrox28** [comment]
thanks,its working now. :)
