### ISSUE TITLE
[Enhancement] Add Address to notification

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#28]
For example, "Dragonite at 1600 Pennsylvania Ave, 20500 until 5:00pm (13m 30s)."  This way we can  gauge the location of the pokemon before tapping on the map link.

**Comment by kvangent** [comment]
This is on the todo list.

**Comment by reme-dy** [comment]
Thanks and great job!  Your notifier is helping a lot! :)

**Comment by reme-dy** [comment]
@kvangent, perhaps the geocoder package can help?  Here's a snippet on how to reverse geocode a set of lat and lon, in this case it's the White House (1600 Pennsylvania Ave NW, 20500):

`import geocoder`
`g = geocoder.google([38.8977,-77.0365], method='reverse')`
`print g.housenumber + " " + g.street + ", " + g.postal`

I'm a newb at python so it'd take me a really long time to go through your code and add it.  Hope this helps.

**Comment by kvangent** [comment]
This feature has now been added. Please see the Alarm Configuration page of the wiki for more information.

**Comment by reme-dy** [comment]
Thanks @kvangent.  I implemented geocoder into your code the other day and noticed some of the pokemon in my area had locations (housenumber and street) that geocoder couldn't resolve, instead returning 'None'.  The postal code was fine though.  Perhaps you should add the postal code as well, otherwise you might see "Zubat at None None".

There's also another package called geopy that has additional keys for extra address fanciness.  So 38.8977,-77.0365 will resolve to White House, 1600, Pennsylvania Ave Northwest, Monumental Core, Washington, District of Columbia, 20500, United States of America.  It's a little more work to pull out all the keys and you might need an API.
