### ISSUE TITLE
[ENHANCEMENT] Send notifications to Facebook page (not profile, not messenger)

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#283]
## Enhancement Description

I looked and noticed that last August somebody proposed to send notifications to Facebook messenger but it was dismissed because the restrictions with the messenger API. I've been using notifications over Twitter and Telegram but some of the users are still stuck to Facebook. Please notice I'm not talking about a Facebook profile posting (although some people would like that), but for a Facebook page.

Even if I have setup a Facebook page that syncs from Twitter and receives the notifications from there, it still has the 143 characters restriction from Twitter, as opposed (for example) as having beautiful stickers in Telegram (which could be replaced with images in Facebook), complete addresses for the pop, link to custom map + Google maps direction, etc.

I took a look at Facebook pages API page: https://developers.facebook.com/docs/pages/publishing

Do you think it could be implemented? Thanks! :)

## Use cases

Described above!

## Other Links

Facebook pages API: https://developers.facebook.com/docs/pages/publishing

**Comment by kvangent** [comment]
So the problem with Facebook is that they have tight control over who they let have api keys. The last time I took a look it it, you had to go through a special process to get an API key and had to be specially approved to develop an app with them. You can check out the links here (https://developers.facebook.com/docs/pages/getting-started#developer-account) and let me know if you can get an API key quickly or not.

**Comment by Imoq** [comment]
Registered and immediately got a "You have successfully registered as a Facebook Developer. You can now add Facebook into your app or website." message.

Now I have the option to:

> Add a New App
> Select a platform to get started

**Comment by Imoq** [comment]
Now I created a new App and got an ID (obfuscated last numbers because forum is public):

APP ID: 31374203902XXXX

**Comment by kvangent** [comment]
Ok, I'm not making any promises, but if I get some free time next week I'll take a look and see what I can do.

**Comment by Imoq** [comment]
You rock, thank you!

**Comment by mikemikemikecoc** [comment]
i have created a new branch on my machine that writes to 19 my 19 FB pages successfully using the permanent page API key.  i'll try to create a PR tonight or tomorrow for it as soon as I figure how to do it.  lol

**Comment by Imoq** [comment]
Thank you! This would be great! :)

**Comment by hokiepokedad** [comment]
@Imoq I have submitted my first PR with facebook pages support #286 . Hopefully I did it right.

**Comment by Imoq** [comment]
Thanks you both! I'll try to test it tonight, would be great to send notifications directly to FB instead of having to to to Twitter -> FB! Then I'll see if an image can be sent along (or referenced somehow) but that will be something to think about for later :)

I'll come back with feedback, thanks a bunch!

**Comment by hokiepokedad** [comment]
Using the "link" field, you _could_ use that as an additional text field to include both maps and images.

**Comment by Imoq** [comment]
It's done on #286 ! So great, thanks a lot, @hokiepokedad ! I hope this get merged soon.

**Comment by kvangent** [comment]
I'm going to leave this and that PR open for a few days so others can try it before I pull it.

**Comment by kvangent** [comment]
Merged as of bc3b6f50ab81dbca1abbcedf637ac644ea461296.
