### ISSUE TITLE
[ENHANCEMENT] Handle multiple webhooks with multiple chatID

### ISSUE THREAD

**Issue by bbdoc** [kvangent/PokeAlarm#289]
## Enhancement Description

Would be very useful if we could have the possibility to have PokeAlarm listening on multiple webhooks at the same time, and link those different webhooks to different ChatID. 

## Use cases

This would allow people running multiple instances of the map to assign a webhook to each map, and have a single instance of PokeAlarm running and distributing alarms to different Chat Rooms for different maps. At the moment, only way to achieve this is to run one instance of PokeAlarm per webhook, which is quite painful especially when running on docker as it means multiple docker containers.

**Comment by kvangent** [comment]
You can add multiple alarms of the same type per instance of PokeAlarm. So you could have 5 different Slack channels all working at the same time.

If I ever get around to developing for this project again, I plan to allows multiple threads running on a single listening port.

**Comment by bbdoc** [comment]
@kvangent Yes I can indeed do that, but how do I get each of those instance listening to a different port ? Port setting is global and not linked to the type of alarm. Maybe I missed Something but if I run different instances of the map, how do I get PokeAlarm to send alarms to different channels, one per instance of the map ?

**Comment by kvangent** [comment]
You can change it in the command line with `-P PORT` and specify the alarms.json file with `-c CONFIG`.

**Comment by bbdoc** [comment]
Yes that's what I'm currently doing, but then I come back to having to launch multiple instance of PokeAlarm. A listening port setting at the channel level would allow to create multiple channels from only one instance of PokeAlarm.

**Comment by kvangent** [comment]
I guess I don't understand what you are asking for. Do you want to send the same notifications to multiple different channels?

**Comment by bbdoc** [comment]
No. I have 3 different instances of the map running, one per city. Currently each of those has a webhook set to a different port (4000, 4001, 4002). I have created 3 different Telegram Channels, one per city, so I'm running 3 instances of PokeAlarm, one per port, in order to redistribute alerts for each port to the right channel.

What I'm looking for is a possibility to do that with only one instance of PokeAlarm. Something like this : 

```
{
    "active": "False",
    "type":"telegram",
    "bot_token":"YOUR_BOT_TOKEN",
    "chat_id":"YOUR_CHAT_ID",
    **"listening_port":"4001"**
}
```

**Comment by kvangent** [comment]
Essentially, that would be impossible without massively restructuring PokeAlarm. 

You could configure 3 PokeAlarms instances to run in 1 docker though.

**Comment by bbdoc** [comment]
OK I understand. Btw another method would be to allow parameter such as -st and lat,long at the channel level, so it would filter pokemons found on the right area per channel matching with map launch parameters ;-)

How can I get 3 instances of PokeAlarm to run in 1 docker ? Have been looking for this already but I have not been successfull achieving it. Thanks
