### ISSUE TITLE
[Feature Request] Simplify geofencing usage for multiple geofences per thread and webhook

### ISSUE THREAD

**Issue by Arengo** [kvangent/PokeAlarm#292]
## Problem Description

When you would like to divide between multiple areas on one alarm list you need the same number of multiple webhooks and PokeAlarm thread. Instead there could be a multiple geofencing configuration that divides between areas where each is named.

## Current state
In the wiki it is written, and it is actual practice that we can only use one geofence file and have to manually state the name of this location in the alarms.json if we want it to be displayed in the resulting message. Also the numbers of webhooks and threads needed for an example cross cities 100% IV channel is really high.

## Possible solution
Modify the code to read multiple geofences out of one geofence.txt file and add a name which is also parsed and stored as a <geoloc>. The structure of the geofence.txt could be like below while ``geloc1``and ``geoloc2``are the names of the geofences which will be parsed.

```
[geoloc1]
lat11,lon11   
lat12,lon12
...

[geoloc2]
lat21,lon21
lat22,lon22
...
```

When a Pokémon is triggering an alarm, the distance is calculated, additionally the geofence of it's location is determined and the geloc name is parsed.

This will result in an easier handling of above mentioned problems and reduce the webhooks and threads needed by far.

**Comment by kvangent** [comment]
This has been implemented in v3, in the format you suggested.

Let me know if you have any problems with it.
