### ISSUE TITLE
[ENHANCEMENT] Round IV %

### ISSUE THREAD

**Issue by georgeherby1994** [kvangent/PokeAlarm#300]
## Enhancement Description
At present when using <iv> in Discord. It comes through at 97.89% this takes up valuable space on the line and really doesnt matter. Could we have a <ivr> IV rounded.

## Use cases
At present in Discord putting this the name and the (att,def,sta) mean its just overflows and displays as ... on the end. If the IV was just 98 instead of 97.89 it wouldn't overflow

**Comment by kvangent** [comment]
Would you rather have a setting to give the number of decimal points, or do you think changing it to round to 1 decimal point would be enough?

**Comment by georgeherby1994** [comment]
Option to have different number would be great. As I know i want no decimals places. but some people would want it at 1 and some at 2.

**Comment by georgeherby1994** [comment]
As a temporary fix for my specific user case i change the following line in alarm_manager.py
`'iv': "%.2f" % iv,`
to
`'iv': int(round(iv)),`

**Comment by kvangent** [comment]
This is complete as of https://github.com/kvangent/PokeAlarm/commit/d3004eeeff82407c3ae4330a51e4386b905a56b9. You can use `<iv_0>` for 0 points of precision or `<iv_2>` for 2 points of precision (`<iv>` will still give 1 point of precision).
