### ISSUE TITLE
[Enhancement] Don't send notifications when iv's are unknown

### ISSUE THREAD

**Issue by daangroot** [kvangent/PokeAlarm#303]
Sometimes rocketmap fails in reading the iv's and marks the iv value as unknown.
Therefore it would be nice if we can choose for every pokemon if a notification should be send when the iv's are unkown. Hope you will implement it. :)

**Comment by kvangent** [comment]
@daangroot Please stick to using the issue template in the future.

**Comment by kvangent** [comment]
This is complete as of https://github.com/kvangent/PokeAlarm/commit/eb0eb3dbd55e431d871187447c9df51dd13c72df. You can use "ignore_missing" in the filters.json to ignore pokemon without moves or ivs.
