### ISSUE TITLE
[BUGUSER SPECIFIC] update to last build. Now I have after starting an error

### ISSUE THREAD

**Issue by DragonHeart69** [kvangent/PokeAlarm#304]
## Problem Description
If I get the following error pokealarm start
Process manager_0:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\gipc\gipc.py", line 361, in _child
    target(*args, **kwargs)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 110, in run
    self.intialize_process()
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 104, in intialize_process
    self.create_alarms(self.__alarms_file)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 612, in create_alarms
    alarm_settings = json.load(f)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 18 column 2 (char 602)

## Your Environment
Operating System : Windows 10 (last inside build) 
Python Version : 2.7.12  

Did the issue persist after restarting the script yesno

## Console Output
Process manager_0:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\gipc\gipc.py", line 361, in _child
    target(*args, **kwargs)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 110, in run
    self.intialize_process()
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 104, in intialize_process
    self.create_alarms(self.__alarms_file)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 612, in create_alarms
    alarm_settings = json.load(f)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 18 column 2 (char 602)

## Your Alarms Config

alarm.json
    [
  {
    "active": "False",
    "type": "boxcar",
    "user_credentials": "YOUR_API_KEY"
  },
  {
    "active": "True",
    "type": "discord",
    "api_key": "https://discordapp.com/api/webhooks/+++",
	"startup_message": "True",
	"startup_list": "True",
	"pokemon":{
		"username": "<pkmn>",
		"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
		"title": "<pkmn> beschikbaar. <move1>/<move2> (<iv>% - <atk>/<def>/<sta>)",
		"body": "Beschikbaar tot <24h_time> (<time_left>)",
	},
		"pokestop":{
        "username": "Pokestop",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/pokestop.png",
        "title": "Someone has placed a lure on a Pokestop!",
        "url": "<gmaps>",
        "body": "Lure will expire at <24h_time> (<time_left>)."
    },
    "gym":{
        "username": "Pokemon Gym",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/gym.png",
        "title": "A Team <old_team> gym has fallen!",
        "url": "<gmaps>",
        "body": "It is now controlled by <new_team>."
    },
  },
  {
    "active": "False",
    "type": "facebook_page",
    "page_access_token": "YOUR_PAGE_ACCESS_TOKEN"
  },
  {
    "active": "False",
    "type": "pushbullet",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "pushover",
    "app_token": "YOUR_APP_TOKEN",
    "user_key": "YOUR_USER_KEY"
  },
  {
    "active": "False",
    "type": "slack",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "telegram",
    "bot_token": "YOUR_BOT_TOKEN",
    "chat_id": "YOUR_CHAT_ID"
  },
  {
    "active": "False",
    "type": "twilio",
    "account_sid": "YOUR_API_KEY",
    "auth_token": "YOUR_AUTH_TOKEN",
    "from_number": "YOUR_FROM_NUM",
    "to_number": "YOUR_TO_NUM"
  },
  {
    "active": "False",
    "type": "twitter",
    "access_token": "YOUR_ACCESS_TOKEN",
    "access_secret": "YOUR_ACCESS_SECRET",
    "consumer_key": "YOUR_CONSUMER_KEY",
    "consumer_secret": "YOUR_CONSUMER_SECRET"
  }
]

& my filters.json

{
    "gyms":{
		"enabled":"True",
		"ignore_neutral":"False",
		"min_dist":"0",
		"max_dist":"20000",
        "Valor":"True",
        "Mystic":"True",
        "Instinct":"True"
    },
    "pokestops":{
		"enabled":"True",
        "min_dist":"0",
        "max_dist":"20000"
    },
    "pokemon":{
		"enabled":"True",
        "min_dist":"0",
        "max_dist":"20000",
        "min_iv":"0",
        "max_iv":"100",
        "Bulbasaur":"True",
        "Ivysaur":"True",
        "Venusaur":"True",
        "Charmander":"True",
        "Charmeleon":"True",
        "Charizard":"True",
        "Squirtle":"True",
        "Wartortle":"True",
        "Blastoise":"True",
        "Caterpie":"False",
        "Metapod":"False",
        "Butterfree":"False",
        "Weedle":"False",
        "Kakuna":"False",
        "Beedrill":"False",
        "Pidgey":"False",
        "Pidgeotto":"False",
        "Pidgeot":"False",
        "Rattata":"False",
        "Raticate":"False",
        "Spearow":"False",
        "Fearow":"False",
        "Ekans":"True",
        "Arbok":"True",
        "Pikachu":"True",
        "Raichu":"True",
        "Sandshrew":"True",
        "Sandslash":"True",
        "Nidoran♀":"True",
        "Nidorina":"True",
        "Nidoqueen":"True",
        "Nidoran♂":"True",
        "Nidorino":"True",
        "Nidoking":"True",
        "Clefairy":"True",
        "Clefable":"True",
        "Vulpix":"True",
        "Ninetales":"True",
        "Jigglypuff":"False",
        "Wigglytuff":"False",
        "Zubat":"False",
        "Golbat":"False",
        "Oddish":"False",
        "Gloom":"False",
        "Vileplume":"False",
        "Paras":"False",
        "Parasect":"False",
        "Venonat":"False",
        "Venomoth":"False",
        "Diglett":"True",
        "Dugtrio":"True",
        "Meowth":"False",
        "Persian":"False",
        "Psyduck":"False",
        "Golduck":"False",
        "Mankey":"True",
        "Primeape":"True",
        "Growlithe":"True",
        "Arcanine":"True",
        "Poliwag":"False",
        "Poliwhirl":"False",
        "Poliwrath":"False",
        "Abra":"True",
        "Kadabra":"True",
        "Alakazam":"True",
        "Machop":"True",
        "Machoke":"True",
        "Machamp":"True",
        "Bellsprout":"True",
        "Weepinbell":"True",
        "Victreebel":"True",
        "Tentacool":"False",
        "Tentacruel":"False",
        "Geodude":"True",
        "Graveler":"True",
        "Golem":"True",
        "Ponyta":"True",
        "Rapidash":"True",
        "Slowpoke":"False",
        "Slowbro":"False",
        "Magnemite":"False",
        "Magneton":"False",
        "Farfetch'd":"True",
        "Doduo":"True",
        "Dodrio":"True",
        "Seel":"False",
        "Dewgong":"False",
        "Grimer":"True",
        "Muk":"True",
        "Shellder":"False",
        "Cloyster":"False",
        "Gastly":"False",
        "Haunter":"False",
        "Gengar":"False",
        "Onix":"True",
        "Drowzee":"False",
        "Hypno":"False",
        "Krabby":"False",
        "Kingler":"False",
        "Voltorb":"False",
        "Electrode":"False",
        "Exeggcute":"True",
        "Exeggutor":"True",
        "Cubone":"False",
        "Marowak":"False",
        "Hitmonlee":"True",
        "Hitmonchan":"True",
        "Lickitung":"False",
        "Koffing":"False",
        "Weezing":"False",
        "Rhyhorn":"False",
        "Rhydon":"True",
        "Chansey":"True",
        "Tangela":"True",
        "Kangaskhan":"True",
        "Horsea":"False",
        "Seadra":"False",
        "Goldeen":"False",
        "Seaking":"False",
        "Staryu":"False",
        "Starmie":"False",
        "Mr. Mime":"False",
        "Scyther":"False",
        "Jynx":"False",
        "Electabuzz":"False",
        "Magmar":"False",
        "Pinsir":"True",
        "Tauros":"True",
        "Magikarp":"False",
        "Gyarados":"True",
        "Lapras":"True",
        "Ditto":"False",
        "Eevee":"False",
        "Vaporeon":"False",
        "Jolteon":"False",
        "Flareon":"False",
        "Porygon":"True",
        "Omanyte":"False",
        "Omastar":"True",
        "Kabuto":"False",
        "Kabutops":"True",
        "Aerodactyl":"True",
        "Snorlax":"True",
        "Articuno":"True",
        "Zapdos":"True",
        "Moltres":"True",
        "Dratini":"False",
        "Dragonair":"False",
        "Dragonite":"True",
        "Mewtwo":"True",
        "Mew":"True"
    }
}

## Troubleshooting Checklist
[*] Most recent version of PokemonGo-Map
[*] Most recent version of PokeAlarm
[*] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
This is a json error in your Alarms.json file. You can copy and paste it into a site like http://www.jsoneditoronline.org/ to find errors.

In this case, you have an extra coma after this line `"body": "Beschikbaar tot <24h_time> (<time_left>)",`
