### ISSUE TITLE
[BUGUSER SPECIFIC] startup Facebook page

### ISSUE THREAD

**Issue by DragonHeart69** [kvangent/PokeAlarm#305]
## Problem Description
Now i'm true to activate pokealarm on a facebook page. I create a page, i create a app & create a long live token.

## Your Environment
Operating System  :windows 10
Python Version : 2.7.12 

## Console Output
Process manager_0:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\gipc\gipc.py", line 361, in _child
    target(*args, **kwargs)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 110, in run
    self.intialize_process()
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 104, in intialize_process
    self.create_alarms(self.__alarms_file)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\Manager.py", line 622, in create_alarms
    from FacebookPage import FacebookPageAlarm
  File "C:\Python27\lib\site-packages\gevent\builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\FacebookPage\__init__.py", line 7, in <module>
    from FacebookPageAlarm import FacebookPageAlarm
  File "C:\Python27\lib\site-packages\gevent\builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "H:\PokemonGo-Maps\Poperinge\PokeAlarm\PokeAlarm\FacebookPage\FacebookPageAlarm.py", line 8, in <module>
    from ..Utils import parse_boolean, get_timestamps
ImportError: cannot import name get_timestamps

## Your Alarms Config
alarm.json
[
  {
    "active": "False",
    "type": "boxcar",
    "user_credentials": "YOUR_API_KEY"
  },
  {
    "active": "True",
    "type": "discord",
    "api_key": "https://discordapp.com/api/webhooks/+++",
	"startup_message": "True",
	"startup_list": "True",
	"pokemon":{
		"username": "<pkmn>",
		"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
		"title": "<pkmn> beschikbaar. IV: <iv>% - <atk>/<def>/<sta>",
		"body": "Beschikbaar tot <24h_time> (<time_left>)"
	},
		"pokestop":{
        "username": "Pokestop",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/pokestop.png",
        "title": "Iemand plaatste een lure aan een Pokestop!",
        "url": "<gmaps>",
        "body": "Deze verdwijnt om <24h_time> (<time_left>)."
    },
    "gym":{
        "username": "Pokemon Gym",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/gym.png",
        "title": "Een gym van team <old_team> is gevallen!",
        "url": "<gmaps>",
        "body": "Deze word nu beheerd door <new_team>!"
    }
  },
  {
    "active": "True",
    "type": "facebook_page",
    "page_access_token": "+++",
	"startup_message":"True",
	"startup_list":"True",
	"pokemon":{
		"message": "<pkmn> beschikbaar. IV: <iv>% - <atk>/<def>/<sta>",
		"link": "<gmaps>"
	},
		"pokestop":{
        "username": "Pokestop",
        "message": "Iemand plaatste een lure aan een Pokestop! Deze verdwijnt om <24h_time> (<time_left>).",
        "link": "<gmaps>"
    },
    "gym":{
        "username": "Pokemon Gym",
        "message": "Een gym van team <old_team> is gevallen! Deze word nu beheerd door <new_team>!",
        "link": "<gmaps>"
    }
  },
  {
    "active": "False",
    "type": "pushbullet",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "pushover",
    "app_token": "YOUR_APP_TOKEN",
    "user_key": "YOUR_USER_KEY"
  },
  {
    "active": "False",
    "type": "slack",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "True",
    "type": "telegram",
    "bot_token": "+++",
    "chat_id": "@MonsterVanger",
	"venue":"True",
	"startup_message":"True",
	"startup_list":"True",
	"pokemon":{
		"username":"<pkmn>",
		"title":"<pkmn> beschikbaar. IV: <iv>% - <atk>/<def>/<sta>",
		"body":"Beschikbaar tot <24h_time> (<time_left>)"
	},
		"pokestop":{
        "username": "Pokestop",
        "title": "Iemand plaatste een lure aan een Pokestop!",
        "body": "Deze verdwijnt om <24h_time> (<time_left>)."
    },
    "gym":{
        "username": "Pokemon Gym",
        "title": "Een gym van team <old_team> is gevallen!",
        "body": "Deze word nu beheerd door <new_team>!"
    }
  },
  {
    "active": "False",
    "type": "twilio",
    "account_sid": "YOUR_API_KEY",
    "auth_token": "YOUR_AUTH_TOKEN",
    "from_number": "YOUR_FROM_NUM",
    "to_number": "YOUR_TO_NUM"
  },
  {
    "active": "False",
    "type": "twitter",
    "access_token": "YOUR_ACCESS_TOKEN",
    "access_secret": "YOUR_ACCESS_SECRET",
    "consumer_key": "YOUR_CONSUMER_KEY",
    "consumer_secret": "YOUR_CONSUMER_SECRET"
  }
]

## Troubleshooting Checklist
[*] Most recent version of PokemonGo-Map
[*] Most recent version of PokeAlarm
[*] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Please make sure you update PokeAlarm. This issue was fixed a few days ago.
