### ISSUE TITLE
[Enhancement] Add pokemon weight

### ISSUE THREAD

**Issue by evilmoses** [kvangent/PokeAlarm#307]
## Enhancement Description
Add ability to filter on pokemon weight.

## Use cases
In order to help those trying to complete the tiny rat / big karp badges,

**Comment by kvangent** [comment]
As far as I know, RocketMap doesn't send this information in the webhook.

**Comment by Aethios** [comment]
Could we get something similar for genders? If breeding is going to be added soon, finding breeding pairs will be very useful.

**Comment by kvangent** [comment]
@Aethios voice your support for it here https://github.com/RocketMap/RocketMap/pull/1828

**Comment by onilton** [comment]
#1828 is merged now

**Comment by onilton** [comment]
@kvangent this can be closed, I think ;)
