### ISSUE TITLE
[BUG] Discord not always showing the map.

### ISSUE THREAD

**Issue by dikkedeur** [kvangent/PokeAlarm#308]
## [BUGUSER SPECIFIC] : 
When a pokemon is found and send to the discord channel, in roughly 25% of the cases it doesnt sent the image of the map with it.
you can clearly see it in this picture

![schermafbeelding 2017-02-15 om 13 42 59](https://cloud.githubusercontent.com/assets/11842306/22975236/418c5a48-f386-11e6-9924-e27525e9f109.png)

## Your Environment
Operating System  : Ubuntu server 16.04 LTS
Python Version (use `python -V`)  : Python 2.7.12

Did the issue persist after restarting the script: No, it is random.

## Console Output

```
	no console output, its not pokemon specific and totally random.
```

## Your Alarms Config
!--- Please post the config for your alarms in the space below --
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```json
    {
    "active": "True",
    "type": "discord",
    "api_key": "API_KEY_OLÉ",
    "startup_message":"True",
    "startup_list":"True",
    "pokemon":{
        "username":"<pkmn>",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<pkmn_id>.png",
        "title":"Een <pkmn> is gespot!",
        "url":"<gmaps>",
        "body": "Actief tot <24h_time> (<time_left>)."
    },
    "pokestop":{
        "username":"Pokestop",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/pokestop.png",
        "title":"Someone has placed a lure on a Pokestop!",
        "url":"<gmaps>",
        "body":"Lure will expire at <24h_time> (<time_left>)."
    },
 "gym":{
        "username":"Pokemon Gym",
        "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/gym.png",
        "title":"Een  <old_team> gym is verwoest!",
        "url":"<gmaps>",
        "body": "<new_team> is nu de nieuwe eigenaar."
    } 
  },
```

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x ] Most recent version of PokeAlarm
[ x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Are you using a google api key ?

**Comment by dikkedeur** [comment]
ahhhh, thats propably it why it doesnt sent always, will check it out and report back if that works better

**Comment by dikkedeur** [comment]
nop thats not it, 

![schermafbeelding 2017-02-15 om 14 03 28](https://cloud.githubusercontent.com/assets/11842306/22975628/b5e85742-f387-11e6-92d7-5408be54755c.png)

**Comment by kvangent** [comment]
Are you sure that you have google static maps enabled on your key?

https://github.com/kvangent/PokeAlarm/wiki/Google-Maps-API-Key

**Comment by dikkedeur** [comment]
wauw, it works again, strange that it was sometimes working and sometimes not. but it seems that its now okay, thanks!!!
made a new Api key just in case..

**Comment by Plotin** [comment]
I currently have the same problem, maps sometimes will get included, but more often not. I am using an API Key with the "-k" option and it is configured to allow static maps. I only use it with PokeAlarm, Rocketmap has another key. On Google API Manager, I see that requests to static maps API are made and none have errors, but the maps do not get included in the Discord messages.

**Comment by kvangent** [comment]
@Plotin So I have noticed that sometimes discord is extermely slow with loading of maps, particularly if you are sending alot. Are you sure that they aren't showing up at all, or could it be they get stuck in a loading state?

**Comment by Plotin** [comment]
@kvangent There seems to be something in the message, when I first switch to the alarms in the discord app, it seems to be trying to load the map but it fails. Looks like in the screenshots while trying and after...

![discord1](https://cloud.githubusercontent.com/assets/635837/23332016/8d49b53c-fb71-11e6-8b40-3d96702e588a.JPG)
![discord2](https://cloud.githubusercontent.com/assets/635837/23332019/9348b8de-fb71-11e6-8fac-472ecefe28b3.jpg)
