### ISSUE TITLE
Only notify within geofence / distance from a point?

### ISSUE THREAD

**Issue by brettgus** [kvangent/PokeAlarm#32]
I have my PokemonGo-Map workers covering the area of a whole city.  However, I'd only like to get notifications near where I am.  Any plans to make a setting for something like this?

**Comment by kvangent** [comment]
Yes. 

For right now, you can just limit the workers covering the area you are interested in by only adding the webhook those instances.

**Comment by brettgus** [comment]
Yeah, that's what I'm doing for now (posting to separate pushbullet channels), but it can be hassle to try to segregate the workers out.

**Comment by kvangent** [comment]
This feature is now added. See the Pokemon Configuration page of the wiki for more details.
