### ISSUE TITLE
[ENHANCEMENT] Support for sending sightings from different cities to separate webhooks.

### ISSUE THREAD

**Issue by Aethios** [kvangent/PokeAlarm#320]
## Enhancement Description
I have a Discord server which is receiving notifications from PokeAlarm, but it would be nice if I could separate sightings from different cities into their own channels.

## Use cases
This would allow people who live in city A but feel that city B is too far away to ignore channel B and still use the service without getting spammed.

**Comment by kvangent** [comment]
You can already do this. 

You can create different managers, and customize alarms.json for have the correct webhook for each one. Each manager can be limited by either distance around a certain location or a geofence.
