### ISSUE TITLE
[BUG] PokeAlarm does not format the <dist> strings correctly

### ISSUE THREAD

**Issue by dripdropper** [kvangent/PokeAlarm#324]
## Problem Description
PokeAlarm does not format the `<dist>` strings correctly.  There are some simple typo bugs in Utils.py :: get_dist_as_str().
1. The "if config['UNITS'] == 'imperial':" block has the code that should be in the "else:  # Metric" block and vice versa.
2.  The abbreviations for the imperial units should be "mi" (miles) and "yd" (yards), not km and m.

## Your Environment
The bug is in the code for all environments

## Console Output
Not relevant.

## Your Alarms Config
Not relevant.

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Thanks for find this. Should be corrected in a1815ea70e51805add5f7537ccb09fa851b9ff1f.

**Comment by dripdropper** [comment]
I don't think it's completely fixed yet.  It looks like you also need to change the two distance checks.  Here is some pseudocode:
if dist > **1760** yards, output = (dist / 1760) mi, else ...
if dist > **1000** meters, output = (dist / 1000) km, else ...
