### ISSUE TITLE
[Feature Request] Using geofence names as dynamic text substitution for alarms

### ISSUE THREAD

**Issue by Arengo** [kvangent/PokeAlarm#329]
## Problem Description
RIght now when you have a manager and geofence for a larger area like medium city size, the user might have it hard to decide fast if the desired alarmed Pokémon is reachable or not. Here, a simple label which geofence was triggered would help, dividing a city into party.

For example: Manhattan, New York
Whole Manhattan is scanned, Despotar spawns in Central Park
Geofence Central Park is triggered, and alarming ``Despotar spawned in Central Park`` because we used ``<pkm> spawned in <geofence>``

## Current state
The current state is, that the geofence prevents alarms outside the desired area (not working properly sometimes, with alarms outside the geofence, see the other issue #330) but not doing anything else. The names are only as visual separation inside the geofence.txt which is good but my #291 proposed already the dynamic text substitution which seemed to be forgotten.

## Possible solution
Modify the code to read multiple geofences out of one geofence.txt file and add a name which is also parsed and stored as a **dynamic text substitution <geofence>** when triggered for the coming alarm. The structure of the geofence.txt is like below while ``geloc1``and ``geoloc2``are the names of the geofences which will be parsed when they are triggered and result in a alarm like ``Pokémon spawned in geoloc1`` when <geofence> is used in the alarm.

```
[geoloc1]
lat11,lon11   
lat12,lon12
...

[geoloc2]
lat21,lon21
lat22,lon22
...
```

**Comment by kvangent** [comment]
This feature is in branch v3.01. You are welcome to try it out. 

When the patch is pulled, I will close this.
