### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by FiveWord** [kvangent/PokeAlarm#33]
When going to start webhook.py I keep getting this error, which is strange because I've gotten it working before and just wiped the old copy I had and set up a new one. Any clue what could be causing this? 
![image](https://cloud.githubusercontent.com/assets/11514435/17375455/a4518e6e-5976-11e6-8b80-5e11cf266956.png)

**Comment by Aidz24** [comment]
Looks like you and I are getting the same errors. Posted the same thing at the same time.   

https://github.com/kvangent/PokeAlarm/issues/34 

I'll close mine if you keep yours open.

**Comment by kvangent** [comment]
Add a comma after  the api_key parameter.

**Comment by Aidz24** [comment]
Got it. You're the best! Thanks! 

Exact details = Navigate to your alarms.json folder, add a " , " (without quotes) after the Slack/Pushbullet api_key (Mine was pushbullet!)

"api_key":"ENTER-API-KEY-HERE"
to 

"api_key":"ENTER-API-KEY-HERE",

**Comment by FiveWord** [comment]
I made the adjustment mentioned above, no luck, still the same error 
![image](https://cloud.githubusercontent.com/assets/11514435/17384087/34f8608c-599f-11e6-84bb-3647840671a4.png)

**Comment by kvangent** [comment]
Make sure you aren't using notepad to edit the file. Use a better editor like Notepad++. (you'll need to make a new copy and edit it, notepad probably ruined your current alarms.json).

If that doesn't fix it, please post your json file.

**Comment by FiveWord** [comment]
Huh, I must have opened it in Notepad by accident at some point because making a new one worked perfectly. Thanks for the help :)

**Comment by kvangent** [comment]
No problem
