### ISSUE TITLE
[Bug] Geofence sometimes fails to jail an incoming Pokémon

### ISSUE THREAD

**Issue by Arengo** [kvangent/PokeAlarm#330]
## Problem Description
Using the new v3 I am using a geofence too, having multiple managers where only 1 can send alarms right now. All others are dummies. I do get alarms for Pokémon outside this geofence.

## Your Environment
I have a freshly pulled not altered PokeAlarm v3 with one working alarm on ```Manager 1```.
I would like to add that geofence1.txt which belongs to the working Manager 1 is detailed with around 25 entries.

```
    |    geofence1.txt        geofence2.txt      geofence3.txt  |
    |    filters.txt          filters.txt        filters.txt    |
    |    alarms1.txt          alarms2.txt        alarms3.txt    |
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question, asked in Discord multiple times

**Comment by kvangent** [comment]
You labeled this as 'Bug' but you used the enhancement issue request template. Please adjust to using the real issue template. Be sure in to include as much info as you can, such as your geofence layout and the coordinates of the pokemon that was incorrectly notified or ignored.
