### ISSUE TITLE
[BUG] Calculation of cardinal direction is not accurate

### ISSUE THREAD

**Issue by dripdropper** [kvangent/PokeAlarm#331]
## Problem Description
PokeAlarm is using an inaccurate algorithm to estimate the cardinal direction.  This can cause, for example, PokeAlarm to say a Pokemon is SE when it is clearly just S.

The solution is to use the power of mathemagics (trigonometry!) to calculate the exact bearing angle and then assign a cardinal direction accordingly.  Fortunately, I have done the hard work and developed just such an algorithm.  It's not in Python (because I currently have no good development environment), but it should be trivial to convert it and integrate it with PokeAlarm.  I have done some basic testing, and it appears to work correctly.
```
string computeDirection(degrees latitudeUser, degrees longitudeUser, degrees latitudePokemon, degrees longitudePokemon)
    radians lat1 = latitudeUser * (PI/180.0);
    radians lat2 = latitudePokemon * (PI/180.0);
    radians deltaLong = (longitudePokemon-longitudeUser) * (PI/180.0);

    double y = sin(deltaLong) * cos(lat2);
    double x = cos(lat1)*sin(lat2) - sin(lat1)*cos(lat2)*cos(deltaLong);
    degrees bearing = atan2(y, x) * (180.0/PI);
    while (bearing < 0)
        bearing = bearing + 360;

    string[8] directions = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"];

    degrees adjustedBearing = (bearing + 22.5) % 360;
    int index = floor(adjustedBearing / 45.0);
    string directionToPokemon = directions[index];

    return directionToPokemon;
```

## Your Environment
Not relevant.

## Console Output
Not relevant.

## Your Alarms Config
Using `<dir>` text substitution.

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
This was fixed with commit 39261ad7bab10aa7b02704c51633b34b9b6d01de.
