### ISSUE TITLE
[BUG] Triggers not posting into Discord

### ISSUE THREAD

**Issue by bdgotham** [kvangent/PokeAlarm#339]
---
## Problem Description
!--- Please describe the problem you are experiencing.  --
Discord Server does not post all of the triggers.  It seems to only post 1 out of every 3 or so triggers that pass through the console.

## Your Environment
!--- Please post as many details  --
Operating System: Windows 10
Python Version 2.7.12
Rocketmap-Map startup command `cmd`  python runserver.py -cf config.ini
PokeAlarm startup command `cmd`  start_pokealarm.py

Did the issue persist after restarting the script. yes

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --
```

```
![cafa4ceb218d074321e332bdb05e703a](https://cloud.githubusercontent.com/assets/26211608/23595130/72cfc5b6-01ed-11e7-84c5-73eff5bada4e.png)

## Your Alarms Config
!--- Please post the config for your alarms in the space below --
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```
[
  {
    "active": "True",
    "type":"discord",
    "api_key":"https://discordapp.com/api/webhooks/276767903901286401/HpnSkLS880InbojDTSPmBOHBTEkTHkavYCo8M5IfrhnOSSZqBt2oZwhGXGI11ypKgrcb",
    "startup_message":"False",
    "startup_list":"False",
    "pokemon":{
      "api_key":"https://discordapp.com/api/webhooks/276767903901286401/HpnSkLS880InbojDTSPmBOHBTEkTHkavYCo8M5IfrhnOSSZqBt2oZwhGXGI11ypKgrcb",
      "username":"<pkmn>",
      "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<pkmn_id>.png",
      "title": "[<neighborhood>] <pkmn> <iv>%",
      "url": "<gmaps>",
      "body": "<address> <postal> \n<atk>/<def>/<sta> <move_1> / <move_2> \nuntil <12h_time> with <time_left> left... caCAW!"
    },
    "gym":{
      "api_key":"https://discordapp.com/api/webhooks/286160581403213825/uFWYZSc2cDvzPgJ20Y5pCUegC22DXzlY__W0xd1sUwVyKfc1w3hvU-P4ZAk-75BbZOxs",
      "username":"Contested Gym",
      "icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/gym_<team_id>.png",
      "title": "[<neighborhood>] <address> <postal>",
      "url": "<gmaps>",
      "body": "A <old_team> gym has fallen to <new_team> \nGet Some!"
    }
  },
  {
    "active": "False",
    "type": "facebook_page",
    "page_access_token": "YOUR_PAGE_ACCESS_TOKEN"
  },
  {
    "active": "False",
    "type": "pushbullet",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "pushover",
    "app_token": "YOUR_APP_TOKEN",
    "user_key": "YOUR_USER_KEY"
  },
  {
    "active": "False",
    "type": "slack",
    "api_key": "YOUR_API_KEY"
  },
  {
    "active": "False",
    "type": "telegram",
    "bot_token": "YOUR_BOT_TOKEN",
    "chat_id": "YOUR_CHAT_ID"
  },
  {
    "active": "False",
    "type": "twilio",
    "account_sid": "YOUR_API_KEY",
    "auth_token": "YOUR_AUTH_TOKEN",
    "from_number": "YOUR_FROM_NUM",
    "to_number": "YOUR_TO_NUM"
  }
]
```

## Troubleshooting Checklist
[X ] Most recent version of Rocketmap-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

!--- END OF [BUGUSER SPECIFIC] TEMPLATE ---REMOVE ABOVE OR BELOW THIS LINE             -----

**Comment by kvangent** [comment]
@bdgotham Currently discord doesn't check to ensure it's request was accepted. I hope to fix this problem soon.

**Comment by kvangent** [comment]
Discord has become more reliable in branch v3.01. This should solve your problem. You are welcome to try it out.

When this patch is pulled, I will close this.
