### ISSUE TITLE
[ENHANCEMENT] Update move_info.json for generation 2 moves.

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#340]
## Enhancement Description
Update `move_info.json` in PokeAlarm for the recent generation 2 move update.

## Use cases
DTS options `<move_1_damage>`, `<move_1_dps>`,  `<move_1_duration>`, `<move_1_energy>`, `<move_2_damage>`, `<move_2_dps>`, `<move_2_duration>`, and  `<move_2_energy>` rely on info from `move_info.json`.  Updating will allow for said DTS to return the new values.
## Other Links
https://pokemongo.gamepress.gg/pokemon-moves

**Comment by kvangent** [comment]
Done in #341
