### ISSUE TITLE
[BUG] Telegram Map notification disable broken

### ISSUE THREAD

**Issue by TheQL** [kvangent/PokeAlarm#345]
## Problem Description
Although map notification is disabled I receive three notifications per Pokémon (Text, Sticker, Location). Might be an API-change by Telegram, but maybe you can adapt. Can't remember when it broke, it was not related to an update of PokeAlarm though. Until then I only got one push.
I just recently added the param to the Pokémon, which is kind of redundant and did nothing.

## Environment
Operating System: Windows 7 
Python Version 2.7.13

## Alarms Config
{
    "active": "True",
    "type": "telegram",
    "bot_token": "",
    "chat_id": "",
	"startup_message": "False",
	"startup_list": "False",
	"disable_map_notification": "True",
	"stickers": "True",
	"pokemon": {
				"title": "Some title",
				"body": "some text",
				"location": "True",
				"disable_map_notification": "True"
			}
  },

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
It was a change by Telegram, I was unable to find a way around it (their API doesn't seem to work like the documentation describes). You can try bringing it up to them or letting me know if someone else has a fix.
