### ISSUE TITLE
Not getting notifications of all pokemon

### ISSUE THREAD

**Issue by dunhillz** [kvangent/PokeAlarm#35]
Hi,

I've seen this happen quite a few times. I have some of the more rarer pokemons set to true however even though it shows up on my pokemon go map server, the PokeAlarm does not send any notifications. For example, I saw a Blastoise within the map that expires in 5 minutes however it never sent a notification to slack.

Another example is with Eevee. I think I only get a notification half of the time when she spawns. I constantly check my pokemon go map server and notice she'd appear but sometimes i wouldn't get the notification.

**Comment by kvangent** [comment]
Please post the commands you are using to run both the server and the map. 

Also, you should check in the log and see if it says "Blastoise notification skipped:" for any reason.

**Comment by Aidz24** [comment]
Dunhillz, which program are you using to receive notifications? Pushbullet/Slack? I have two phones, on one of them, Slack messages only gets messages if I have it running in the background(all settings for push notifications in both Slack and Google are correct) on the one. On the other, it makes no difference if its open closed or anywhere in between. Seems overkill, but this is why I use both Pushbullet and Slack.

**Comment by dunhillz** [comment]
`python runserver.py -a ptc -u Username -p Password -l 123,-123 -st 2 -H 0.0.0.0 -L en -k A1234123412341234 -wh http://localhost:3000/` - map

'python runwebhook.py -P 3000 -H 0.0.0.0' server

**Comment by dunhillz** [comment]
@Aidz24 I am just using slack. I think I know exactly what you mean by the push notifications. I opened the slack app to see if I did get any notifications but it didnt show up there. I think its a problem with the initialization of retrieving the data from the pokemon go map

**Comment by kvangent** [comment]
Is there a reason  you set the host to 0.0.0.0 instead of 127.0.0.1?
Are you running multiple workers? Are you sure they are all set up to use the webhook?

If you are getting some notifications its receiving some data from the map. Either your workers aren't all sending the information, or something is stopping it in between.

If you check the console that you are running the webhook in, it will tell you every time it receives data on a pokemon and if it decided to trigger a notification or not. I would suggest looking at this log and see what it says.

**Comment by Blamroc** [comment]
I've had this problem with only one specific pokemon (charmander) that only spawns on one point within my scanned area. It always displayed on the map, sometimes it would trigger an alert (I only use Telegram) but most times it would not, I modified runwebhook.py to dump into a log file and could not find any mention of the charmander I saw on map but wasn't alerted for.
I use ```runwebhook.py -H 127.0.0.1 -P 4000``` to run PokeAlarm and for the first worker:
``` 
 -a ptc -u username -p password -l "gps" -fl -st 3 -sd 10.1 -H 0.0.0.0 -P 5000 -k GAPIkey -L EN -t 1 -wh http://127.0.0.1:4000
``` 
 and for the other 18 scanbots (one of these covered the charmander area):
```
  -a ptc -u username -p password -l "gps" -st 3 -sd 10.1 -ns -k GAPIkey -L EN -t 1 -wh http://127.0.0.1:4000
```
Also I run with the changes you mention under Common Problems to my files.
Might be a problem with PokemonGo-Map? Is there an easy way to log all webhook traffic coming from it?

**Comment by kvangent** [comment]
I would ensure that you have everything correctly setup. If charmander is spelled wrong or not set correctly, it will skip the notification (and say so in the log).

You can see all the webhooks received by the Alarm if you run in debug mode. 

I am going to close this issue for now. If you continue to have problems after the API is fixed, please reopen.
