### ISSUE TITLE
[ENHANCEMENT] Filter by gender

### ISSUE THREAD

**Issue by PokemonCatcher** [kvangent/PokeAlarm#356]
## Enhancement Description
Allow filtering by gender.

## Use cases
This will allow people trying to collect breeding pairs to be happy.

**Comment by PokemonCatcher** [comment]
I have committed code which implements filter by gender:
https://github.com/PokemonCatcher/PokeAlarm/

It has been tested and works when incoming data is good.
It is largely untested when incoming data is incomplete or corrupt.
i.e. neutral gender, unknown gender etc.

There is some complication with gender being represented by both name and symbol. I isolated the conversion between the two to check_genders method.

**Comment by PokemonCatcher** [comment]
Code has been running on my small server for 4 days now. I have not had any problems reported.

**Comment by kvangent** [comment]
I think it looks pretty good from a cursory glance, but I won't have time until after this weekend is over to sit down and mess with it.

**Comment by PokemonCatcher** [comment]
I guess this issue can be closed. Thank you for accepting the pull request! I'm happy to support any issues relating to gender filtering and reporting. Ping me if anything comes up.
