### ISSUE TITLE
[ENHANCEMENT] Different notification text based on Pokemon number

### ISSUE THREAD

**Issue by dsorc** [kvangent/PokeAlarm#360]
## Enhancement Description
You could have separate pokemon status tags in alarms.json based on received pokemon number. (if - else statements?)

## Use cases
You only care about the size of Magikarp and Rattata. No need to have this information included for other pokemon.

**Comment by kvangent** [comment]
You can do this with managers.

You can create a manager to filter just magikarp and rattata with an alarms config set up to alert on what you want. And you can create another one with all the others.
