### ISSUE TITLE
Time_left always its around 1 Minute

### ISSUE THREAD

**Issue by painkiller666X** [kvangent/PokeAlarm#361]
!--- [BUGUSER SPECIFIC] Use this template if PokeAlarm is behaving in an incorrect or unexpected way.   ---
## Problem Description

In the alerts Time_left always its around 1 Minute and the "iv, atk, def, sta " are undefined symbol (?)

## Your Environment
Python 2.7
Win 10 X64
RocketMap
PokemonGo-Map startup command `python runserver.py -cf xxx.ini`  
PokeAlarm startup command `python start_pokealarm.py`

Did the issue persist after restarting the script yesno

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --
```
	CONSOLE OUTPUT GOES HERE
```

## Your Alarms Config
!--- Please post the config for your alarms in the space below --
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```json
"active": "True",
		"type": "telegram",
		"bot_token": "XXX",
		"chat_id": "XXX",
		"pokemon":{
				"title": " Pokemon:",
				"body": " pokemon: <pkmn> \n Latitud y Longitud:\n <lat>,<lng> \n Disponible hasta las: <24h_time> ,(<time_left>) \n ( <iv>% <atk>/<def>/<sta> \n <quick_move>,<charge_move>) "  

```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

!--- END OF [BUGUSER SPECIFIC] TEMPLATE ---REMOVE ABOVE OR BELOW THIS LINE             -----
!--- [ENHANCEMENT] Use this template if you have a suggestion for improving PokeAlarm   -----
## Enhancement Description
!--- Please describe the improvement you are proposing.  --

## Use cases
!--- Please describe why you think this improvement will be useful --

## Other Links
!--- If you are suggesting a new service, please include a link to relevant API or Python module --

!--- END OF [ENHANCEMENT] TEMPLATE  ---------------------------------------------------------------

**Comment by walaoaaa1234** [comment]
Do you have accurated time at RocketMap?

**Comment by painkiller666X** [comment]
where do you set accurated time?? its a parameter? please can you help me to set??

**Comment by walaoaaa1234** [comment]
join Rocket map discord for support https://discord.gg/RocketMap
