### ISSUE TITLE
How do you deal with negative expiry time?

### ISSUE THREAD

**Issue by brettgus** [kvangent/PokeAlarm#37]
I was browsing the code, and it looks like you check to see if a Pokemon has already expired when you get the notification.  However I've noticed that some of the pokemon will have a negative expiry time.  I believe this means that the pokemon will last longer than 15 mins.  Are you accounting for this?

**Comment by paradoxally** [comment]
At least in the earlier releases when I used this as part of AHAAAAAA's forked repo, it would send me notifications about expired Pokémon and they would be constant (e.g. 10 notifications in 5 minutes or so). If this hasn't been fixed, I believe it's possible to suppress with a simple check.

**Comment by kvangent** [comment]
As of right now, PokemonGo-Map sends a timestamp and now a countdown of when they dissapear. I'm not sure if the Map corrects negative times or not - but the Alarm check if a notice has already expired before alerting you. This fixed the multiple notifications issue in early versions.
