### ISSUE TITLE
[BUG] Charge/Quick moves can not be set in default section

### ISSUE THREAD

**Issue by friscoMad** [kvangent/PokeAlarm#374]
## Problem Description

quick_move, charge_move can not be set in the default filter, it leads to the error:

> Moves list must be in a comma seperated array. Ex: ["Move","Move"]Please see PokeAlarm documentation for more examples.

## Your Environment

Operating System  
Python Version (use `python -V`)  
PokemonGo-Map startup command `cmd`  
PokeAlarm startup command `cmd`

Did the issue persist after restarting the script yesno

## Console Output

```
	CONSOLE OUTPUT GOES HERE
```

## Your Alarms Config
I am not posting all pokemons for brevity reasons
```json
      "pokemon": {
    "enabled": "True",
    "default": {
      "min_dist": "0",
      "max_dist": "5000",
      "min_iv": "0",
      "max_iv": "100",
      "min_atk": "0",
      "max_atk": "15",
      "min_def": "0",
      "max_def": "15",
      "min_sta": "15",
      "max_sta": "15",
      "quick_move": ["Dark Pulse","Vice Grip"],
      "charge_move": ["Hyper Beam","Sludge"],
      "moveset": null,
      "size": [
        "normal",
        "large"
      ],
      "gender": [
        "male",
        "neutral"
      ],
      "ignore_missing": "False"
    }
}
```

The problem comes from the function create_moves_list, the default section is parsed without issues but for each pokemon a new filter is created and calls again to the same function but with the values returned from the first call.
So for the first call we get a list of text moves but the second call gets a set or int moves.
My proposal to fix that is changing lines 248 onwards with:

```python
        if moves is None:  # no moves
            return None
        if type(moves) != list and type(moves) != set:
            log.error("Moves list must be in a comma seperated array. Ex: [\"Move\",\"Move\"]"
                      + "Please see PokeAlarm documentation for more examples.")
            sys.exit(1)
        if type(moves) == set: # default moves being parsed again
            return moves
        list_ = set()
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
This should be fixed in the next patch 06fdaf734bbd07663e2423a09aebe0e9fcf734ab.
