### ISSUE TITLE
[Enhacement] Filter by CP

### ISSUE THREAD

**Issue by JoniValles** [kvangent/PokeAlarm#384]
# Enhancement Description

!--- Please describe the improvement you are proposing. --

As the title says, filter by CP too, not only by % IVs 

# Use cases

!--- Please describe why you think this improvement will be useful --

Sometimes it can be useful that we prefer a 3000 CP Dragonite 0% instead of a 400 CP Dragonite 100%

# Other Links

!--- If you are suggesting a new service, please include a link to relevant API or Python module --

**Comment by tallypokemap** [comment]
Branch v3.2 already does this.  Pull that branch or wait for it to be merged, but it might take a while for it to be merged, so I recommend pulling it as it is stable.
