### ISSUE TITLE
[Enhancement] Discord

### ISSUE THREAD

**Issue by HusbandoMax** [kvangent/PokeAlarm#39]
Is there any chance of having this post in Discord acting like the bots I see all the time or maybe facebook groups?

**Comment by kvangent** [comment]
Potentially discord. I'll add it to my list. Facebook probably not.

**Comment by phr34k0** [comment]
Discord please :3 maybe refer to https://github.com/Devsome/pkGo-Discord

**Comment by kvangent** [comment]
I haven't been able to find a good module for Discord that works with Python 2.7, so for right now Discord is going on the back-burner for now. If you know of one or are willing to get the ground work start on authentication for their REST api please let me know.

**Comment by phr34k0** [comment]
@kvangent Is cool. I've already coded my own using https://github.com/ImDevinC/pkgo-discord/blob/master/discord-server/app.js .. 

`npm install discord.js` and slap in a bash script that pgreps pid, if errorlevel and cronevery 2 minutes if process stops works like a charm. 

![image](https://cloud.githubusercontent.com/assets/13272249/17863424/2ade1ce0-68cc-11e6-9367-9962069bfff5.png)
