### ISSUE TITLE
[ENHANCEMENT] Adding CP details

### ISSUE THREAD

**Issue by jophj** [kvangent/PokeAlarm#393]
## Enhancement Description
I'm proposing to add CP support in dynamic text substitution.

## Use cases
Notified pokemon's CP could be really useful combined with IV info. A low IV high CP pokemon, like a Dragonite or a Snorlax or even a Machop, can be used to attack/defend gyms or to be evolved saving lots of candies for powering up.

**Comment by tallypokemap** [comment]
This already exists in branch v3.2

**Comment by jophj** [comment]
I'm using it and can confirm it works. There are also level  filters and, for what I understand, level dts. That's awesome!

I'm closing this issue, thanks.
