### ISSUE TITLE
[ENHANCEMENT] Commands for Telegram Bot

### ISSUE THREAD

**Issue by mo-mueller** [kvangent/PokeAlarm#394]
## Enhancement Description
I have good ideas for some commands for the Telegram Bot. You can write something like /status in the Telegram chat and then the Bot gives a response. This ideas are primary for use RocketMap on a server, which runs 24/7. Here are my ideas:

### /status

Check if PokeAlarm is running correctly and also check if RocketMap is running correctly. You could check the time, when the last message came from RocketMap and if it is longer than x minutes ago, RocketMap is not running correctly. And then the Bot gives a response if everything is running or not. If not, you can connect to the server and check what is going wrong.

### /enable \<pokemon\>

Set the value of a given pokemon in the filters.json to "True" and then reload the filters.json

### /disable \<pokemon\>

Set the value of a given pokemon in the filters.json to "False" and then reload the filters.json

### /highivonly \<pokemon\>

Use a predefined object like { "min_iv": "95", "ingore_missing": "True" } and set it to the given pokemon

### /reload

Reload the config files without restarting the whole program. Usefull if you just edit the files on PC and transfer them to the server via SFTP. Then you dont must connect to the server with putty and restart the program.

## Use cases
This is very usefull if you run your programs on a server. If you just write "/enable Dragonite" you save yourself these steps:

- Start your PC
- Edit local filters.json
- Upload it to server
- Connect to the server
- Go to the correct screen
- Stop the running program
- Start the program
- Leave the screen
- Leave the server

Then you only have to go to your PC and connect to the server if something is wrong with PokeAlarm or RocketMap. And that you can check with /status. Would be awesome!

On default these commands should be disabled. If you want to enable it, you must define the commands for your bot with BotFather and then you can enable the PA config for it.

## Other Links
\-

PS: An answer, whether you like this and whether you would implement it would be nice. Otherwise I would customize that sometimes on my own. But I've never worked with python yet :/

**Comment by kvangent** [comment]
There are no plans to do this any time soon. It is very complicated and not easily possible with the current structure of PA.
