### ISSUE TITLE
[ENHANCEMENT] Follow up list of trainers in gyms

### ISSUE THREAD

**Issue by bbdoc** [kvangent/PokeAlarm#395]
## Enhancement Description

Would be very useful to be able to follow a list of specific trainers in gyms and get notification if one of those trainers is being ejected from a gym (including current gym lvl and xp)

## Use cases

When playing with a team of people, that would allow those people to get notifications when losing some of our gyms so that we can quickly get back and train those gyms again.

**Comment by reme-dy** [comment]
While I see your point, filtering based on player names would make it all too easy to track other players and create a witch hunt scenario.

**Comment by bbdoc** [comment]
OK thanks, I do understand your point. Even if this would be a PA setting, so only available to the map admin, and tbh, if I want to track down a player name for whatever reason, I can already do so using a simple query on my RM db ;-)

What about being able to set a list of gyms we want to follow ? My map is scanning a big amount of gyms and I don't want to avoid being spammed with changes in all of those, would be nice to be able to filter only on the ones we try to maintain (and i don't think this one could be abused).

Also do you think adding the list of gym members to the notification and triggering notifications for every change in the list of member would be an issue (so if a gym goes down from lvl 10 to 9 I would like to receive a notification, not only when it's completely taken down) ?

**Comment by kvangent** [comment]
@bbdoc You could do this with geofences for sure.

I have plans for more gym features in the future, but not alot of people use that functionality and gym notifications are complicated because of the nature of them.
