### ISSUE TITLE
Filter by either IV or CP

### ISSUE THREAD

**Issue by lota7** [kvangent/PokeAlarm#400]
### [ENHANCEMENT] 
Be able to filter pokemon by either IV or CP...not both.

## Problem Description
Currently using:
{ "min_iv":"80", "min_cp":"1500" }
Will only trigger if the pokemon has IV 80+ **AND** CP+1500.
I want the trigger to go off if **EITHER** of them is fulfilled, no need for both to be true.

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
This is already possible with the multiple filter feature. Check the wiki for more info.
