### ISSUE TITLE
IOError: cannot watch more than 1024 sockets

### ISSUE THREAD

**Issue by chickennoodo** [kvangent/PokeAlarm#412]
!--- [BUGUSER SPECIFIC] Use this template if PokeAlarm is behaving in an incorrect or unexpected way.   ---
## Problem Description
When I run Pokealarm, I am having an error pop up. It doesn't appear at first, but once more than 350 or so workers log on, this error pops up almost every other manager. Rocket map will scan a pokemon, but sometimes the error will prevent it from being pushed to Discord.

## Your Environment
!--- Please post as many details  --
Windows 10  
Python-2.7.12  
RocketMap - python ./runserver.py
PokeAlarm - python start_pokealarm.py

Did the issue persist after restarting the script?

Yes

## Console Output
!--- Please post any relevant output provided from the PokeAlarm when you ran it --
```

  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 197, in _do_read
    args = self.do_read()
  File "C:\Python27\lib\site-packages\gevent\server.py", line 158, in do_read
    client_socket, address = self.socket.accept()
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 198, in accept
    sockobj = socket(_sock=client_socket)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 124, in __init__
    self._read_event = io(fileno, 1)
  File "gevent.libev.corecext.pyx", line 487, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6680)
  File "gevent.libev.corecext.pyx", line 835, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11088)
IOError: cannot watch more than 1024 sockets
Sun Jul 30 13:49:12 2017 <WSGIServer at 0x492e4e0L fileno=644 address=127.0.0.1:4000> failed with IOError
```

## Your Alarms Config
!--- Please post the config for your alarms in the space below --
!--- Remove all person data such as API_KEYs or CHAT_IDs --
```
# Server Settings
#debug											# Enables debugging mode
#host:											# Address to listen on (default 127.0.0.1)
#port:											# Port to listen on (default: 4000)
manager_count: 7
# Number of Managers to run. (default: 1)
key: *******

# Manager-Specific Settings
#manager_name                                   # Name of the Manager in the logs. Default(manager_0).
#key:                                           # Google Maps API Key to use
filters:	[filters.json, superfilters.json, ultrafilters.json, raidfilters.json, legendaryfilters.json, candyfilters.json, starterfilters.json]
# File containing filter rules (default: filters.json)
alarms: 	[alarms.json, superalarms.json, ultraalarms.json, raidalarms.json, legendaryalarms.json, candyalarms.json, starteralarms.json]
# File containing alarm rules (default: alarms.json)
#geofence:										# File containing geofence(s) used to filter (default: None)
#location:										# Location for the manager. 'Name' or 'lat lng' (default: None)
#locale:										# Language to be used to translate names (default: en)
#unit:											# Units used to measure distance. Either 'imperial' or 'metric' (default: imperial)
#timelimit:										# Minimum number of seconds remaining to send a notification (default: 0)
#max_attempts:									# Maximum number of attempts an alarm makes to send a notification. (default: 3)
#timezone:                                      # Timezone used for notifications Ex: 'America/Los_Angeles' or '[America/Los_Angeles, America/New_York]'
```

## Troubleshooting Checklist
[Yes] Most recent version of PokemonGo-Map
[Yes] Most recent version of PokeAlarm
[Yes] Checked the Wiki page for service in question

!--- END OF [BUGUSER SPECIFIC] TEMPLATE ---REMOVE ABOVE OR BELOW THIS LINE             -----

**Comment by kvangent** [comment]
This occurs when your machine has too many sockets open. Windows has a max of 1024 open at one time. You need to lower your webhook threads (or concurrent webhook, whichever you are using).

**Comment by chickennoodo** [comment]
Is there a general rule, or formula I should follow for the amount of
threads I should open?

I have just under 800 workers, running 7 alarms, with a scan delay of 25
sec.

Thanks for getting back to me!

**Comment by kvangent** [comment]
It depends on your setup, how many instances, you run, etc. I would start off with the defaults and only raise it slowly if you experience longer queues.

**Comment by chickennoodo** [comment]
A trial by error, gotcha! Thanks very much!
