### ISSUE TITLE
Twilio Error

### ISSUE THREAD

**Issue by jorgitoh** [kvangent/PokeAlarm#414]
Hi. The api for Twilio it is updated?. Im trying to using Twilio but i have an error like "Abstract Method not implemented". 

[Manager][ERROR] Encountered error while loading Alarms: NotImplementedError: This is an abstract method.

**Comment by jorgitoh** [comment]
Fixed:

TwilioAlarm.py
Line 57
Error:
self.__egg = self.create_alert_settings(settings.pop('egg', {}), self._defaults['egg'])

Fix:
self.__egg = self.set_alert(settings.pop('egg', {}), self._defaults['egg'])

**Comment by kvangent** [comment]
Thanks for catching this - fixed as of commit https://github.com/kvangent/PokeAlarm/commit/d8c554f639894573769aab214c6b467f591a5711. 

In the future, please be sure to use the appropriate template when opening an issue.
