### ISSUE TITLE
[Enhancement] Update config while running

### ISSUE THREAD

**Issue by brettgus** [kvangent/PokeAlarm#45]
Any plans on making it so a URL can be called to the PokeAlarm to change the configuration options?

**Comment by kvangent** [comment]
I have thought about implementing a RESTful API but the use cases seem pretty slim. What would you do with it if I did?

**Comment by amducious** [comment]
I don't know if the OP was wanting the same thing as me but I think this would give us the ability to create a silent mode for ex. while I'm sleeping

**Comment by brettgus** [comment]
I was thinking about making a web GUI for myself so I could change the monitored location and pokemon ids while on the go.  I'm sure I'd figure out a way to whip up a way to push updates of my phones location automatically.

I was thinking of forking and implementing something like this myself, but I don't have much python experience and was having trouble figuring out how to pass data from the web server to the called thread for alarm_manager

**Comment by kvangent** [comment]
@amducious I just shut the alarm off when I got to bed and start it in the morning.

@brettgus If you can make a reasonable GUI, I'm fairly certain I can get it to pass data to the server.

**Comment by fatmagic** [comment]
@amducious If you use Slack for notifications, you can set an automatic nightly "Snooze / Quiet Time" on the channel. I do this so it goes silent from 11pm to 7am. Notifications still arrive, just don't buzz my phone until after 7am.

**Comment by RiberoD07** [comment]
another github project uses a telegram bot to add or remove entries to a config file would this be possible?
https://github.com/algoni/PogoBot-Telegram/blob/master/src/bot.js
think it's a very nice way of doing it for people using telegram as their alarm and allows for changing the configuration on the fly. I know the configuration the other github project uses is completely different but might be worth checking it out and would be amazing if it could be implemented.

**Comment by kvangent** [comment]
@RiberoD07 It's definitely possible but I probably won't get around to implementing it. I'm just one guy doing this in his free time and I'm already stretched pretty thin trying to answer issues as they pop up.

**Comment by RiberoD07** [comment]
@kvangent no worries, I appreciate the work you've already done! It's great and worked flawlessly from the get-go. Might be a bit more complicated seeing how their code is in javascript but if I have time i'll take a look at how something like that could work in python and see if I could do it but certainly recommend others that think they can do it to go for it.

**Comment by brettgus** [comment]
@kvangent Even just an API to change the location would be awesome.  If you have info/ideas on how to pass changes on to the alarm_manager thread I could even try to work on making this myself and submitting a PR

**Comment by brettgus** [comment]
Wow just realized config variable is shared by the caller and the thread.  That makes things easy.  

FYI, I'm going to try to think of a way to integrate pyicloud and PokeAlarm for automatic location for distance.. or even driving/walking time.

**Comment by kvangent** [comment]
@brettgus Yeah I tried to make it easy to expand.

I'm going to leave this open so people know it's on my radar.

**Comment by guaycuru** [comment]
I too would like this feature. My use case: I'm developing a Telegram Bot (already wrote too much code before realizing https://github.com/algoni/PogoBot-Telegram existed), so I'd like to change the pokémon list that triggers the alarm via an API.

**Comment by brettgus** [comment]
Created a pull request for basic location changing #117

**Comment by kvangent** [comment]
Consolidating to #148.
