### ISSUE TITLE
"notify_text" doesn't appear to be working

### ISSUE THREAD

**Issue by Varnsen** [kvangent/PokeAlarm#48]
So, finally managed to get PokeAlarm up and running and it's pretty much perfect. I saw in an update we can customize what the message says with the "notify_text" field, which I read about [**here**](https://github.com/kvangent/PokeAlarm/wiki/Alarm-Configuration)

Once the server is running, the message I get from the bot is: 

```
A wild Omanyte has appeared! 
http://maps.google.com/maps?q=lat,lon
 Available until 21:06:54 (9m 59s).
```

When, in the alarm.json I specified something like this:
```
		        "active": "True",
		        "type":"telegram",
		        "chat_id":"-CHATID",
		        "bot_token":"BOTTOKEN:BOTTOKEN-BOTTOKEN",
				"notify_text":"A wild <pkmn> has appeared until <12h_time>! <pkmn> is @ <addr> on <loc>. You are <dist> from the <pkmn> <gmaps>"
    		}

```

Any idea why these changes aren't being applied for the client? I should be on the most recent version of PokeAlarm.

**Comment by kvangent** [comment]
Telegram page is [here ](https://github.com/kvangent/PokeAlarm/wiki/Telegram). Telegram has two fields - `header` and `body_text`.
