### ISSUE TITLE
[Enhancement] Add distance to pokemon from a specified location

### ISSUE THREAD

**Issue by molecularswords** [kvangent/PokeAlarm#5]
It would be nice to have the notification tell you how far away the pokemon is. This would prevent the need to click the notification to open the map for certain pokemon that happen to be a bit too far away to go get in the moment but still show up in a scan. For example, this would help if I only care about pokemon that are essentially right next to me for now but I don't want to change my scanning radius because later I will be able to go and get pokemon that are further away.

A simple implementation of this could be done by asking the user for latlon coords and then adding something like this in the notify_pkmns method of notifications.py:

`lon1 = -78.942769   #User defined longitude
lat1 = 36.009407   #User defined latitude
lon2 = pkmn['longitude']
lat2 = pkmn['latitude']
dlon = lon2 - lon1 
dlat = lat2 - lat1 
a = (math.sin(math.radians(dlat/2.)))**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * (math.sin(math.radians(dlon/2.)))**2 
c = 2 * math.atan2( math.radians(math.sqrt(a)), math.radians(math.sqrt(1-a)) ) 
d = 3959 * c   #3959 is the radius of Earth in miles`

You could then just add 'distance': d to the pkinfo part and pass that through with the notification text.

**Comment by blaulan** [comment]
I had a similar implementation in [blaulan/PokemonGo-Slack](https://github.com/blaulan/PokemonGo-Slack), which will have different groups of pokemons and each group can have a different notification radius.

**Comment by kvangent** [comment]
This feature has now been added. Please see the Alarm Configuration and Pokemon Configuration pages of the wiki for more details.
