### ISSUE TITLE
Closing without error?

### ISSUE THREAD

**Issue by HusbandoMax** [kvangent/PokeAlarm#52]
Just randomly stops working after a few minutes without any error?
http://i.imgur.com/MPFsuJd.png

**Comment by kvangent** [comment]
Try running in debug mode `-d` and see if you get any other errors.

**Comment by HusbandoMax** [comment]
http://i.imgur.com/VGCiEGg.png

**Comment by kvangent** [comment]
Can you show your bat file?

**Comment by HusbandoMax** [comment]
python C:\PokeAlarm\runwebhook.py -d
pause
with -wh http://127.0.0.1:4000 thrown into my map with multiple account scanners if that affects it.

**Comment by HusbandoMax** [comment]
Doesn't seem to matter what I run it with. Tried Push and Slack both randomly do it.

**Comment by reactortrip** [comment]
I kept having issues with this one as well.  I think I give up with webhooks.  Kvangent, I am using your original alarm that worked inside the map that you took down the git for, do you mind if I make my own git repository for it and give you complete credit, so I can keep my files backed up.

**Comment by kvangent** [comment]
@reactortrip You certainly can, but there have been alot of changes to the Map to keep it working. The older version won't benefit from these changes.

@HusbandoMax Something is causing your python version to close. It doesn't seem to be the program it self. Do you run any antivirus or anything in the background?

One thing that I do to run the server is run a Virtual Machine with Ubuntu installed on it. VirtualBox is free and easy to use, and then you know you have an environment that works.

**Comment by reactortrip** [comment]
@kvangent thanks, not sure what I am missing, just like how stable it's been for me.  Seems to be pulling everything on the new dev map for me and only requires a few additions to the code.

**Comment by kvangent** [comment]
@HusbandoMax are you still having this issue?

**Comment by HusbandoMax** [comment]
@kvangent Nuh I got everything working. It seemed that it was the map iteself. I forgot that I had it restarting every so often when workers would stop working but that doesn't happen in the new version. So it was my dumb fault not realising that it was still doing that.
