### ISSUE TITLE
Telegram PokeAlert notifications for channels instead of groups?

### ISSUE THREAD

**Issue by Varnsen** [kvangent/PokeAlarm#53]
Hey, not sure if this is the right place to post this as it's more of a request/"is this already a feature" question, rather than an issue. I'm curious if PokeAlert is compatible with channels instead of groups? That way people won't get notified in the group if other people start talking about the new Pokemon that spawned.

I found [this bit of information when looking for a channels ID code](http://stackoverflow.com/questions/33126743/how-do-i-join-my-bot-to-the-channel), but it I don't think it applies to PokeAlert yet.

**Comment by kvangent** [comment]
From the look of it, channels and groups are handled the same. You should just need to create the channel, add the bot and make it an administrator. The 'chat_id' will be @channelid where channel id is the end part of the url.

You are welcome to give it a shot and let me know if it works.

**Comment by Varnsen** [comment]
I'll give it a go and report back ASAP. I'm having trouble with telegram not allowing me to create groups/channels currently, but hopefully that'll fix itself soon.

**Comment by kvangent** [comment]
Hey so I tried it out and it works just like I said. I couldn't create a channel from the web app but I could do it from the android app.

**Comment by Varnsen** [comment]
Aha! It worked brilliantly, I think. The problem comes in if you want a private channel, but it's not too much of an issue.

If anyone's curious, include the @ sign in the "chat_id": option, like @kvangent said.

e.g.: `"chat_id":"@PokeAlertArea",` 
You get the ID from the join URL you can use.

**Comment by RiberoD07** [comment]
Had no idea what chat_id was i kept using username or @username but no luck. Thanks, created a channel and this worked! If pushbullet is no longer supported telegram will be my go to.
