### ISSUE TITLE
[Request] Add multiple slack channels with different pokemon going to each one

### ISSUE THREAD

**Issue by amducious** [kvangent/PokeAlarm#55]
Ultimately I would like to have slack setup with a channel for Each Pokemon so my users can just add or remove that Pokemon's channel to receive or stop receiving that Pokemon's allerts

**Comment by kvangent** [comment]
I'll look into this.

**Comment by Bart274** [comment]
where do you find your API key for Slack?

**Comment by HusbandoMax** [comment]
That would be great. Having certain pokemon in certain channels like rares, uncommon ect.

@Bart274 https://my.slack.com/services/new/bot

**Comment by amducious** [comment]
@HusbandoMax  It is great. As a temp fix I am running 13 instances of PokeAlarm for the different channels I want to run. But it has created a hell of a mess starting my server not to mention the extra overhead

**Comment by Bart274** [comment]
@HusbandoMax thanks a lot, that did the trick :)

**Comment by HusbandoMax** [comment]
@amducious How did you go about running s many? I'm unable to run more than on at a time from the map.

**Comment by amducious** [comment]
@kvangent I don't know if this helps get across what I'm thinking but I was hoping get have the alarms.json file act somthing like [this](http://pastebin.com/tJ6cuRBB).

This way not only would we be able to just add another slackbot section but if I wanted to do something like. Send everything to slack and then only have rares spawns sent to me through sms

**Comment by amducious** [comment]
@HusbandoMax You I dont know about windows so if you running it there your sol. But for linux I just cloned PokeAlarm into a new folder for each instance and then I run a script at startup like [this one ](http://pastebin.com/uyVPLvz6)

**Comment by HusbandoMax** [comment]
@amducious Ah thought thats what you would have done. Wasn't 100% sure if it would let you run multiple webhooks o the map like that.

**Comment by kvangent** [comment]
@HusbandoMax You can run as many webhooks as you want. You can have 10 different alarms going as long as they each have a different port and the Map is set up to send to all of them. 

@amducious I am going to add the channel to the list of things that take dynamic text for slack. This way you can set up the channel as #<id> or #<pkmn> and it will send to the correct channel. I don't want to have a list of each pokemon for each alarm because that gets unwieldy.

**Comment by kvangent** [comment]
Ok, you can now add an option 'pkmn_channel' field to Slack alarms. This will allow you to push to channels named with ID or Pokemon names. Nidorans will be renamed to NidoranM or NidoranF.

**Comment by amducious** [comment]
@kvangent Thank for doing this so quickly. I know I'm going to fee dumb after this but how should this be formated to get this working can you show and example alarms.json file.

**Comment by kvangent** [comment]
```json
		{
			"active": "True",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#general",
			"pkmn_channel":"#<pkmn>"
		}
```

**Comment by amducious** [comment]
@kvangent I know this has been closed but is there anyway to get the bot to auto create the rooms when you add the new "pkmn_channel option
