### ISSUE TITLE
Still issues with ReadTimeOut

### ISSUE THREAD

**Issue by remcotroost** [kvangent/PokeAlarm#56]
I just reinstalled the PokemonGo-Map on my own VPS instead of Heroku. Everything works fine except the webhook to PokeAlarm.

I think it's an issue with the time as I'm getting a ReadTimeOut issue. My alarm is running as I got a confirmation on Telegram.

Screenshot: http://imgur.com/FPUEF1N

Anybody got any ideas or had the same issue?

**Comment by kvangent** [comment]
It is not related to time. 

It looks like an issue with PokemonGoMap I would install the latest version and make sure you reinstall the requirements with pip.

**Comment by kvangent** [comment]
This doesn't seem to be happening to me when I run the map. Are you still having problems?

**Comment by remcotroost** [comment]
Unfortunately I am. I've brought it up in the PokemonGo-Map community. I
fresh installed 12 hours ago so this shouldn't be a problem.

What does your webhook look like in config.ini on the map (or via -wh).
I'm using `webhook: http://localhost:4000`. I've also tried 127.0.0.1

Thank you.

On Aug 8, 2016 17:46, "Kurtis Van Gent" <notifications@github.com> wrote:

This doesn't seem to be happening to me when I run the map. Are you still
having problems?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kvangent/PokeAlarm/issues/56#issuecomment-238278729>,
or mute the thread

**Comment by kvangent** [comment]
What is your OS? Python version?

My webhook looks the same as yours.

**Comment by remcotroost** [comment]
I'm on:

Ubuntu 14.04.5 LTS
Python 2.7.6 (also have python3 installed for other things)
PIP is connected to Python 2.7.6

It's really weird. I've googled and its seems to be a TimeOut issue, perhaps to the alarm, but the alarm itself is running (I get activated notification on telegram) and listening on port 4000. It might be a system issue, I don't know

**Comment by kvangent** [comment]
@remcotroost Can you delete your PokemonGo-Map older and do a clean pull and npm install? Please back up any config files if necessary.

**Comment by remcotroost** [comment]
@kvangent I'll give it a try tomorrow. Will report back.

**Comment by remcotroost** [comment]
Update:
updated to latest PokemonGo-Map dev build. Everything works.

Closing the issue. Thank you
