### ISSUE TITLE
Notifications for lured pokemons

### ISSUE THREAD

**Issue by rapinou** [kvangent/PokeAlarm#57]
Since this (https://github.com/PokemonGoMap/PokemonGo-Map/commit/205f065f2980b81da5de21a24f2ae484e13a3842) was merged, i receive notifications for lured pokemons.
This could be great, but your code for check notify range seems not working on it, i receive notifications for lured pokemons far away from search range.
Thanks for checking this ;)

**Comment by kvangent** [comment]
Are you setting a location when you run the webhook? If the pokemon is lured or not shouldn't matter.

**Comment by rapinou** [comment]
I have never set location for the webhook server, only for the pokemap server.
It is now needed ?

**Comment by kvangent** [comment]
You only need to set it if you want to set a limit on how far away you get alerts on.

**Comment by rapinou** [comment]
Ok , I understood the operation.
But how it goes if you change the location of pokemap frontend ? The location of pokealarm does not change ?
This does not cause problems for notifications?

**Comment by kvangent** [comment]
There is currently no way to update location for PokeAlarm. It can give a distance away from one location only. If you change the location of PokemonGo-Map via the front end, PokeAlarm will continue to calculate distance from the original location give to it.

**Comment by rapinou** [comment]
Ok, i have just testing it. So if i set location, it fix my problem with receiving notifications of far away lured pokemons. And when i change location in pokemap frontend, normal notifications still works, but not lured pokemons notifications. It's ok, spam of lured pokemons have stop, it's good.
Thank you.

**Comment by rapinou** [comment]
Finally, set location doesn't fix this problem. My bad, I did my test on an old version of Pokemap which has not implemented this commit : https://github.com/PokemonGoMap/PokemonGo-Map/commit/205f065f2980b81da5de21a24f2ae484e13a3842

On a new version of Pokemap with this commit, spam notifications of far away lured pokemons continue, set location doesn't work to stop this.

**Comment by kvangent** [comment]
@rapinou So what is the problem? You are getting notification of lured Pokemon far away?

**Comment by rapinou** [comment]
Yes, get a lot of notifications for lured pokemons out of my search range.
The problem went with this commit : https://github.com/PokemonGoMap/PokemonGo-Map/commit/205f065f2980b81da5de21a24f2ae484e13a3842
If I delete these lines, spam finish.

**Comment by kvangent** [comment]
And you sure that they are out of the search range? If possible, could you add the <dist> text to one of your alarms and let me know what distance it says the lure pokemon are from (and if possible what distance they really are)?

Is it the same pokemon every time or different pokemon?

**Comment by martinsweitzer** [comment]
His issue is that search range is like -ST 5 from some location  but the pokestops you get from that location are over a much larger area (e.g. i get 160 pokestops or something some which quite far away)

**Comment by kvangent** [comment]
@rapinou Are you enabling the location limit on pokemon? Because otherwise setting the location doesn't do anything.

**Comment by rapinou** [comment]
Yes, sure they are out of range. I have verified it on the map. And it concerns all lured pokemons who appeared on lured pokestops, so not always the same.
I'm on my bed, i can't do the test for distance right now but i will take a look tomorrow.

What do you mean by location limit on pokemon ?

**Comment by rapinou** [comment]
@martinsweitzer Yes you're right, if i set step limit to 5, many pokestops out of these 5 steps appeared on the map. Maybe have to look at this side.

**Comment by kvangent** [comment]
@rapinou You can set limits on how are away pokemon are alerted to you. Check out the Pokemon Configuration page for more details.

**Comment by rapinou** [comment]
Ohh, i didn't see this new page on your wiki.
My apologies for wasting your time :/
And thanks for your tool ;)
