### ISSUE TITLE
Lost notification of existing Pokémon: "time_left has passed"?

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#58]
Earlier today I took a quick look at the map and noticed an Arcanine with still 8 minutes to depop very close to my location. Rushed to it and was able to catch it, but when I went back home I looked for PokeAlarm log and found this:

> 2016-08-08 16:36:30,115 [     alarm_manager] [   INFO] Zubat ignored: notify not enabled.
2016-08-08 16:36:55,722 [     alarm_manager] [   INFO] Arcanine ignore: time_left has passed.
2016-08-08 16:37:18,254 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.

The Arcanine was definitely there, it was showing in the map and I was able to catch it but for some reason the notification didn't fire up becaue "time_left" has passed. I assume this is a bug.

**Comment by kvangent** [comment]
What version of PokemonGo-Map are you using? Can you please list the arguments for both?

If possible, can you check your DB for the Arcanine entry and post it as well?

**Comment by Imoq** [comment]
Regarding PokemonGo-Map version, it is:

>root@raspberrypi:~/PokemonGo-Map# git log | head
commit bea23ba3ed722768a674694bc7380da5ee74b54b
Author: Hao Hu <hhu94@uw.edu>
Date:   Sat Aug 6 22:28:42 2016 -0700

>    Make location marker always be on top (#10)

I don't run PokeAlarm with any other argument than:

> python runwebhook.py

The relevant part on alarms.json:

>                 {
                        "active": "True",
                        "type":"telegram",
                        "chat_id":"-someid",
                        "bot_token":"sometoken"
                }


For PokemonGo-Map, I don't execute with any argument either, but the config.ini is:

> auth-service: google         # ptc (default) or google
username: [user1, user2, user3]
password: [pass1, pass2, pass3]
db-type: sqlite        # sqlite (default) or mysql
location: some,location
scan-delay: 10           # default 5
step-limit: 6           # default 12
display-in-console: TRUE
gmaps-key: somekey            # your Google Maps API key
webhook: http://127.0.0.1:4000
host: 192.168.1.34                 # address to listen on (default 127.0.0.1)
port: 80                 # port to listen on (default 5000)

Finally, I am unsure how to check  SQLite 3.x databases, let me do some googling (or if you know how to extract that particular data, I will be grateful).

Thank you!

**Comment by kvangent** [comment]
Navigate to the folder where the DB is at. `sqlite3 pogo.db` (or whatever your db is named
`.headers on` and `.mode columns` increase readibility. Then `SELECT * FROM pokemon WHERE pokemon_id = 59` and when try to tell me which one is the correct one.

**Comment by Imoq** [comment]
Great! Here is the info:

> sqlite> SELECT * FROM pokemon WHERE pokemon_id = 59;
encounter_id                  spawnpoint_id  pokemon_id  latitude         longitude         disappear_time
----------------------------  -------------  ----------  ---------------  ----------------  --------------------------
MTU0OTE0NTQ3OTcxMzM3NDI2MDU=  12c9c74d58b    59          43.279365438427  5.38344451327047  2016-08-08 15:01:30.764000
sqlite>

Thanks!

**Comment by kvangent** [comment]
Are you running both on the same machine? What timezone are you in?

**Comment by Imoq** [comment]
Apologies, I went to bed last night after posting. They are both running on same Raspberry Pi, I am in CEST time zone (UTC +2).

It does seem strange that the DB has Arcanine listed at 15:01 when the notification was at 16:36, it doesn't make sense and could very well be a Map bug instead, no?

**Comment by kvangent** [comment]
Yes, I think it was a spawn with a 30 or 45 minute time. The map doesn't seem to be handling these properly and gives time already passed instead of a future time. The DB entry is in UTC, so it probably actually despawned at 17:01, making a 16:36 notification likely for a 30 minute spawn.

**Comment by Imoq** [comment]
ok, and since I haven't seen any other issues like this in the days I have used PokeAlarm, let's say it was an isolated bug and close for now then.

Thank you very much for your support!
