### ISSUE TITLE
[Enhancement] Notify of location change

### ISSUE THREAD

**Issue by rawdr** [kvangent/PokeAlarm#59]
Is it possible to add a notification when the location of the PokemonGo-Map changes? Coordinates could be passed to link to new location as well.

Here is what shows up in my PokemonGo-Map console when location is updated (Coordinates modified to middle of nowhere):
`2016-08-08 14:24:29,580 [     Thread-3921][           app][    INFO] Changing next location: 59.7458078,-34.1829137`

But I don't know enough of how the webhook feature works to know if that data is even passed to this app in the first place.

Thanks for your time and thanks for the app. :)

**Comment by fatmagic** [comment]
This would be helpful. I share my map with another person who will change the location every now and then (and vice versa), would be nice to know when it changes. Thanks kvangent!

**Comment by kvangent** [comment]
The PokemonGo-Map would need to be updated to signal when it changes it's location.

**Comment by rawdr** [comment]
Thanks kvangent. I'll look at PokemonGo-Map and probably add a feature request there... I'll return here if that gets added.

**Comment by RiberoD07** [comment]
Don't think it's offtopic necessarily so asking here. Is there a way to have it update location by itself? or what's the easiest way. I have it set up for twilio atm and want it to message me of nearby pokemon everywhere I go not just the location I originally set on my map. If i set the map up to scan follows location and just open it once on my phone does it follow? Not entirely sure as to the best way of doing this.

**Comment by Malouff** [comment]
Can we have duplicate Pokémon in alarms.json or more than one alarms.json?

Why I would use this:
During the day I would use True as I don't care about distance and use one channel. 

At Night I would want just a limited Distance close to home so I don't have to drive across town, But still have a True for a Rare Pokémon I wouldn't mind racing across town for.

If I am using myself I can just stop one server for day & start one for night. Problem Solved

I could also switch from notify all in the day to keyword notifications at night just for rare Pokémon & miss some common ones for candy as I can't filter distance as numbers are in a range. 
So not an ideal fix. 

The real problem however is if you are sharing notifications. So I would currently need to run two servers each with a alarms.json one with distance limited and another with a true.  So my PC would need to use more resources to run tow servers and I would need to run more than one webhooks &  open more than one port. 

Another question can we direct message in Slack or we need to provide a channel as I could notify on direct messages & keywords at night.  That or I would have to /mute the public channel at night & have a private channel at home as they would contain the same keywords unless I changed the default message from  <pkmn> to Home<pkmn> and did a keyword notify at night for Home<pkmn>

To get to the point I am wondering if we can have duplicate Pokémon Values (True & a Distance) for different alerts or If we need to run more than one server.

**Comment by brettgus** [comment]
@Malouff Yeah, I would like multiples as well.  

I am doing this right now.  I'm running several different alarm processes.  I'm having a php script redirect the webhook to multiple instances of PokeAlarm:
`<?php
function runhook ($url,$data) {
	$headers[] ='Host: 10.1.22.10';
	$headers[] = 'Connection: keep-alive';
	$headers[] =  'Accept-Encoding: gzip, deflate';
	$headers[] =  'Accept: */*';
	$headers[] =  'User-Agent: python-requests/2.10.0';
	$headers[] =  'Content-Length ' . strlen($data);
	$headers[] =  'Content-Type: application/json';

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($ch, CURLOPT_USERAGENT, "python-requests/2.10.0");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    $output = curl_exec($ch);
}
$phpinput =  file_get_contents('php://input');
// Each of these URLs is a separate instance of PokeAlarm
runhook("http://localhost:6000", $phpinput);
runhook("http://localhost:6001", $phpinput);
runhook("http://localhost:6002", $phpinput);
runhook("http://localhost:6003", $phpinput);`

**Comment by kvangent** [comment]
Consolidating to #148.
