### ISSUE TITLE
Something is amiss with how PokeAlarm handles webhooks

### ISSUE THREAD

**Issue by martinsweitzer** [kvangent/PokeAlarm#62]
I run pokemon map with say -ST 5 and 12 accounts (yes over kill but I was at a loss to why it was slow).  The updates I see on the map (and logs) are speedy fast covering the entire 60 nodes.  All 60 nodes are all green all the time.  And even 10 seconds there are 12 nodes updated.

If I add a -wh for pokelyzer, I have the same behavior.  Speedy fast.

If I add a -wh for pokealarm (by itself) then the scanning speed dramatically slows.  The map now will get yellow and even red nodes.  And the log has really long delays between the search threads doing work.

NOTE: previously, I had the PokeAlarm integrated directly into the Pokemon Map with the old integration.  That did not suffer any delays / slow down the scanning.  

So it seems something in how Pokemon Map and Poke Alarm are interacting via webhooks is causing massive scanning delays.

Is there anything I can turn on for logging / printing out anything to help narrow it down?

**Comment by martinsweitzer** [comment]
Well still not certain why this occurs (and it doesn't make sense) but a fun other bug is that every single worker is sending duplicate pokestop data is pretty exciting!  (e.g.  thread 0 scans in node 0  and thread 1 scans in node 1    the nodes are close to each other and so pick up some of the same/some of the same pokestops which then get webhook sent out

OH!! commenting out sending out pokestops to the send_to_webhook  and we are back to speedy fast!

**Comment by kvangent** [comment]
@martinsweitzer You mean bug in the PokemonGo-Map? My guess is this is what is slowing it down - it must be adding a crazy high amount post requests.

**Comment by martinsweitzer** [comment]
So if you did 12 workers and then when a it is upserting 290 pokestops and then if say 40 of them are lured.   So almost full overlap like 400 requests every 10 seconds or so.

But, Pokelyzer is able to handle that with no "slow down"  while pokealarm has some bottle neck or something that causes those hundreds of web requests to stall out the PokemonGo-Map

**Comment by martinsweitzer** [comment]
Ahh!  ok so with lot of logging on (e.g. every single webhook request logging).  You can watch it the PokemonGo-Map issue a webhook and then pokealarm consume it.   In lock step fashion.

So as there are 400 requests with each one taking about a second it seems there is the slow down.

**Comment by kvangent** [comment]
That one second wait on requests is on PokemonGo-Map. It starts a connection and gives it a timeout for 1 second. For some reason, PokemonGo-Map must not be registering or handling the OK response quickly enough. The Alarm is sending back a 200 (almost instantly), but the Map seems to be waiting anyway.

You could try to adding some debugging lines in the Webhook function before is sends the POST and after and see if it is getting the 200 reponse okay or not. I'll try to look into it when I can, but I don't seem to be having a similar problem for whatever reason.

**Comment by kvangent** [comment]
@martinsweitzer Are you running debian?

**Comment by martinsweitzer** [comment]
@kvangent It is getting 200 back when I was logging that.  I will get some exact timings later today.  

@kvangent I am running win64 12 cores 32 gigs of ram etc.  Both the map and the PokeAlarm are running on the same machine.  

Also when I was messing around I believe I put an App.run() in PokeAlarm and somehow was able to get the log output from the PokemonMap in that cmd.exe!

**Comment by kvangent** [comment]
@martinsweitzer Can you also try disabling ipv6 on your machine and see if that solves any issues

**Comment by martinsweitzer** [comment]
@kvangent even with ipv6 off  it was slow.   But that led me to:   FUCK http://localhost     http://127.0.0.1  and then everything is fast again   even with the many many many lures being fired off

**Comment by theresthatguy** [comment]
@martinsweitzer 127.0.0.1 is the default host if you run `python runwebhook.py` without any flags.

**Comment by martinsweitzer** [comment]
@theresthatguy the failure was from pokemongo.     -wh http://localhost    is slow   -wh http://127.0.0.1 is fast
