### ISSUE TITLE
Connection aborted when Network disconnects 

### ISSUE THREAD

**Issue by bilalkamoon** [kvangent/PokeAlarm#64]
I'm getting "ProtocolError: ('Connection aborted.', error(10054, 'An existing connection was
forcibly closed by the remote host'))" whenever my network disconnects then connects again.

And it just freezes there. Is there a way to make it try to reconnect again instead of freezing?

**Comment by kvangent** [comment]
Something I'm working on.

**Comment by kvangent** [comment]
Services will now try to reconnect via commit 700c8c6f49e3106fa263d71fa09c36688837a38f. Long disconnects (over 30 secs) may cause Pokemon to be dropped.
