### ISSUE TITLE
Distance setting not working?

### ISSUE THREAD

**Issue by schawsk** [kvangent/PokeAlarm#66]
So, the wiki describes that when you set the flag for a pokemon in alarms.json neither to true or false, but a number, it will only alert you of pokemon within a distance away of me according to that number. However when I do that, I am always alerted of all pokemon of that type, no matter how close or far they are.
I am running pokemon go map with a server (-os) flag at my current position and then several worker in no server mode (-ns flag) from other positions around me in order to scan the map faster.

So the question is, is this due to my setup (every pokemon is never darther than a few meters from a worker, even though they can be far from the servers location), or do I have to input my location somehow directly to pokealarm, or is this simply a bug?

**Comment by kvangent** [comment]
Yes, you need to input your location in with -l or --location. It will calculate all distances from this point.

**Comment by boadude** [comment]
Got the same error, i put 10 meters and show me pokemons in a big distance away... not working ...

**Comment by kvangent** [comment]
@boadude It's not working as in it doesn't work for you? Or it's not working as in it stopped working?

Please open an issue and stick to the issue template if you haven't figured it out.
