### ISSUE TITLE
Not getting any notifications.

### ISSUE THREAD

**Issue by joveice** [kvangent/PokeAlarm#67]
## Your Environment

Operating System:Ubuntu 16.04
Environment name and version (e.g. Python 2.7):
PokemonGo-Map command: `python /home/user/pokemon/runserver.py -os -l '69.649606 18.955858' -P 5002 -H 0.0.0.0 -fl -wh https://127.0.0.1:5000`
PokeAlarm command: `python /home/user/pokealarm/runwebhook.py -H 127.0.0.1 -P 5000`

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active": "True",
			"type":"pushbullet",
			"api_key":"api",
			"channel":"id"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"",
			"channel":"#general"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"",
			"auth_token":"",
			"to_number":"+11234567890",
			"from_number":"+11234567890"
		},
		{
		        "active": "False",
		        "type":"telegram",
		        "chat_id":"your bot chat ID",
		        "bot_token":"your bot API"
    		},
		{
                        "active": "False",
                        "type": "pushover",
                        "app_token": "",
                        "user_key": ""
                }
	],
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"False",
		"Charmander":"False",
		"Charmeleon":"False",
		"Charizard":"False",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"False",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"False",
		"Sandshrew":"False",
		"Sandslash":"False",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"False",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"False",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"False",
		"Jigglypuff":"False",
		"Wigglytuff":"False",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"False",
		"Persian":"False",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"False",
		"Growlithe":"False",
		"Arcanine":"False",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"False",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"False",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"False",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"False",
		"Ponyta":"False",
		"Rapidash":"False",
		"Slowpoke":"False",
		"Slowbro":"False",
		"Magnemite":"False",
		"Magneton":"False",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"False",
		"Seel":"False",
		"Dewgong":"False",
		"Grimer":"False",
		"Muk":"False",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"False",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"False",
		"Exeggcute":"False",
		"Exeggutor":"False",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"False",
		"Hitmonchan":"False",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"False",
		"Rhyhorn":"False",
		"Rhydon":"False",
		"Chansey":"False",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"False",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"False",
		"Lapras":"False",
		"Ditto":"False",
		"Eevee":"True",
		"Vaporeon":"False",
		"Jolteon":"False",
		"Flareon":"False",
		"Porygon":"False",
		"Omanyte":"False",
		"Omastar":"False",
		"Kabuto":"False",
		"Kabutops":"False",
		"Aerodactyl":"False",
		"Snorlax":"False",
		"Articuno":"False",
		"Zapdos":"False",
		"Moltres":"False",
		"Dratini":"False",
		"Dragonair":"False",
		"Dragonite":"False",
		"Mewtwo":"False",
		"Mew":"False"
	}
}

```

##Troubleshooting Checklist
- [x] Updated PokemonGo-Map
- [x] Updated PokeAlarm
- [x] Check the Wiki for specified Service

**Comment by joveice** [comment]
Added slacker, still no notifications. just the startup one

**Comment by kvangent** [comment]
Use `-wh http://127.0.0.1:5000` - No s on the http.

**Comment by joveice** [comment]
Changed, still no notifications

**Comment by kvangent** [comment]
Can you post your commands for both again please? As well as your console output from the Alarm?

**Comment by joveice** [comment]
pokealarm command
python /user/ubuntrix/pokealarm/runwebhook.py -H 127.0.0.1 -P 5000

pokemap command 
/home/user/pokemon/runserver.py -os -l '69.649606 18.955858' -P 5002 -H 0.0.0.0 -fl -wh http://127.0.0.1:5000

log from pokealarm
`2016-08-10 00:47:42,991 [     alarm_manager] [   INFO] You will be notified of the following pokemon:
Eevee, Snorlax, Dragonite, Mewtwo, Mew
2016-08-10 00:47:44,333 [  pushbullet_alarm] [   INFO] Pushing to channel ubnpmtromso.
2016-08-10 00:47:44,333 [  pushbullet_alarm] [   INFO] Pushbullet Alarm intialized
2016-08-10 00:47:44,636 [       slack_alarm] [   INFO] Slack Alarm intialized
2016-08-10 00:47:45,117 [     alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-08-10 00:47:45,117 [     alarm_manager] [   INFO] Alarm not activated: telegram because value not set to "True"
2016-08-10 00:47:45,117 [     alarm_manager] [   INFO] Alarm not activated: pushover because value not set to "True"
2016-08-10 00:47:45,118 [     alarm_manager] [   INFO] PokeAlarm has started! Your alarms should trigger now.
2016-08-10 00:47:45,118 [        runwebhook] [   INFO] Webhook server running on http://127.0.0.1:5000`
Both slack and pushbullet gets the PokeAlarm activated but nothing more.

**Comment by kvangent** [comment]
@joveice  Are you running multiple workers?

**Comment by joveice** [comment]
Yes 56

**Comment by joveice** [comment]
Added -wh http:127.0.0.1:5000 to a random worker and removed it from the starter, this worked, tho if I add it to all the workers will port confliction happen or does it work with -wh sameport on each?

**Comment by kvangent** [comment]
@joveice The wh command needs to be added to each worked The wh address is the address which they need to send information to - its the address the Alarm is listening for . So yes, they all should point to the same port/ip.

**Comment by joveice** [comment]
Thank you it fixed the issue
