### ISSUE TITLE
[BUG] Pokemon aren't sent because time_left has passed

### ISSUE THREAD

**Issue by kvangent** [kvangent/PokeAlarm#68]
**Problem**: Currently PokemonGo-Map is mishandling 30 and 45 minute spawns and sending past dissapeared_times. This causes pokemon with long times to be skipped over by the Alarm.

**Possible Solutions**:
PR for PokemonGo-Map to handle the times correctly.
Clientside fix - Look for negative times and account somehow?

**Comment by brettgus** [comment]
FYI, not sure if this was clear but this is what I was trying to communicate in #37
