### ISSUE TITLE
[ENHANCEMENT] Twitter?

### ISSUE THREAD

**Issue by joveice** [kvangent/PokeAlarm#70]
Title says it all, have it post to twitter using their api?

**Comment by kvangent** [comment]
Yes, its on the todo list.

**Comment by ninthwalker** [comment]
Just saw your twitter push and wanted to say thanks. Works for me after I manually added the section to alarm.json. Nice to have twitter back!

**Comment by rjwestman** [comment]
@ninthwalker where/how did you see it? i'd love to do it that way.

**Comment by kvangent** [comment]
@rjwestman It was commit db947b7c41411c8b1c6f2e7a027ad726ab5b83ad. There is an example in the defaults but I haven't gotten around to making a wiki page yet.

**Comment by rjwestman** [comment]
saw it and made it work! thanks a lot.
