### ISSUE TITLE
[ENHANCEMENT] Add postal codes to <addr>

### ISSUE THREAD

**Issue by theresthatguy** [kvangent/PokeAlarm#71]
Currently, `<addr>` will display something like 3141 Pi St. When notifications are coming from a large area it would be nice to know where said street is by including the postal code; after the change `<addr>` would display above example as 3141 Pi St. 59265. If nearest address cannot be obtained, use the postal code instead of saying "None".

tl;dr
`"notify_text":"A wild <pkmn> has appeared near <addr>."` outputs "A wild Mew has appeared near 3141 Pi St. 59265."

**Comment by RiberoD07** [comment]
could also have it so that it says how far away from you in metres it is? That way no need to click on the link if it's too far

**Comment by kvangent** [comment]
@RiberoD07 This is already a feature.

**Comment by RiberoD07** [comment]
@kvangent ah didn't know since i never passed -l thanks!

**Comment by theresthatguy** [comment]
@RiberoD07, also don't hijack threads please.

**Comment by RiberoD07** [comment]
@theresthatguy i'm sorry for hijacking your thread not sure what you mean by the return None but i just made a PR so that <addr> also shows the postal code and not just the housenumber and streetname
#80

**Comment by kvangent** [comment]
`<postal>` has been added to the dynamic text substitution options. Check out the Wiki page for Alarms Configuration and your preferred service for more details.
