### ISSUE TITLE
[ENHANCEMENT]Mini Maps for Telegram Channel

### ISSUE THREAD

**Issue by alexccs** [kvangent/PokeAlarm#72]
Currently, PokeAlarm will post a gmap link in the alert.  By providing mini maps utilizing the telegram sendlocation feature, it will be more convenience for users as they can access the map directly in telegram without waiting for google maps to open externally, or even no need to open the map as they can easily recognize if a location is too far from the mini map.  

Tried to add the feature by myself but dunno how to pass the lat and long variables in the codes.  Static values already tested and can trigger the bot to post mini maps.

in telegram_alarm.py:
message = self.client.sendMessage(self.channel, '<b>' + header + '</b> \n' + body_text, parse_mode='HTML', disable_web_page_preview='False')
message = self.client.sendLocation(self.channel, latitude='latitude', longitude='longitude')

**Comment by Bart274** [comment]
That would be a nice enhancement! :)

**Comment by kvangent** [comment]
@alexccs @Bart274 Added in commit 39ed900199ad0dc11d5eec1d11a66ac034ffcbab. Can be disabled by including send_map set to False.

**Comment by Bart274** [comment]
@kvangent it works great :D 
would it be possible to remove the google maps url from the message when the mini map is enabled?

**Comment by kvangent** [comment]
@Bart274 You can certainly do that by customizing the url field. Checkout the the Alarms Config and Telegram pages in the wiki for more information.

**Comment by Bart274** [comment]
@kvangent thanks for the suggestion, that did the trick indeed :)
