### ISSUE TITLE
[ENHANCEMENT] Google Maps walking distance calculation

### ISSUE THREAD

**Issue by fgnn** [kvangent/PokeAlarm#74]
By using the google map api to get directions from your location to the pokemons location, you can get an accurate walking distance and time. While at work, I can see at a glance whether I can walk to the pokemon in time or not without having to open the link.

The code in the fork works and I've been using it for a few days. Unfortunately I am a subversion guy and don't understand git at all. Something went very wrong with the commit and pull request... Hopefully someone can do a proper update of the code. Its now a few commits behind master since I waited a day.
https://github.com/fgnn/PokeAlarm/commit/dbe284d0dd22d374eb8ecc154e0f1a75255e7f68

features:
 - added google-maps api key to the config file.
 - implemented different messages for slack only.
 - unicode arrow indicating the compass direction from you to the pokemon (8 directions)
 - time and distance walking to pokemon
 - a "walking"emoji if you can walk there in time, otherwise a red "no" emoji.

**Comment by fgnn** [comment]
<walk/dont walk>[<walking distance in meters><compass direction><watch emoji><walking time in minutes>]

![screenshot_2016-08-09-21-44-53](https://cloud.githubusercontent.com/assets/12035623/17541266/ee225970-5e7a-11e6-95a5-068d850c1dc3.png)

**Comment by jameson167** [comment]
Wow this is incredible, would love to see it integrated

**Comment by kvangent** [comment]
@fgnn If you could provide me the snippet of the code you used, I will look into this.

**Comment by brettgus** [comment]
Yeah this would be awesome!  It looks like @fgnn cited his commits... maybe I'm blind but I don't see the changes there?

The [DistanceMatrix Googlemaps API](https://developers.google.com/maps/documentation/distance-matrix/intro#DistanceMatrixRequests) is what we should use.  However, while in the docs they say an API key is a required paremeter, it doesn't actually appear to be.

It'd be a bit of a non-starter, as every poke alarm would result in an API call which would count against the quote.

It's as easy as querying here for a json and change the paremeters accordingly:
[https://maps.googleapis.com/maps/api/distancematrix/json?origins=43.041780,-87.909758&destinations=43.043215,-87.903911&mode=walking&units=imperial]

There's actually a python package, [googlemaps](https://github.com/googlemaps/google-maps-services-python), that will query this.  However, the constructor refuses to work without an API key being supplied.
import googlemaps
gmaps = googlemaps.Client(key="YOURKEYHERE")
dist = gmaps.distance_matrix((43.041780,-87.909758),(43.043215,-87.903911), 'walking')
print "%s" % dist.get("rows")[0].get("elements")[0].get("duration").get("text")

**Comment by fgnn** [comment]
That's exactly how I implemented it.

I looked at my fork again and it looks like I messed up even more than I thought and the code didn't get uploaded at all. 

Tonight I will take another stab at attempting to get it uploaded.

**Comment by fgnn** [comment]
Finally figured out how to use git!

Pull request located here:

https://github.com/kvangent/PokeAlarm/pull/112

**Comment by kvangent** [comment]
This should now be implimented as of commit fc60ddc7231c1ce515f2d343022eb33ebf80464d. You can add in the following options

`<walk_time>` or `<walk_dist>`
`<bike_time>` or `<bike_dist>`
`<drive_time>` or `<drive_dist>`
