### ISSUE TITLE
[ENHANCEMENT] Skype support

### ISSUE THREAD

**Issue by lota7** [kvangent/PokeAlarm#78]
## Enhancement Description
Request to add Skype support, to report to a specific group which the skype user is invited to.

## Use cases

Skype is used by alot of people, and has well documented API for implementation.

##Other Links

Skype4Py  -- https://github.com/Skype4Py/Skype4Py

**Comment by kvangent** [comment]
@lota7 In the future, please stick to one of the issue templates.

I will look into Skype being added in the future.

**Comment by lota7** [comment]
@kvangent Sorry mate! I've updated it now. Thanks for your work!

**Comment by lota7** [comment]
@kvangent Hi, love this alarm, but if you could get Skype support it'd be great! Please do skype! :D

**Comment by kvangent** [comment]
I looked into Skype but was unable to find a suitable module using Python 2.7 and the API seems to require approval from Microsoft before you can get an API key. If anyone knows of a better way, please let mw know and I'll look into this gain.

**Comment by lota7** [comment]
@kvangent Didnt it work with Skype4Py -- https://github.com/Skype4Py/Skype4Py ? That should be a good module
