### ISSUE TITLE
[Enhancement] Join

### ISSUE THREAD

**Issue by smoothlystable** [kvangent/PokeAlarm#79]
## Enhancement Description

Add support for Join (by joaoapps)
## Use cases

This would open up for Join users.
Join is a "Pushbullet alternative". But got plenty of support for other joaoapps (AutoApps), which gives you really good Tasker integration. 
## Other Links

[Info](http://joaoapps.com/join/)
[API](http://joaoapps.com/join/api/)

**Comment by kvangent** [comment]
@smoothlystable In the future please use the Issue Templates provided.

I'm looking into different services to add - I will take a look at Join.

**Comment by smoothlystable** [comment]
Sorry about that, I've updated the issue now.

**Comment by kvangent** [comment]
Service Requests are now going to be handled under issue #147.
