### ISSUE TITLE
[BUG] After Slack Icon Update No More Notifications

### ISSUE THREAD

**Issue by jameson167** [kvangent/PokeAlarm#82]
Thanks for the help this morning. Everything was working fine and when I saw your message about the Slack Icon fix I decided to do a git pull and upgrade the files. After doing the git pull upgrade and turning the alarm back on, it no longer posts to Slack anymore.

I made no other configuration changes just 1 pull and re-start service
![image](https://cloud.githubusercontent.com/assets/20566412/17569190/f3718da2-5efb-11e6-8b15-bb3bf6ccc06e.png)

**Comment by kvangent** [comment]
@jameson167 In the future, please make sure you are using the issue templates so I can have an easier time diagnosing your problem.
