### ISSUE TITLE
[ENHANCEMENT] Facebook Messenger Support :)

### ISSUE THREAD

**Issue by Teelve** [kvangent/PokeAlarm#83]
Is it even possible ? I would like to automaticaly share pokemons locations through a facebook messenger conversation

**Comment by kvangent** [comment]
@Teelve In the future, please make sure you use the given issue template.

I am currently looking at other services to add. Facebook Messenger is on that list.

**Comment by kvangent** [comment]
I've look into Facebook Messenger, and they have a very vigorous screening method for getting access to BOT API keys. Because of this Facebook Messenger will probably not happen unless someone can present me with an easier way to do it.
