### ISSUE TITLE
[Advanced Enhancement] Area of Notification

### ISSUE THREAD

**Issue by lota7** [kvangent/PokeAlarm#85]
## Feature Description

Add possibility of limiting area of notifications.
For example I have scanners setup on alot of places for friends, but I only want notifications on the area close to myself.
Could make it by drawing a user defined area from position top left to bottom right, as to draw a square.

Further implementation of the idea would be to have each of these set to notify on a different channel.
For example I have 3 areas I want to cover. 
Using Slack as choice of app.
Each have different area of notifications, and submits notification to their own channel in slack.

So every user that wants notification on any given area just has to join that channel in Slack.

## Your Environment

Operating System:  Win 10, 64bit
Environment name and version (e.g. Python 2.7): Python 2.7

**Comment by kvangent** [comment]
@lota7 There is already a feature to limit the range of Pokemon to a certain distance. Please take a look at the Pokemon Configuration part of the Wiki. 

If you want to run 3 different areas, you can run multiple Alarms each with their own configuration.
