### ISSUE TITLE
[Enhancement]Auth for webhook

### ISSUE THREAD

**Issue by GareRam** [kvangent/PokeAlarm#91]
## Enhancement Description
(Basic) Possibilities to have some sort of authentication for webhooks.

## Use cases
I'm running a mapserver with mySQL database, various other computers are scanning for pokemon and upserting them in the database over the internet, making for one big map of our city (this spreads cpu load and prevents bans). I could enable webhooks and open the associated port in my router, but that would allow for anyone with the address and port to insert (false) webhooks into the PokeAlarm. 

Authentication solves this problem.

**Comment by kvangent** [comment]
@GareRam This would require a change to PokemonGO-Map as well.

**Comment by GareRam** [comment]
I solved my issue by running your code on all the local machines as well, and pushing to the various API's (Slack/Twitter).
