### ISSUE TITLE
[ENHANCEMENT] Ability to add custom location descriptions

### ISSUE THREAD

**Issue by hagehg** [kvangent/PokeAlarm#92]
## Enhancement Description
Implement a way to add custom descriptions for coordinates (lat & long combination).

i.e.:
40.723260, -73.991055, Bus stop
40.718389, -73.994896, Grandma's house

## Use cases

When using &#60;addr> in the notifications, it will give you an approximate address, but the address is often pretty vague and doesn't really help you.

Since Pokemon spawn on fixed locations, it would be useful to be able to add more meaningful descriptions for some of these spawnpoints, so that when you recieve a notification you immideatly know which location the Pokemon spawned.

Thanks!

**Comment by kvangent** [comment]
@hagehg This probably won't happen soon, it's a little bit of a logistical nightmare. I'm interested in looking in to it.

**Comment by reme-dy** [comment]
The geopy module does have an option for a more descriptive location thought it will require an additional API key and some time to implement.

Another option would be to use the specific spawnpoint_id from the database.  That would, however, assume that the user has harvested spawnpoints and knows how to identify a specific spawnpoint.

**Comment by kvangent** [comment]
(I think) the best way to do this would be to specify a Latitude, Longitude, and a distance and anything within that distance from it would be pinned as that area. That being said I don't feel this is an overly useful feature and don't plan to incorporate it any time soon. If anyone wants to do it and submit a PR that is good with me.
