### ISSUE TITLE
[ENHANCEMENT] Slack Wiki

### ISSUE THREAD

**Issue by Malouff** [kvangent/PokeAlarm#93]
## Enhancement Description
Update the Slack Wiki's Optional Parameters & Special Pokemon Names

## Use cases
Help Users Create a Slack Config

## Problem Description
Some Optional Parameters are not working as expected.
- [ ] _Slack message formatting not working in custom text_
- [ ] `pkmn_channel` Could be easier to understand
- [ ] How to use `url` parameter, can it be used to see your server map at that location?

## Example
**Optional Parameters**

Parameters | Description	| Default
------------ | ------------- | -------------
`title` | Notification text to begin the message | A wild `<pkmn>` has appeared!
`url` | Link to be added to notification text | `<gmaps>`
`body` | Additional text to be added to the message | Available until `<24h_time>` (`<time_left>`).
`username` | Username the bot should post the message as | `<pkmn>`
`pkmn_channel` | Custom channel for pokemon * | None - pushes to user channel

*Note: `channel` is still a Required Parameter but will not be used so if you want to use both create more than one Slack Config.
Dynamic Slack Channels must exist or will try 5 times to post and fail
Use Dynamic Substitutions to create the dynamic Pokémon channels
Example: `"pkmn_channel":"#<id>-<pkmn>",`
`<id>` is 1-151 not 001-151 So `#1-bulbasaur to #151-mew`

- [x] **Nidoran♀** changed to **nidoranf** to allow channels to work.
- [x] **Nidoran♂** changed to **nidoranm** to allow channels to work.
- [x] **Farfetch'd**  changed to **farfetched** to allow channels to work.
- [x] **Mr. Mime**  changed to **mrmime** to allow channels to work.

*Remember to end each custom parameters with a comma `,` and the last parameter should not have one.

## Other Links
**[Multiline Messages](https://api.slack.com/docs/message-formatting#multiline_messages)**
**I have added a `\n` to my custom text but it does not make it a multiline message it just shows the `\n`**
Can I please get an example on how to pass a `\n` in the custom text?

Later on, It would be cool to add:
- [ ] [Emoji](https://api.slack.com/docs/message-formatting#emoji)
You could use this [project ](https://github.com/lambtron/emojipacks)to mass upload [Pokémon emoji icons](https://raw.githubusercontent.com/jaylynch/pokemoji/master/pokemon-by-name.yaml ) to slack
We could even create a Pokémon Rarity Emoji to attach to the message or it's [type/types](http://i.imgur.com/BSrwLA4.png)
- [ ] [Color Formatting for Rarity](https://api.slack.com/docs/message-formatting#formatting_and_attachments)
- [ ] [Attaching a mini map like Telegram](https://api.slack.com/docs/message-buttons#confirmation_fields)
- [ ] Color background behind Pokémon Bot image for Rarity
- [ ] How to Identify A wild `<pkmn>` from a lured  `<pkmn>` 

Maybe use code from https://github.com/kvangent/PokeAlarm/pull/87 and create a new Dynamic Substitution for Lured and Wild

**Comment by kvangent** [comment]
@Malouff Are you interested in becoming a contributer and managing issues and wiki pages for me?

**Comment by Malouff** [comment]
Thanks for the offer but I don't understand python and it took me a lot of edits to make the issue request and understand how to format with the Markdown Styling

I did look at slack_alarm.py and think I see what would need to change to fix Mr. Mime &  Farfetch'd

`Line 37 args = {
Line 38			'channel': channel.replace(u"\u2642", "M").replace(u"\u2640", "F"),
Line 39			'username': replace(self.username, pkinfo),
Line 40			'text': '<{}|{}> {}'.format(link,  title , body_text),
Line 41			'icon_url': 'https://raw.githubusercontent.com/PokemonGoMap/PokemonGo-Map/develop/static/icons/{}.png'.format(pkinfo['id'])
Line 42		}
Line 43		try_sending(log, self.connect, "Slack", self.client.chat.post_message, args)`

**Comment by kvangent** [comment]
@Malouff I actually just pushed a big rework to slack. Farfetche'd comes out to farfetched and Mr. Mime is mrmime.
