### ISSUE TITLE
[Enhancement] notify on nearby lured pokemon and distinguish from wild

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#95]
[ENHANCEMENT]

## Problem Description

Awesome to see that we can filter out is_lured by the new `-sl` flag.  I'm thinking about running a second instance of your webhook just to detect lured pokemon within a short range of a given distance.  Then I'll get a notification of a wanted pokemon just spawned at a nearby lure.

I'm not sure what the best way is to notify nearby lured pokemon, e.g., 20 meters from [lat,lon].  Any ideas?

## Your Environment

Operating System:
Python Version: (use `python -V`)
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>`

Did the issue persist after restarting the script?: yes/no

##Console Output

```
	<CONSOLE OUTPUT GOES HERE>
```

## Your Alarms Config

```json
    <CONFIG HERE>
```

##Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokemonGo-Map
[X] Checked the Wiki for specified Service

## Use cases

##Other Links

**Comment by kvangent** [comment]
You can already limit Pokemon based on their distance - check out the Pokemon Configuration page for more details.

**Comment by reme-dy** [comment]
I should have been clearer, my request was for lured pokemon only.  Right now the `-sl` flag is all or nothing.  It would be nice to specifically filter lured pokemon on distance.  For example, notify a regular spawned dragonite at 1000m, or a lured dragonite at 20m.

**Comment by kvangent** [comment]
They just changed lured pokemon, so it doesn't look like they can be filtered at all right now.

**Comment by reme-dy** [comment]
Gotcha, thanks for being on top of this!  Looking forward to the next set of updates.
