### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Samras** [kvangent/PokeAlarm#96]
## Your Environment

Operating System:  Debian 8
Python Version: 2.7 (use `python -V`)  
PokemonGo-Map startup command: `python runserver.py -ns -l 'XXXX' -st 3 -a ptc -u millions9275769 -p 'lXXXX1' -k XXXX`  
PokeAlarm startup command: `python runwebhook.py`

Did the issue persist after restarting the script?: yes

##Console Output

```
	 Webhook server running on http://127.0.0.1:4000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/poke/pka/PokeAlarm/alarms/alarm_manager.py", line 64, in run
    log.debug("Request processed for #%s" % data['message']['pokemon_id'])
KeyError: 'pokemon_id'


```

## Your Alarms Config

```json
    
{
        "alarms":[
                {
                        "active":"False",
                        "type":"pushbullet",
                        "api_key":"YOUR_API_KEY"
                },
                {
                        "active": "False",
                        "type":"slack",
                        "api_key":"YOUR_API_KEY",
                        "channel":"#general"
                },
                {
                        "active": "False",
                        "type":"twilio",
                        "account_sid":"YOUR_API_KEY",
                        "auth_token":"YOUR_AUTH_TOKEN",
                        "from_number":"YOUR_FROM_NUM",
                        "to_number":"YOUR_TO_NUM"
                },
                {
                        "active": "True",
                        "type":"telegram",
                        "bot_token":"",
                        "chat_id":""
                },
                {
                        "active": "False",
                        "type": "pushover",
                        "app_token": "",
                        "user_key": ""
                }

```

##Troubleshooting Checklist
[X ] Most recent version of PokemonGo-Map
[X ] Most recent version of PokemonGo-Map
[X] Checked the Wiki for specified Service

**Comment by Malouff** [comment]
Looks like you are only using Telegram '"active": "True",'
You however did not supply any arguments for the other required fields.
'"bot_token":"'You Need YOUR_BOT_TOKEN Here '",'
'"chat_id":"'You Need YOUR_CHAT_ID Here '"'

Look at the Telegram Wiki [How to get API Key](https://github.com/kvangent/PokeAlarm/wiki/Telegram#how-to-get-api-key) to get your values to enter there.

**Comment by Samras** [comment]
Yeah i know. but i deleted them cause its private data. im using it with filled in fields. with chat id and bot token ;)

**Comment by kvangent** [comment]
Same as #97 (but his title is more clear).

Working on a fix.

**Comment by kvangent** [comment]
@Samras Could you pull the latest update and tell me if you still have problems?
