### ISSUE TITLE
[Enhancement] Slack - set topic and first post to pokemon names that will be notified

### ISSUE THREAD

**Issue by reme-dy** [kvangent/PokeAlarm#98]
## Enhancement Description

It'd be nice if PokeAlarm would set the Slack channel topic to list the pokemon that will be monitored.  The first post when PokeAlarm is activated could also post the pokemon list.

Here's the link to the Slack API SetTopic method:
[https://api.slack.com/methods/channels.setTopic](https://api.slack.com/methods/channels.setTopic)
 

Thanks!

**Comment by brettgus** [comment]
There's a 100 character limit on slack topics.  That doesn't allow for many pokemon in the title.  I guess it'd be possible to list poke ids in a shortened format "Monitored pokemon: 1,5,7,8,9,10,11,15,120", although it's still possible that that could go over 100 characters if enough pokemon are monitored.

Another option might be pinning a message?

**Comment by brettgus** [comment]
Implemented this in #187

**Comment by kvangent** [comment]
Merged in f37cc80111c5899ba3f0231f114123c9a8a0bdff.
